# Check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.13.3/www/docs/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: vdl
dist: ./dist

before:
  hooks:
    - task deps
    - task tc:build:wasm
    # - task pg:build

builds:
  - dir: ./toolchain
    main: ./cmd/vdl
    binary: vdl
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/varavelio/vdl/toolchain/internal/version.Version={{.Version}}
      - -X github.com/varavelio/vdl/toolchain/internal/version.Commit={{.ShortCommit}}
      - -X github.com/varavelio/vdl/toolchain/internal/version.Date={{.CommitDate}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ tolower .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
  algorithm: sha256
