# yaml-language-server: $schema=https://taskfile.dev/schema.json

#####################################################################
# Docs: https://taskfile.dev                                        #
#                                                                   #
# Use npx with the "--no" argument to ensure that dependencies with #
# versions different from those in package.json are not downloaded. #
#####################################################################

###############################################################################
# BUILD PIPELINE:                                                             #
### Install deps -> Build WASM binary -> Build Playground -> Build VDL binary #
###############################################################################

version: "3"

tasks:
  default:
    desc: List all available commands
    cmd: task --list-all

  ##############
  # ROOT TASKS #
  ##############

  ci:
    desc: "Run full CI pipeline (deps, test, lint, build)"
    cmds:
      - task: deps
      - task: test
      - task: lint
      - task: build

  release:
    desc: "Build all for release by running ./scripts/release"
    cmds:
      - task: deps
      - go run -C ./scripts ./release/.

  deps:
    desc: "Install dependencies for all subprojects (Go, Node, etc)"
    cmds:
      - npm install
      - cd ./toolchain && go mod download
      - cd ./playground && npm install
      - cd ./docs && npm install

  build:
    desc: "Build everything for current system (WASM, Playground, and VDL CLI)"
    cmds:
      - task: tc:build:wasm # <- Required by the playground
      - task: pg:build # <- Required by the final VDL binary
      - task: tc:build:vdl

  codegen:
    desc: "Run all code generators"
    cmds:
      - task: tc:install
      - vdl generate

  format:
    desc: "Format all code"
    cmds:
      - cd ./toolchain && go fmt ./...
      - cd ./toolchain && go run ./cmd/vdl/. format
      - npx --no @biomejs/biome format --write --config-path ./biome.json --no-errors-on-unmatched .
      - dprint fmt --config ./dprint.json --log-level warn

  test:
    desc: "Run all tests (Toolchain, Toolchain E2E and Playground)"
    cmds:
      - cd ./toolchain && go test ./...
      - cd ./toolchain && go test -race ./...
      - cd ./playground && npx --no vitest run

  lint:
    desc: "Lint all code"
    cmds:
      - cd ./toolchain && golangci-lint run ./...
      - |
        cd ./toolchain
        UNFORMATTED=$(gofmt -l .)
        if [ -n "$UNFORMATTED" ]; then
          echo "The following files are not formatted correctly:"
          echo "$UNFORMATTED"
          exit 1
        fi
      - cd ./playground && npx --no svelte-kit sync
      - cd ./playground && npx --no svelte-check --tsconfig ./tsconfig.json
      - npx --no biome lint ./playground ./installers/npm ./docs --config-path ./biome.json
      - npx --no @biomejs/biome format --config-path ./biome.json --no-errors-on-unmatched .
      - dprint check --config ./dprint.json --log-level warn

  ###################
  # TOOLCHAIN TASKS #
  ###################

  tc:install:
    desc: "Toolchain: Install 'vdl' binary to local GOPATH"
    dir: ./toolchain
    cmd: go install ./cmd/vdl/.

  tc:build:wasm:
    desc: "Toolchain: Build WASM binary for Playground"
    dir: ./toolchain
    cmds:
      - GOOS=js GOARCH=wasm go build -o ./dist/vdl.wasm ./cmd/vdlwasm/.
      - cp "/usr/local/go/lib/wasm/wasm_exec.js" ./dist/wasm_exec.js

  tc:build:vdl:
    desc: "Toolchain: Cross-compile VDL CLI for all platforms"
    dir: ./toolchain
    cmds:
      # LINUX builds
      - GOOS=linux GOARCH=amd64 go build -o ./dist/vdl-linux-amd64 ./cmd/vdl/.
      - GOOS=linux GOARCH=arm64 go build -o ./dist/vdl-linux-arm64 ./cmd/vdl/.

      # WINDOWS builds
      - GOOS=windows GOARCH=amd64 go build -o ./dist/vdl-windows-amd64.exe ./cmd/vdl/.
      - GOOS=windows GOARCH=arm64 go build -o ./dist/vdl-windows-arm64.exe ./cmd/vdl/.

      # DARWIN (macOS) builds
      - GOOS=darwin GOARCH=amd64 go build -o ./dist/vdl-darwin-amd64 ./cmd/vdl/.
      - GOOS=darwin GOARCH=arm64 go build -o ./dist/vdl-darwin-arm64 ./cmd/vdl/.

  ####################
  # PLAYGROUND TASKS #
  ####################

  pg:dev:
    desc: "Playground: Start Vite dev server"
    dir: ./playground
    deps:
      - tc:build:wasm
    cmd: npx --no vite dev

  pg:build:
    desc: "Playground: Build static assets for embedding"
    dir: ./playground
    deps:
      - tc:build:wasm
    cmds:
      - npx --no vite build
      - node ./postbuild.ts

  ##########################
  # VSCODE EXTENSION TASKS #
  ##########################

  vs:dev:
    desc: "VSCode: Build extension in watch mode"
    dir: ./editors/vscode
    cmds:
      - rm -rf ./dist
      - node esbuild.js --watch

  vs:build:
    desc: "VSCode: Build extension for production"
    dir: ./editors/vscode
    cmds:
      - rm -rf ./dist
      - node esbuild.js --production

  vs:package:
    desc: "VSCode: Package extension into .vsix"
    dir: ./editors/vscode
    cmds:
      - task: vs:build
      - rm -rf *.vsix
      - npx --no vsce package

  vs:package:ls:
    desc: "VSCode: List contents of packaged .vsix"
    dir: ./editors/vscode
    cmd: npx --no vsce ls

  ####################
  # INSTALLERS TASKS #
  ####################

  ##############
  # DOCS TASKS #
  ##############

  dc:dev:
    desc: "Docs: Start development server"
    dir: ./docs
    deps:
      - tc:build:wasm
    cmd: npx --no astro dev --host 0.0.0.0

  dc:build:
    desc: "Docs: Build the production docs site"
    dir: ./docs
    deps:
      - tc:build:wasm
    cmd: npx --no astro build
