# https://taskfile.dev

version: "3"

tasks:
  ci:
    desc: Run all CI tasks
    cmds:
      - task deps
      - task fmt-check
      - task lint
      - task test
      - task build

  deps:
    desc: Install all dependencies for the project
    cmds:
      - npm install
      - cd ./toolchain && go mod download
      - cd ./playground && npm install
      - cd ./docs && npm install

  build:
    desc: Builds the WASM binary, the Playground and the VDL binary
    cmds:
      - cd ./toolchain && task build:wasm # <- Required by the playground
      - cd ./playground && npm run build # <- Required by the final VDL binary
      - cd ./toolchain && task build:vdl

  setversion:
    desc: Set the version from latest git tag in the relevant files
    cmd: node ./scripts/set-version.ts

  test:
    desc: Run all repository tests
    cmds:
      - cd ./toolchain && task test
      - cd ./playground && npm run test

  lint:
    desc: Run all repository linters
    cmds:
      - cd ./toolchain && task lint
      - cd ./playground && npm run lint

  fmt:
    desc: Run all repository code formatters
    cmds:
      - prettier . --write # <- Default formatter for the root directory
      # The following commands are specific to each directory that has its
      # own formatter
      - cd ./toolchain && task fmt
      - cd ./playground && npm run fmt
      - cd ./docs && npm run fmt

  fmt-check:
    desc: Run all repository code formatter checks
    cmds:
      - cd ./toolchain && task fmt-check
      - cd ./playground && npm run fmt-check
      - cd ./docs && npm run fmt-check
