# yaml-language-server: $schema=https://taskfile.dev/schema.json

#####################################################################
# Docs: https://taskfile.dev                                        #
#                                                                   #
# Use npx with the "--no" argument to ensure that dependencies with #
# versions different from those in package.json are not downloaded. #
#####################################################################

version: "3"

tasks:
  default:
    desc: List all available commands
    cmd: task --list-all

  ##############
  # ROOT TASKS #
  ##############

  ci:
    desc: "Run full CI pipeline (deps, format, test, lint, build)"
    cmds:
      - task: deps
      - task: format
      - task: test
      - task: lint
      - task: build

  release:
    desc: "Build all for release by running ./scripts/release"
    cmds:
      - task: deps
      - go run -C ./scripts ./release/.

  deps:
    desc: "Install dependencies for all subprojects (Go, Node, etc)"
    cmds:
      - npm install
      - cd ./integrations/editors/vscode && npm install
      - cd ./integrations/syntax/textmate && npm install
      - cd ./toolchain && go mod download

  codegen:
    desc: "Run all code generators"
    cmds:
      - task: tc:install
      - vdl generate

  format:
    desc: "Format all code"
    cmds:
      - cd ./toolchain && golangci-lint fmt ./...
      - cd ./toolchain && go run ./cmd/vdl/. format
      - npx --no biome format --write --config-path ./biome.json --log-level warn --no-errors-on-unmatched .
      - npx --no dprint fmt --config ./dprint.json --log-level warn

  test:
    desc: "Run all tests"
    cmds:
      - cd ./toolchain && go test ./...
      - cd ./toolchain && go test -race ./...
      - task: tml:test

  lint:
    desc: "Lint all code"
    cmds:
      - cd ./toolchain && golangci-lint run ./...
      - npx --no biome check --config-path ./biome.json --log-level warn --no-errors-on-unmatched .
      - npx --no dprint check --config ./dprint.json --log-level warn

  build:
    desc: "Build core CLI binary"
    cmds:
      - cd ./toolchain && go build -o ./dist/vdl ./cmd/vdl/.

  docs:
    desc: "Build documentation website"
    cmd: cd ./docs && node ./themes/varapress/llms.mjs

  ###################
  # TOOLCHAIN TASKS #
  ###################

  tc:install:
    desc: "Toolchain: Install 'vdl' binary to local GOPATH"
    dir: ./toolchain
    cmd: go install ./cmd/vdl/.

  ################
  # SYNTAX TASKS #
  ################

  tml:test:
    desc: "TextMate: Test shared VDL grammar"
    dir: ./integrations/syntax/textmate
    cmd: npx --no vscode-tmgrammar-test "test/**/*.vdl" --config package.json

  ##########################
  # VSCODE EXTENSION TASKS #
  ##########################

  vs:build:
    desc: "VSCode: Build extension for production"
    dir: ./integrations/editors/vscode
    cmds:
      - mkdir -p ./integrations/editors/vscode/language
      - cp ./integrations/syntax/textmate/vdl.tmLanguage.json ./integrations/editors/vscode/language/vdl.tmLanguage.json
      - rm -rf ./dist
      - node esbuild.js --production

  vs:package:
    desc: "VSCode: Package extension into .vsix"
    dir: ./integrations/editors/vscode
    cmds:
      - task: vs:build
      - rm -rf *.vsix
      - npx --no vsce package

  vs:package:ls:
    desc: "VSCode: List contents of packaged .vsix"
    dir: ./integrations/editors/vscode
    cmd: npx --no vsce ls
