# yaml-language-server: $schema=https://taskfile.dev/schema.json

#####################################################################
# Docs: https://taskfile.dev                                        #
#                                                                   #
# Use npx with the "--no" argument to ensure that dependencies with #
# versions different from those in package.json are not downloaded. #
#####################################################################

###############################################################################
# BUILD PIPELINE:                                                             #
### Install deps -> Build WASM binary -> Build Playground -> Build VDL binary #
###############################################################################

version: "3"

tasks:
  default:
    cmd: task --list-all

  ##############
  # ROOT TASKS #
  ##############

  ci:
    desc: "Run full CI pipeline (deps, test, lint, build)"
    cmds:
      - task deps
      - task test
      - task lint
      - task build

  deps:
    desc: "Install dependencies for all subprojects (Go, Node, etc)"
    cmds:
      - npm install
      - cd ./toolchain && go mod download
      - cd ./playground && npm install
      # - cd ./docs && npm install

  build:
    desc: "Build everything (WASM, Playground, and VDL CLI)"
    cmds:
      - cd ./toolchain && task build:wasm # <- Required by the playground
      - cd ./playground && npm run build # <- Required by the final VDL binary
      - cd ./toolchain && task build:vdl

  codegen:
    desc: "Run all code generators (Schemas, Toolchain, Playground)"
    cmds:
      - task: codegen:schemas
      - task: tc:codegen
      - task: pg:codegen

  codegen:schemas:
    desc: "Generate Go code from VDL schemas"
    cmds:
      - cd ./toolchain && task install
      - vdl generate

  setversion:
    desc: "Sync project version from git tag to all files"
    cmd: node ./scripts/set-version.ts

  format:
    desc: "Format all code (Go, TS, Svelte, etc.)"
    cmds:
      - task: tc:format
      - task: pg:format
      - task: ve:format
      - npx --no prettier '**/*' '!toolchain/**' '!playground/**' '!editors/vscode/**' --write --config ./.prettierrc --ignore-path ./.prettierignore --ignore-unknown --log-level warn

  test:
    desc: "Run all tests (Toolchain, Toolchain E2E and Playground)"
    cmds:
      - task: tc:test
      - task: pg:test

  lint:
    desc: "Lint all code (Go, TS, Svelte)"
    cmds:
      - task: tc:lint
      - task: pg:lint
      - task: ve:lint
      - npx --no prettier '**/*' '!toolchain/**' '!playground/**' '!editors/vscode/**' --check --config ./.prettierrc --ignore-path ./.prettierignore --ignore-unknown --log-level warn

  ###################
  # TOOLCHAIN TASKS #
  ###################

  tc:install:
    desc: "Toolchain: Install 'vdl' binary to local GOPATH"
    deps:
      - codegen
    cmd: go install ./cmd/vdl/.

  tc:build:wasm:
    desc: "Toolchain: Build WASM binary for Playground"
    deps:
      - codegen
    cmds:
      - GOOS=js GOARCH=wasm go build -o ./dist/vdl.wasm ./cmd/vdlwasm/.
      - cp "/usr/local/go/lib/wasm/wasm_exec.js" ./dist/wasm_exec.js

  tc:build:vdl:
    desc: "Toolchain: Cross-compile VDL CLI for all platforms"
    dir: ./toolchain
    deps:
      - codegen
    cmds:
      # LINUX builds
      - GOOS=linux GOARCH=amd64 go build -o ./dist/vdl-linux-amd64 ./cmd/vdl/.
      - GOOS=linux GOARCH=arm64 go build -o ./dist/vdl-linux-arm64 ./cmd/vdl/.

      # WINDOWS builds
      - GOOS=windows GOARCH=amd64 go build -o ./dist/vdl-windows-amd64.exe ./cmd/vdl/.
      - GOOS=windows GOARCH=arm64 go build -o ./dist/vdl-windows-arm64.exe ./cmd/vdl/.

      # DARWIN (macOS) builds
      - GOOS=darwin GOARCH=amd64 go build -o ./dist/vdl-darwin-amd64 ./cmd/vdl/.
      - GOOS=darwin GOARCH=arm64 go build -o ./dist/vdl-darwin-arm64 ./cmd/vdl/.

  tc:codegen:
    desc: "Toolchain: Run internal code generators"
    dir: ./toolchain
    cmds:
      - task: tc:codegen:schemas

  tc:codegen:schemas:
    desc: "Toolchain: Generate JSON Schemas from Go structs"
    dir: ./toolchain
    cmd: go run ./internal/cmd/schemagen/.

  tc:format:
    desc: "Toolchain: Format Go code and run internal formatters"
    dir: ./toolchain
    cmds:
      - npx --no prettier . --write --config ../.prettierrc --ignore-path ../.prettierignore --ignore-unknown --log-level warn
      - go fmt ./...
      - go run ./cmd/vdl/. format

  tc:test:
    desc: "Toolchain: Run unit and E2E tests"
    dir: ./toolchain
    cmds:
      - go test ./...
      - go test -race ./...

  tc:lint:
    desc: "Toolchain: Run GolangCI-Lint and format checks"
    deps: [tc:lint:golang, tc:lint:format]
    failfast: true

  tc:lint:golang:
    desc: "Toolchain: Run GolangCI-Lint"
    dir: ./toolchain
    cmd: golangci-lint run ./...

  tc:lint:format:
    desc: "Toolchain: Verify code formatting"
    dir: ./toolchain
    cmds:
      - |
        UNFORMATTED=$(gofmt -l .)
        if [ -n "$UNFORMATTED" ]; then
          echo "The following files are not formatted correctly:"
          echo "$UNFORMATTED"
          exit 1
        fi
      - npx --no prettier . --check --config ../.prettierrc --ignore-path ../.prettierignore --ignore-unknown --log-level warn

  ####################
  # PLAYGROUND TASKS #
  ####################

  pg:dev:
    desc: "Playground: Start Vite dev server"
    dir: ./playground
    cmds:
      - task: pg:codegen
      - npx --no vite dev

  pg:build:
    desc: "Playground: Build static assets for embedding"
    dir: ./playground
    cmds:
      - task: pg:codegen
      - npx --no vite build
      - node ./postbuild.ts

  pg:format:
    desc: "Playground: Format Svelte/TS code (Prettier)"
    dir: ./playground
    cmd: npx --no prettier . --write --config ../.prettierrc --ignore-path ../.prettierignore --ignore-unknown --log-level warn

  pg:lint:
    desc: "Playground: Lint Svelte/TS (Biome + Svelte Check)"
    dir: ./playground
    cmds:
      - npx --no svelte-kit sync
      - npx --no svelte-check --tsconfig ./tsconfig.json
      - npx --no biome lint .
      - npx --no prettier . --check --config ../.prettierrc --ignore-path ../.prettierignore --ignore-unknown --log-level warn

  pg:test:
    desc: "Playground: Run Vitest unit tests"
    dir: ./playground
    cmd: npx --no vitest run

  pg:codegen:
    desc: "Playground: Run internal code generators"
    dir: ./playground
    cmds:
      - task: pg:codegen:irschema

  pg:codegen:irschema:
    desc: "Playground: Generate TS types from IR JSON Schema"
    dir: ./playground
    cmd: npx --no json2ts ../toolchain/internal/core/ir/ir.schema.json > ./src/lib/irTypes.ts

  ##########################
  # VSCODE EXTENSION TASKS #
  ##########################

  ve:dev:
    desc: "VSCode: Build extension in watch mode"
    dir: ./editors/vscode
    cmds:
      - rm -rf ./dist
      - node esbuild.js --watch

  ve:build:
    desc: "VSCode: Build extension for production"
    dir: ./editors/vscode
    cmds:
      - rm -rf ./dist
      - node esbuild.js --production

  ve:package:
    desc: "VSCode: Package extension into .vsix"
    dir: ./editors/vscode
    cmds:
      - task: ve:build
      - rm -rf *.vsix
      - npx --no vsce package

  ve:package:ls:
    desc: "VSCode: List contents of packaged .vsix"
    dir: ./editors/vscode
    cmd: npx --no vsce ls

  ve:format:
    desc: "VSCode: Format extension code"
    dir: ./editors/vscode
    cmd: npx --no prettier . --write --config ../../.prettierrc --ignore-path ../../.prettierignore --ignore-unknown --log-level warn

  ve:lint:
    desc: "VSCode: Lint extension code"
    dir: ./editors/vscode
    cmd: npx --no prettier . --check --config ../../.prettierrc --ignore-path ../../.prettierignore --ignore-unknown --log-level warn

  ##############
  # DOCS TASKS #
  ##############
