// Code generated by VDL v0.4.0-alpha.5. DO NOT EDIT.
// If you edit this file, it will be overwritten the next time it is generated.

// Package locktypes contains generated code for VDL.
//
// For more information about VDL, visit https://vdl.varavel.com
package locktypes

// -----------------------------------------------------------------------------
// Domain Types
// -----------------------------------------------------------------------------

// VDL Lock File Schema.
//
// It ensures that builds are reproducible and secure by locking the exact
// cryptographic hashes of all remote dependencies (plugins and schemas and
// any other remote files).
//
// Should be generated and consumed by VDL tooling using the `vdl.lock` file
// in the project root.
type VdlLockFileSchema struct {
	// The version of the lockfile format. This should be set to 1.
	Version int64 `json:"version"`
	// A flat map of all locked remote dependencies and its SHA-256 hash.
	//
	// The key MUST be the fully resolved, canonical HTTPS URL. For GitHub
	// syntactic sugar ("owner/repo@tag"), the key will be the raw CDN URL.
	//
	// The value is the SHA-256 hash of the downloaded file's content
	// in the format "sha256-<hex-string>".
	Hashes *map[string]string `json:"hashes,omitempty"`
}

// GetVersion returns the value of Version or the zero value if the receiver or field is nil.
func (x *VdlLockFileSchema) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	var zero int64
	return zero
}

// GetVersionOr returns the value of Version or the provided default if the receiver or field is nil.
func (x *VdlLockFileSchema) GetVersionOr(defaultValue int64) int64 {
	if x != nil {
		return x.Version
	}
	return defaultValue
}

// GetHashes returns the value of Hashes or the zero value if the receiver or field is nil.
func (x *VdlLockFileSchema) GetHashes() map[string]string {
	if x != nil && x.Hashes != nil {
		return *x.Hashes
	}
	var zero map[string]string
	return zero
}

// GetHashesOr returns the value of Hashes or the provided default if the receiver or field is nil.
func (x *VdlLockFileSchema) GetHashesOr(defaultValue map[string]string) map[string]string {
	if x != nil && x.Hashes != nil {
		return *x.Hashes
	}
	return defaultValue
}

// preVdlLockFileSchema is the version of VdlLockFileSchema previous to the required field validation
type preVdlLockFileSchema struct {
	Version *int64             `json:"version,omitempty"`
	Hashes  *map[string]string `json:"hashes,omitempty"`
}

// validate validates the required fields of VdlLockFileSchema
func (p *preVdlLockFileSchema) validate() error {
	if p == nil {
		return errorMissingRequiredField("preVdlLockFileSchema is nil")
	}

	// Validation for field "version"
	if p.Version == nil {
		return errorMissingRequiredField("field version is required")
	}

	// Validation for field "hashes"

	return nil
}

// transform transforms the preVdlLockFileSchema type to the final VdlLockFileSchema type
func (p *preVdlLockFileSchema) transform() VdlLockFileSchema {
	// Transformations
	transVersion := *p.Version
	transHashes := p.Hashes

	// Assignments
	return VdlLockFileSchema{
		Version: transVersion,
		Hashes:  transHashes,
	}
}
