// Code generated by VDL v0.0.0-dev. DO NOT EDIT.
// If you edit this file, it will be overwritten the next time it is generated.

// Package configtypes contains generated code for VDL.
//
// For more information about VDL, visit https://vdl.varavel.com
package configtypes

import (
	"encoding/json"
	"fmt"
)

// -----------------------------------------------------------------------------
// Enumerations
// -----------------------------------------------------------------------------

// Import extension options for TypeScript target
type TypescriptTargetImportExtension string

// TypescriptTargetImportExtension enum values
const (
	TypescriptTargetImportExtensionNone TypescriptTargetImportExtension = "none"
	TypescriptTargetImportExtensionJs   TypescriptTargetImportExtension = ".js"
	TypescriptTargetImportExtensionTs   TypescriptTargetImportExtension = ".ts"
)

// TypescriptTargetImportExtensionList contains all valid TypescriptTargetImportExtension values.
var TypescriptTargetImportExtensionList = []TypescriptTargetImportExtension{
	TypescriptTargetImportExtensionNone,
	TypescriptTargetImportExtensionJs,
	TypescriptTargetImportExtensionTs,
}

// String returns the string representation of TypescriptTargetImportExtension.
func (e TypescriptTargetImportExtension) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid TypescriptTargetImportExtension.
func (e TypescriptTargetImportExtension) IsValid() bool {
	switch e {
	case TypescriptTargetImportExtensionNone, TypescriptTargetImportExtensionJs, TypescriptTargetImportExtensionTs:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid TypescriptTargetImportExtension member.
func (e TypescriptTargetImportExtension) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum TypescriptTargetImportExtension", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid TypescriptTargetImportExtension member.
func (e *TypescriptTargetImportExtension) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := TypescriptTargetImportExtension(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum TypescriptTargetImportExtension", s)
	}

	*e = v
	return nil
}

// -----------------------------------------------------------------------------
// Domain Types
// -----------------------------------------------------------------------------

// Configuration for generating RPC clients
type ClientTargetConfig struct {
	// Generate RPC client code
	GenClient *bool `json:"genClient,omitempty"`
}

// GetGenClient returns the value of GenClient or the zero value if the receiver or field is nil.
func (x *ClientTargetConfig) GetGenClient() bool {
	if x != nil && x.GenClient != nil {
		return *x.GenClient
	}
	var zero bool
	return zero
}

// GetGenClientOr returns the value of GenClient or the provided default if the receiver or field is nil.
func (x *ClientTargetConfig) GetGenClientOr(defaultValue bool) bool {
	if x != nil && x.GenClient != nil {
		return *x.GenClient
	}
	return defaultValue
}

// preClientTargetConfig is the version of ClientTargetConfig previous to the required field validation
type preClientTargetConfig struct {
	GenClient *bool `json:"genClient,omitempty"`
}

// validate validates the required fields of ClientTargetConfig
func (p *preClientTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preClientTargetConfig is nil")
	}

	// Validation for field "genClient"

	return nil
}

// transform transforms the preClientTargetConfig type to the final ClientTargetConfig type
func (p *preClientTargetConfig) transform() ClientTargetConfig {
	// Transformations
	transGenClient := p.GenClient

	// Assignments
	return ClientTargetConfig{
		GenClient: transGenClient,
	}
}

// Common configuration fields shared by all targets
type CommonTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *CommonTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *CommonTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *CommonTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *CommonTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *CommonTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *CommonTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// preCommonTargetConfig is the version of CommonTargetConfig previous to the required field validation
type preCommonTargetConfig struct {
	Output *string `json:"output,omitempty"`
	Clean  *bool   `json:"clean,omitempty"`
	Schema *string `json:"schema,omitempty"`
}

// validate validates the required fields of CommonTargetConfig
func (p *preCommonTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCommonTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	return nil
}

// transform transforms the preCommonTargetConfig type to the final CommonTargetConfig type
func (p *preCommonTargetConfig) transform() CommonTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema

	// Assignments
	return CommonTargetConfig{
		Output: transOutput,
		Clean:  transClean,
		Schema: transSchema,
	}
}

// Configuration for generating constants
type ConstsTargetConfig struct {
	// Generate constant definitions
	GenConsts *bool `json:"genConsts,omitempty"`
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *ConstsTargetConfig) GetGenConsts() bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *ConstsTargetConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	return defaultValue
}

// preConstsTargetConfig is the version of ConstsTargetConfig previous to the required field validation
type preConstsTargetConfig struct {
	GenConsts *bool `json:"genConsts,omitempty"`
}

// validate validates the required fields of ConstsTargetConfig
func (p *preConstsTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preConstsTargetConfig is nil")
	}

	// Validation for field "genConsts"

	return nil
}

// transform transforms the preConstsTargetConfig type to the final ConstsTargetConfig type
func (p *preConstsTargetConfig) transform() ConstsTargetConfig {
	// Transformations
	transGenConsts := p.GenConsts

	// Assignments
	return ConstsTargetConfig{
		GenConsts: transGenConsts,
	}
}

// Configuration for Dart code generation
type DartTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// Generate helper functions for patterns
	GenPatterns *bool `json:"genPatterns,omitempty"`
	// Generate constant definitions
	GenConsts *bool `json:"genConsts,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *DartTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *DartTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *DartTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *DartTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *DartTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *DartTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *DartTargetConfig) GetGenPatterns() bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *DartTargetConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *DartTargetConfig) GetGenConsts() bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *DartTargetConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	return defaultValue
}

// preDartTargetConfig is the version of DartTargetConfig previous to the required field validation
type preDartTargetConfig struct {
	Output      *string `json:"output,omitempty"`
	Clean       *bool   `json:"clean,omitempty"`
	Schema      *string `json:"schema,omitempty"`
	GenPatterns *bool   `json:"genPatterns,omitempty"`
	GenConsts   *bool   `json:"genConsts,omitempty"`
}

// validate validates the required fields of DartTargetConfig
func (p *preDartTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preDartTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "genPatterns"

	// Validation for field "genConsts"

	return nil
}

// transform transforms the preDartTargetConfig type to the final DartTargetConfig type
func (p *preDartTargetConfig) transform() DartTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transGenPatterns := p.GenPatterns
	transGenConsts := p.GenConsts

	// Assignments
	return DartTargetConfig{
		Output:      transOutput,
		Clean:       transClean,
		Schema:      transSchema,
		GenPatterns: transGenPatterns,
		GenConsts:   transGenConsts,
	}
}

// Configuration for Go code generation
type GoTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// Generate helper functions for patterns
	GenPatterns *bool `json:"genPatterns,omitempty"`
	// Generate constant definitions
	GenConsts *bool `json:"genConsts,omitempty"`
	// Generate RPC client code
	GenClient *bool `json:"genClient,omitempty"`
	// Generate RPC server interfaces and handlers
	GenServer *bool `json:"genServer,omitempty"`
	// The Go package name to use in generated files
	Package string `json:"package"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetGenPatterns() bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetGenConsts() bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	return defaultValue
}

// GetGenClient returns the value of GenClient or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetGenClient() bool {
	if x != nil && x.GenClient != nil {
		return *x.GenClient
	}
	var zero bool
	return zero
}

// GetGenClientOr returns the value of GenClient or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetGenClientOr(defaultValue bool) bool {
	if x != nil && x.GenClient != nil {
		return *x.GenClient
	}
	return defaultValue
}

// GetGenServer returns the value of GenServer or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetGenServer() bool {
	if x != nil && x.GenServer != nil {
		return *x.GenServer
	}
	var zero bool
	return zero
}

// GetGenServerOr returns the value of GenServer or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetGenServerOr(defaultValue bool) bool {
	if x != nil && x.GenServer != nil {
		return *x.GenServer
	}
	return defaultValue
}

// GetPackage returns the value of Package or the zero value if the receiver or field is nil.
func (x *GoTargetConfig) GetPackage() string {
	if x != nil {
		return x.Package
	}
	var zero string
	return zero
}

// GetPackageOr returns the value of Package or the provided default if the receiver or field is nil.
func (x *GoTargetConfig) GetPackageOr(defaultValue string) string {
	if x != nil {
		return x.Package
	}
	return defaultValue
}

// preGoTargetConfig is the version of GoTargetConfig previous to the required field validation
type preGoTargetConfig struct {
	Output      *string `json:"output,omitempty"`
	Clean       *bool   `json:"clean,omitempty"`
	Schema      *string `json:"schema,omitempty"`
	GenPatterns *bool   `json:"genPatterns,omitempty"`
	GenConsts   *bool   `json:"genConsts,omitempty"`
	GenClient   *bool   `json:"genClient,omitempty"`
	GenServer   *bool   `json:"genServer,omitempty"`
	Package     *string `json:"package,omitempty"`
}

// validate validates the required fields of GoTargetConfig
func (p *preGoTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preGoTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "genPatterns"

	// Validation for field "genConsts"

	// Validation for field "genClient"

	// Validation for field "genServer"

	// Validation for field "package"
	if p.Package == nil {
		return errorMissingRequiredField("field package is required")
	}

	return nil
}

// transform transforms the preGoTargetConfig type to the final GoTargetConfig type
func (p *preGoTargetConfig) transform() GoTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transGenPatterns := p.GenPatterns
	transGenConsts := p.GenConsts
	transGenClient := p.GenClient
	transGenServer := p.GenServer
	transPackage := *p.Package

	// Assignments
	return GoTargetConfig{
		Output:      transOutput,
		Clean:       transClean,
		Schema:      transSchema,
		GenPatterns: transGenPatterns,
		GenConsts:   transGenConsts,
		GenClient:   transGenClient,
		GenServer:   transGenServer,
		Package:     transPackage,
	}
}

// Configuration for IR (Intermediate Representation) JSON generation
type IrTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// The name of the output file
	Filename *string `json:"filename,omitempty"`
	// Output minified JSON (no indentation). Default is false (pretty-printed with 2-space indent)
	Minify *bool `json:"minify,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *IrTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *IrTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *IrTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *IrTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *IrTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *IrTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetFilename returns the value of Filename or the zero value if the receiver or field is nil.
func (x *IrTargetConfig) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	var zero string
	return zero
}

// GetFilenameOr returns the value of Filename or the provided default if the receiver or field is nil.
func (x *IrTargetConfig) GetFilenameOr(defaultValue string) string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return defaultValue
}

// GetMinify returns the value of Minify or the zero value if the receiver or field is nil.
func (x *IrTargetConfig) GetMinify() bool {
	if x != nil && x.Minify != nil {
		return *x.Minify
	}
	var zero bool
	return zero
}

// GetMinifyOr returns the value of Minify or the provided default if the receiver or field is nil.
func (x *IrTargetConfig) GetMinifyOr(defaultValue bool) bool {
	if x != nil && x.Minify != nil {
		return *x.Minify
	}
	return defaultValue
}

// preIrTargetConfig is the version of IrTargetConfig previous to the required field validation
type preIrTargetConfig struct {
	Output   *string `json:"output,omitempty"`
	Clean    *bool   `json:"clean,omitempty"`
	Schema   *string `json:"schema,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Minify   *bool   `json:"minify,omitempty"`
}

// validate validates the required fields of IrTargetConfig
func (p *preIrTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preIrTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "filename"

	// Validation for field "minify"

	return nil
}

// transform transforms the preIrTargetConfig type to the final IrTargetConfig type
func (p *preIrTargetConfig) transform() IrTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transFilename := p.Filename
	transMinify := p.Minify

	// Assignments
	return IrTargetConfig{
		Output:   transOutput,
		Clean:    transClean,
		Schema:   transSchema,
		Filename: transFilename,
		Minify:   transMinify,
	}
}

// Configuration for JSON Schema generation
type JsonSchemaTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// The $id of the generated schema
	Id *string `json:"id,omitempty"`
	// The name of the output file
	Filename *string `json:"filename,omitempty"`
	// The name of a type from '$defs' to use as the main entry point (adds a $ref at the root).
	// Must exist; VDL validates this and provides fuzzy suggestions for typos.
	Root *string `json:"root,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetId returns the value of Id or the zero value if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	var zero string
	return zero
}

// GetIdOr returns the value of Id or the provided default if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetIdOr(defaultValue string) string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return defaultValue
}

// GetFilename returns the value of Filename or the zero value if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	var zero string
	return zero
}

// GetFilenameOr returns the value of Filename or the provided default if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetFilenameOr(defaultValue string) string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return defaultValue
}

// GetRoot returns the value of Root or the zero value if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetRoot() string {
	if x != nil && x.Root != nil {
		return *x.Root
	}
	var zero string
	return zero
}

// GetRootOr returns the value of Root or the provided default if the receiver or field is nil.
func (x *JsonSchemaTargetConfig) GetRootOr(defaultValue string) string {
	if x != nil && x.Root != nil {
		return *x.Root
	}
	return defaultValue
}

// preJsonSchemaTargetConfig is the version of JsonSchemaTargetConfig previous to the required field validation
type preJsonSchemaTargetConfig struct {
	Output   *string `json:"output,omitempty"`
	Clean    *bool   `json:"clean,omitempty"`
	Schema   *string `json:"schema,omitempty"`
	Id       *string `json:"id,omitempty"`
	Filename *string `json:"filename,omitempty"`
	Root     *string `json:"root,omitempty"`
}

// validate validates the required fields of JsonSchemaTargetConfig
func (p *preJsonSchemaTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preJsonSchemaTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "id"

	// Validation for field "filename"

	// Validation for field "root"

	return nil
}

// transform transforms the preJsonSchemaTargetConfig type to the final JsonSchemaTargetConfig type
func (p *preJsonSchemaTargetConfig) transform() JsonSchemaTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transId := p.Id
	transFilename := p.Filename
	transRoot := p.Root

	// Assignments
	return JsonSchemaTargetConfig{
		Output:   transOutput,
		Clean:    transClean,
		Schema:   transSchema,
		Id:       transId,
		Filename: transFilename,
		Root:     transRoot,
	}
}

// Configuration for OpenAPI specification generation
type OpenApiTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// The name of the output file (can be .yml, .yaml or .json)
	Filename *string `json:"filename,omitempty"`
	// API title
	Title string `json:"title"`
	// API version
	Version string `json:"version"`
	// API description
	Description *string `json:"description,omitempty"`
	// Base URL for API endpoints
	BaseUrl *string `json:"baseUrl,omitempty"`
	// Contact name
	ContactName *string `json:"contactName,omitempty"`
	// Contact email
	ContactEmail *string `json:"contactEmail,omitempty"`
	// License name
	LicenseName *string `json:"licenseName,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetFilename returns the value of Filename or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	var zero string
	return zero
}

// GetFilenameOr returns the value of Filename or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetFilenameOr(defaultValue string) string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return defaultValue
}

// GetTitle returns the value of Title or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	var zero string
	return zero
}

// GetTitleOr returns the value of Title or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetTitleOr(defaultValue string) string {
	if x != nil {
		return x.Title
	}
	return defaultValue
}

// GetVersion returns the value of Version or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	var zero string
	return zero
}

// GetVersionOr returns the value of Version or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetVersionOr(defaultValue string) string {
	if x != nil {
		return x.Version
	}
	return defaultValue
}

// GetDescription returns the value of Description or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetDescriptionOr returns the value of Description or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetDescriptionOr(defaultValue string) string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return defaultValue
}

// GetBaseUrl returns the value of BaseUrl or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	var zero string
	return zero
}

// GetBaseUrlOr returns the value of BaseUrl or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetBaseUrlOr(defaultValue string) string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return defaultValue
}

// GetContactName returns the value of ContactName or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetContactName() string {
	if x != nil && x.ContactName != nil {
		return *x.ContactName
	}
	var zero string
	return zero
}

// GetContactNameOr returns the value of ContactName or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetContactNameOr(defaultValue string) string {
	if x != nil && x.ContactName != nil {
		return *x.ContactName
	}
	return defaultValue
}

// GetContactEmail returns the value of ContactEmail or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetContactEmail() string {
	if x != nil && x.ContactEmail != nil {
		return *x.ContactEmail
	}
	var zero string
	return zero
}

// GetContactEmailOr returns the value of ContactEmail or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetContactEmailOr(defaultValue string) string {
	if x != nil && x.ContactEmail != nil {
		return *x.ContactEmail
	}
	return defaultValue
}

// GetLicenseName returns the value of LicenseName or the zero value if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetLicenseName() string {
	if x != nil && x.LicenseName != nil {
		return *x.LicenseName
	}
	var zero string
	return zero
}

// GetLicenseNameOr returns the value of LicenseName or the provided default if the receiver or field is nil.
func (x *OpenApiTargetConfig) GetLicenseNameOr(defaultValue string) string {
	if x != nil && x.LicenseName != nil {
		return *x.LicenseName
	}
	return defaultValue
}

// preOpenApiTargetConfig is the version of OpenApiTargetConfig previous to the required field validation
type preOpenApiTargetConfig struct {
	Output       *string `json:"output,omitempty"`
	Clean        *bool   `json:"clean,omitempty"`
	Schema       *string `json:"schema,omitempty"`
	Filename     *string `json:"filename,omitempty"`
	Title        *string `json:"title,omitempty"`
	Version      *string `json:"version,omitempty"`
	Description  *string `json:"description,omitempty"`
	BaseUrl      *string `json:"baseUrl,omitempty"`
	ContactName  *string `json:"contactName,omitempty"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	LicenseName  *string `json:"licenseName,omitempty"`
}

// validate validates the required fields of OpenApiTargetConfig
func (p *preOpenApiTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preOpenApiTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "filename"

	// Validation for field "title"
	if p.Title == nil {
		return errorMissingRequiredField("field title is required")
	}

	// Validation for field "version"
	if p.Version == nil {
		return errorMissingRequiredField("field version is required")
	}

	// Validation for field "description"

	// Validation for field "baseUrl"

	// Validation for field "contactName"

	// Validation for field "contactEmail"

	// Validation for field "licenseName"

	return nil
}

// transform transforms the preOpenApiTargetConfig type to the final OpenApiTargetConfig type
func (p *preOpenApiTargetConfig) transform() OpenApiTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transFilename := p.Filename
	transTitle := *p.Title
	transVersion := *p.Version
	transDescription := p.Description
	transBaseUrl := p.BaseUrl
	transContactName := p.ContactName
	transContactEmail := p.ContactEmail
	transLicenseName := p.LicenseName

	// Assignments
	return OpenApiTargetConfig{
		Output:       transOutput,
		Clean:        transClean,
		Schema:       transSchema,
		Filename:     transFilename,
		Title:        transTitle,
		Version:      transVersion,
		Description:  transDescription,
		BaseUrl:      transBaseUrl,
		ContactName:  transContactName,
		ContactEmail: transContactEmail,
		LicenseName:  transLicenseName,
	}
}

// Configuration for generating patterns
type PatternsTargetConfig struct {
	// Generate helper functions for patterns
	GenPatterns *bool `json:"genPatterns,omitempty"`
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *PatternsTargetConfig) GetGenPatterns() bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *PatternsTargetConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	return defaultValue
}

// prePatternsTargetConfig is the version of PatternsTargetConfig previous to the required field validation
type prePatternsTargetConfig struct {
	GenPatterns *bool `json:"genPatterns,omitempty"`
}

// validate validates the required fields of PatternsTargetConfig
func (p *prePatternsTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("prePatternsTargetConfig is nil")
	}

	// Validation for field "genPatterns"

	return nil
}

// transform transforms the prePatternsTargetConfig type to the final PatternsTargetConfig type
func (p *prePatternsTargetConfig) transform() PatternsTargetConfig {
	// Transformations
	transGenPatterns := p.GenPatterns

	// Assignments
	return PatternsTargetConfig{
		GenPatterns: transGenPatterns,
	}
}

// Configuration for API playground generation
type PlaygroundTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// Default base URL for API requests
	DefaultBaseUrl *string `json:"defaultBaseUrl,omitempty"`
	// Default headers to include in API requests
	DefaultHeaders *map[string]string `json:"defaultHeaders,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetDefaultBaseUrl returns the value of DefaultBaseUrl or the zero value if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetDefaultBaseUrl() string {
	if x != nil && x.DefaultBaseUrl != nil {
		return *x.DefaultBaseUrl
	}
	var zero string
	return zero
}

// GetDefaultBaseUrlOr returns the value of DefaultBaseUrl or the provided default if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetDefaultBaseUrlOr(defaultValue string) string {
	if x != nil && x.DefaultBaseUrl != nil {
		return *x.DefaultBaseUrl
	}
	return defaultValue
}

// GetDefaultHeaders returns the value of DefaultHeaders or the zero value if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetDefaultHeaders() map[string]string {
	if x != nil && x.DefaultHeaders != nil {
		return *x.DefaultHeaders
	}
	var zero map[string]string
	return zero
}

// GetDefaultHeadersOr returns the value of DefaultHeaders or the provided default if the receiver or field is nil.
func (x *PlaygroundTargetConfig) GetDefaultHeadersOr(defaultValue map[string]string) map[string]string {
	if x != nil && x.DefaultHeaders != nil {
		return *x.DefaultHeaders
	}
	return defaultValue
}

// prePlaygroundTargetConfig is the version of PlaygroundTargetConfig previous to the required field validation
type prePlaygroundTargetConfig struct {
	Output         *string            `json:"output,omitempty"`
	Clean          *bool              `json:"clean,omitempty"`
	Schema         *string            `json:"schema,omitempty"`
	DefaultBaseUrl *string            `json:"defaultBaseUrl,omitempty"`
	DefaultHeaders *map[string]string `json:"defaultHeaders,omitempty"`
}

// validate validates the required fields of PlaygroundTargetConfig
func (p *prePlaygroundTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("prePlaygroundTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "defaultBaseUrl"

	// Validation for field "defaultHeaders"

	return nil
}

// transform transforms the prePlaygroundTargetConfig type to the final PlaygroundTargetConfig type
func (p *prePlaygroundTargetConfig) transform() PlaygroundTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transDefaultBaseUrl := p.DefaultBaseUrl
	transDefaultHeaders := p.DefaultHeaders

	// Assignments
	return PlaygroundTargetConfig{
		Output:         transOutput,
		Clean:          transClean,
		Schema:         transSchema,
		DefaultBaseUrl: transDefaultBaseUrl,
		DefaultHeaders: transDefaultHeaders,
	}
}

// Configuration for external plugin generators
type PluginTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// Command to execute the plugin (executable + args)
	Command []string `json:"command"`
	// Arbitrary options passed to the plugin (flat key-value pairs)
	Options *map[string]string `json:"options,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *PluginTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *PluginTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *PluginTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *PluginTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *PluginTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *PluginTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetCommand returns the value of Command or the zero value if the receiver or field is nil.
func (x *PluginTargetConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	var zero []string
	return zero
}

// GetCommandOr returns the value of Command or the provided default if the receiver or field is nil.
func (x *PluginTargetConfig) GetCommandOr(defaultValue []string) []string {
	if x != nil {
		return x.Command
	}
	return defaultValue
}

// GetOptions returns the value of Options or the zero value if the receiver or field is nil.
func (x *PluginTargetConfig) GetOptions() map[string]string {
	if x != nil && x.Options != nil {
		return *x.Options
	}
	var zero map[string]string
	return zero
}

// GetOptionsOr returns the value of Options or the provided default if the receiver or field is nil.
func (x *PluginTargetConfig) GetOptionsOr(defaultValue map[string]string) map[string]string {
	if x != nil && x.Options != nil {
		return *x.Options
	}
	return defaultValue
}

// prePluginTargetConfig is the version of PluginTargetConfig previous to the required field validation
type prePluginTargetConfig struct {
	Output  *string            `json:"output,omitempty"`
	Clean   *bool              `json:"clean,omitempty"`
	Schema  *string            `json:"schema,omitempty"`
	Command *[]string          `json:"command,omitempty"`
	Options *map[string]string `json:"options,omitempty"`
}

// validate validates the required fields of PluginTargetConfig
func (p *prePluginTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("prePluginTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "command"
	if p.Command == nil {
		return errorMissingRequiredField("field command is required")
	}

	// Validation for field "options"

	return nil
}

// transform transforms the prePluginTargetConfig type to the final PluginTargetConfig type
func (p *prePluginTargetConfig) transform() PluginTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transCommand := *p.Command
	transOptions := p.Options

	// Assignments
	return PluginTargetConfig{
		Output:  transOutput,
		Clean:   transClean,
		Schema:  transSchema,
		Command: transCommand,
		Options: transOptions,
	}
}

// Configuration for Python code generation
type PythonTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// Generate helper functions for patterns
	GenPatterns *bool `json:"genPatterns,omitempty"`
	// Generate constant definitions
	GenConsts *bool `json:"genConsts,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *PythonTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *PythonTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *PythonTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *PythonTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *PythonTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *PythonTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *PythonTargetConfig) GetGenPatterns() bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *PythonTargetConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *PythonTargetConfig) GetGenConsts() bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *PythonTargetConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	return defaultValue
}

// prePythonTargetConfig is the version of PythonTargetConfig previous to the required field validation
type prePythonTargetConfig struct {
	Output      *string `json:"output,omitempty"`
	Clean       *bool   `json:"clean,omitempty"`
	Schema      *string `json:"schema,omitempty"`
	GenPatterns *bool   `json:"genPatterns,omitempty"`
	GenConsts   *bool   `json:"genConsts,omitempty"`
}

// validate validates the required fields of PythonTargetConfig
func (p *prePythonTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("prePythonTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "genPatterns"

	// Validation for field "genConsts"

	return nil
}

// transform transforms the prePythonTargetConfig type to the final PythonTargetConfig type
func (p *prePythonTargetConfig) transform() PythonTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transGenPatterns := p.GenPatterns
	transGenConsts := p.GenConsts

	// Assignments
	return PythonTargetConfig{
		Output:      transOutput,
		Clean:       transClean,
		Schema:      transSchema,
		GenPatterns: transGenPatterns,
		GenConsts:   transGenConsts,
	}
}

// Configuration for generating RPC servers
type ServerTargetConfig struct {
	// Generate RPC server interfaces and handlers
	GenServer *bool `json:"genServer,omitempty"`
}

// GetGenServer returns the value of GenServer or the zero value if the receiver or field is nil.
func (x *ServerTargetConfig) GetGenServer() bool {
	if x != nil && x.GenServer != nil {
		return *x.GenServer
	}
	var zero bool
	return zero
}

// GetGenServerOr returns the value of GenServer or the provided default if the receiver or field is nil.
func (x *ServerTargetConfig) GetGenServerOr(defaultValue bool) bool {
	if x != nil && x.GenServer != nil {
		return *x.GenServer
	}
	return defaultValue
}

// preServerTargetConfig is the version of ServerTargetConfig previous to the required field validation
type preServerTargetConfig struct {
	GenServer *bool `json:"genServer,omitempty"`
}

// validate validates the required fields of ServerTargetConfig
func (p *preServerTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preServerTargetConfig is nil")
	}

	// Validation for field "genServer"

	return nil
}

// transform transforms the preServerTargetConfig type to the final ServerTargetConfig type
func (p *preServerTargetConfig) transform() ServerTargetConfig {
	// Transformations
	transGenServer := p.GenServer

	// Assignments
	return ServerTargetConfig{
		GenServer: transGenServer,
	}
}

// Configuration for a specific generation target, only one target type should be set per entry
type TargetConfig struct {
	// Go language target
	Go *GoTargetConfig `json:"go,omitempty"`
	// TypeScript language target
	Typescript *TypeScriptTargetConfig `json:"typescript,omitempty"`
	// Dart language target
	Dart *DartTargetConfig `json:"dart,omitempty"`
	// Python language target
	Python *PythonTargetConfig `json:"python,omitempty"`
	// JSON Schema output target
	Jsonschema *JsonSchemaTargetConfig `json:"jsonschema,omitempty"`
	// OpenAPI specification output target
	Openapi *OpenApiTargetConfig `json:"openapi,omitempty"`
	// API Playground output target
	Playground *PlaygroundTargetConfig `json:"playground,omitempty"`
	// External plugin target
	Plugin *PluginTargetConfig `json:"plugin,omitempty"`
	// IR (Intermediate Representation) JSON output target
	Ir *IrTargetConfig `json:"ir,omitempty"`
	// Unified VDL schema output target (merges includes and external docs)
	Vdl *VdlTargetConfig `json:"vdl,omitempty"`
}

// GetGo returns the value of Go or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetGo() GoTargetConfig {
	if x != nil && x.Go != nil {
		return *x.Go
	}
	var zero GoTargetConfig
	return zero
}

// GetGoOr returns the value of Go or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetGoOr(defaultValue GoTargetConfig) GoTargetConfig {
	if x != nil && x.Go != nil {
		return *x.Go
	}
	return defaultValue
}

// GetTypescript returns the value of Typescript or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetTypescript() TypeScriptTargetConfig {
	if x != nil && x.Typescript != nil {
		return *x.Typescript
	}
	var zero TypeScriptTargetConfig
	return zero
}

// GetTypescriptOr returns the value of Typescript or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetTypescriptOr(defaultValue TypeScriptTargetConfig) TypeScriptTargetConfig {
	if x != nil && x.Typescript != nil {
		return *x.Typescript
	}
	return defaultValue
}

// GetDart returns the value of Dart or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetDart() DartTargetConfig {
	if x != nil && x.Dart != nil {
		return *x.Dart
	}
	var zero DartTargetConfig
	return zero
}

// GetDartOr returns the value of Dart or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetDartOr(defaultValue DartTargetConfig) DartTargetConfig {
	if x != nil && x.Dart != nil {
		return *x.Dart
	}
	return defaultValue
}

// GetPython returns the value of Python or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetPython() PythonTargetConfig {
	if x != nil && x.Python != nil {
		return *x.Python
	}
	var zero PythonTargetConfig
	return zero
}

// GetPythonOr returns the value of Python or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetPythonOr(defaultValue PythonTargetConfig) PythonTargetConfig {
	if x != nil && x.Python != nil {
		return *x.Python
	}
	return defaultValue
}

// GetJsonschema returns the value of Jsonschema or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetJsonschema() JsonSchemaTargetConfig {
	if x != nil && x.Jsonschema != nil {
		return *x.Jsonschema
	}
	var zero JsonSchemaTargetConfig
	return zero
}

// GetJsonschemaOr returns the value of Jsonschema or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetJsonschemaOr(defaultValue JsonSchemaTargetConfig) JsonSchemaTargetConfig {
	if x != nil && x.Jsonschema != nil {
		return *x.Jsonschema
	}
	return defaultValue
}

// GetOpenapi returns the value of Openapi or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetOpenapi() OpenApiTargetConfig {
	if x != nil && x.Openapi != nil {
		return *x.Openapi
	}
	var zero OpenApiTargetConfig
	return zero
}

// GetOpenapiOr returns the value of Openapi or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetOpenapiOr(defaultValue OpenApiTargetConfig) OpenApiTargetConfig {
	if x != nil && x.Openapi != nil {
		return *x.Openapi
	}
	return defaultValue
}

// GetPlayground returns the value of Playground or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetPlayground() PlaygroundTargetConfig {
	if x != nil && x.Playground != nil {
		return *x.Playground
	}
	var zero PlaygroundTargetConfig
	return zero
}

// GetPlaygroundOr returns the value of Playground or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetPlaygroundOr(defaultValue PlaygroundTargetConfig) PlaygroundTargetConfig {
	if x != nil && x.Playground != nil {
		return *x.Playground
	}
	return defaultValue
}

// GetPlugin returns the value of Plugin or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetPlugin() PluginTargetConfig {
	if x != nil && x.Plugin != nil {
		return *x.Plugin
	}
	var zero PluginTargetConfig
	return zero
}

// GetPluginOr returns the value of Plugin or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetPluginOr(defaultValue PluginTargetConfig) PluginTargetConfig {
	if x != nil && x.Plugin != nil {
		return *x.Plugin
	}
	return defaultValue
}

// GetIr returns the value of Ir or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetIr() IrTargetConfig {
	if x != nil && x.Ir != nil {
		return *x.Ir
	}
	var zero IrTargetConfig
	return zero
}

// GetIrOr returns the value of Ir or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetIrOr(defaultValue IrTargetConfig) IrTargetConfig {
	if x != nil && x.Ir != nil {
		return *x.Ir
	}
	return defaultValue
}

// GetVdl returns the value of Vdl or the zero value if the receiver or field is nil.
func (x *TargetConfig) GetVdl() VdlTargetConfig {
	if x != nil && x.Vdl != nil {
		return *x.Vdl
	}
	var zero VdlTargetConfig
	return zero
}

// GetVdlOr returns the value of Vdl or the provided default if the receiver or field is nil.
func (x *TargetConfig) GetVdlOr(defaultValue VdlTargetConfig) VdlTargetConfig {
	if x != nil && x.Vdl != nil {
		return *x.Vdl
	}
	return defaultValue
}

// preTargetConfig is the version of TargetConfig previous to the required field validation
type preTargetConfig struct {
	Go         *preGoTargetConfig         `json:"go,omitempty"`
	Typescript *preTypeScriptTargetConfig `json:"typescript,omitempty"`
	Dart       *preDartTargetConfig       `json:"dart,omitempty"`
	Python     *prePythonTargetConfig     `json:"python,omitempty"`
	Jsonschema *preJsonSchemaTargetConfig `json:"jsonschema,omitempty"`
	Openapi    *preOpenApiTargetConfig    `json:"openapi,omitempty"`
	Playground *prePlaygroundTargetConfig `json:"playground,omitempty"`
	Plugin     *prePluginTargetConfig     `json:"plugin,omitempty"`
	Ir         *preIrTargetConfig         `json:"ir,omitempty"`
	Vdl        *preVdlTargetConfig        `json:"vdl,omitempty"`
}

// validate validates the required fields of TargetConfig
func (p *preTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preTargetConfig is nil")
	}

	// Validation for field "go"
	if p.Go != nil {
		if err := p.Go.validate(); err != nil {
			return errorMissingRequiredField("field go: " + err.Error())
		}
	}

	// Validation for field "typescript"
	if p.Typescript != nil {
		if err := p.Typescript.validate(); err != nil {
			return errorMissingRequiredField("field typescript: " + err.Error())
		}
	}

	// Validation for field "dart"
	if p.Dart != nil {
		if err := p.Dart.validate(); err != nil {
			return errorMissingRequiredField("field dart: " + err.Error())
		}
	}

	// Validation for field "python"
	if p.Python != nil {
		if err := p.Python.validate(); err != nil {
			return errorMissingRequiredField("field python: " + err.Error())
		}
	}

	// Validation for field "jsonschema"
	if p.Jsonschema != nil {
		if err := p.Jsonschema.validate(); err != nil {
			return errorMissingRequiredField("field jsonschema: " + err.Error())
		}
	}

	// Validation for field "openapi"
	if p.Openapi != nil {
		if err := p.Openapi.validate(); err != nil {
			return errorMissingRequiredField("field openapi: " + err.Error())
		}
	}

	// Validation for field "playground"
	if p.Playground != nil {
		if err := p.Playground.validate(); err != nil {
			return errorMissingRequiredField("field playground: " + err.Error())
		}
	}

	// Validation for field "plugin"
	if p.Plugin != nil {
		if err := p.Plugin.validate(); err != nil {
			return errorMissingRequiredField("field plugin: " + err.Error())
		}
	}

	// Validation for field "ir"
	if p.Ir != nil {
		if err := p.Ir.validate(); err != nil {
			return errorMissingRequiredField("field ir: " + err.Error())
		}
	}

	// Validation for field "vdl"
	if p.Vdl != nil {
		if err := p.Vdl.validate(); err != nil {
			return errorMissingRequiredField("field vdl: " + err.Error())
		}
	}

	return nil
}

// transform transforms the preTargetConfig type to the final TargetConfig type
func (p *preTargetConfig) transform() TargetConfig {
	// Transformations
	var transGo *GoTargetConfig
	if p.Go != nil {
		var valGo GoTargetConfig
		valGo = p.Go.transform()
		transGo = &valGo
	}
	var transTypescript *TypeScriptTargetConfig
	if p.Typescript != nil {
		var valTypescript TypeScriptTargetConfig
		valTypescript = p.Typescript.transform()
		transTypescript = &valTypescript
	}
	var transDart *DartTargetConfig
	if p.Dart != nil {
		var valDart DartTargetConfig
		valDart = p.Dart.transform()
		transDart = &valDart
	}
	var transPython *PythonTargetConfig
	if p.Python != nil {
		var valPython PythonTargetConfig
		valPython = p.Python.transform()
		transPython = &valPython
	}
	var transJsonschema *JsonSchemaTargetConfig
	if p.Jsonschema != nil {
		var valJsonschema JsonSchemaTargetConfig
		valJsonschema = p.Jsonschema.transform()
		transJsonschema = &valJsonschema
	}
	var transOpenapi *OpenApiTargetConfig
	if p.Openapi != nil {
		var valOpenapi OpenApiTargetConfig
		valOpenapi = p.Openapi.transform()
		transOpenapi = &valOpenapi
	}
	var transPlayground *PlaygroundTargetConfig
	if p.Playground != nil {
		var valPlayground PlaygroundTargetConfig
		valPlayground = p.Playground.transform()
		transPlayground = &valPlayground
	}
	var transPlugin *PluginTargetConfig
	if p.Plugin != nil {
		var valPlugin PluginTargetConfig
		valPlugin = p.Plugin.transform()
		transPlugin = &valPlugin
	}
	var transIr *IrTargetConfig
	if p.Ir != nil {
		var valIr IrTargetConfig
		valIr = p.Ir.transform()
		transIr = &valIr
	}
	var transVdl *VdlTargetConfig
	if p.Vdl != nil {
		var valVdl VdlTargetConfig
		valVdl = p.Vdl.transform()
		transVdl = &valVdl
	}

	// Assignments
	return TargetConfig{
		Go:         transGo,
		Typescript: transTypescript,
		Dart:       transDart,
		Python:     transPython,
		Jsonschema: transJsonschema,
		Openapi:    transOpenapi,
		Playground: transPlayground,
		Plugin:     transPlugin,
		Ir:         transIr,
		Vdl:        transVdl,
	}
}

// Configuration for TypeScript code generation
type TypeScriptTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// Generate helper functions for patterns
	GenPatterns *bool `json:"genPatterns,omitempty"`
	// Generate constant definitions
	GenConsts *bool `json:"genConsts,omitempty"`
	// Generate RPC client code
	GenClient *bool `json:"genClient,omitempty"`
	// Generate RPC server interfaces and handlers
	GenServer *bool `json:"genServer,omitempty"`
	// File extension to append to import paths
	ImportExtension *TypescriptTargetImportExtension `json:"importExtension,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenPatterns() bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil && x.GenPatterns != nil {
		return *x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenConsts() bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil && x.GenConsts != nil {
		return *x.GenConsts
	}
	return defaultValue
}

// GetGenClient returns the value of GenClient or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenClient() bool {
	if x != nil && x.GenClient != nil {
		return *x.GenClient
	}
	var zero bool
	return zero
}

// GetGenClientOr returns the value of GenClient or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenClientOr(defaultValue bool) bool {
	if x != nil && x.GenClient != nil {
		return *x.GenClient
	}
	return defaultValue
}

// GetGenServer returns the value of GenServer or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenServer() bool {
	if x != nil && x.GenServer != nil {
		return *x.GenServer
	}
	var zero bool
	return zero
}

// GetGenServerOr returns the value of GenServer or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetGenServerOr(defaultValue bool) bool {
	if x != nil && x.GenServer != nil {
		return *x.GenServer
	}
	return defaultValue
}

// GetImportExtension returns the value of ImportExtension or the zero value if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetImportExtension() TypescriptTargetImportExtension {
	if x != nil && x.ImportExtension != nil {
		return *x.ImportExtension
	}
	var zero TypescriptTargetImportExtension
	return zero
}

// GetImportExtensionOr returns the value of ImportExtension or the provided default if the receiver or field is nil.
func (x *TypeScriptTargetConfig) GetImportExtensionOr(defaultValue TypescriptTargetImportExtension) TypescriptTargetImportExtension {
	if x != nil && x.ImportExtension != nil {
		return *x.ImportExtension
	}
	return defaultValue
}

// preTypeScriptTargetConfig is the version of TypeScriptTargetConfig previous to the required field validation
type preTypeScriptTargetConfig struct {
	Output          *string                          `json:"output,omitempty"`
	Clean           *bool                            `json:"clean,omitempty"`
	Schema          *string                          `json:"schema,omitempty"`
	GenPatterns     *bool                            `json:"genPatterns,omitempty"`
	GenConsts       *bool                            `json:"genConsts,omitempty"`
	GenClient       *bool                            `json:"genClient,omitempty"`
	GenServer       *bool                            `json:"genServer,omitempty"`
	ImportExtension *TypescriptTargetImportExtension `json:"importExtension,omitempty"`
}

// validate validates the required fields of TypeScriptTargetConfig
func (p *preTypeScriptTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preTypeScriptTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "genPatterns"

	// Validation for field "genConsts"

	// Validation for field "genClient"

	// Validation for field "genServer"

	// Validation for field "importExtension"

	return nil
}

// transform transforms the preTypeScriptTargetConfig type to the final TypeScriptTargetConfig type
func (p *preTypeScriptTargetConfig) transform() TypeScriptTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transGenPatterns := p.GenPatterns
	transGenConsts := p.GenConsts
	transGenClient := p.GenClient
	transGenServer := p.GenServer
	transImportExtension := p.ImportExtension

	// Assignments
	return TypeScriptTargetConfig{
		Output:          transOutput,
		Clean:           transClean,
		Schema:          transSchema,
		GenPatterns:     transGenPatterns,
		GenConsts:       transGenConsts,
		GenClient:       transGenClient,
		GenServer:       transGenServer,
		ImportExtension: transImportExtension,
	}
}

// VDL Configuration Schema
//
// This schema defines the configuration format for the VDL code generator (vdl.yaml)
//
// It supports multiple target languages and output formats
type VdlCodegenConfig struct {
	// Configuration version (must be 1)
	Version int64 `json:"version"`
	// Path to the default global VDL schema file entrypoint
	Schema *string `json:"schema,omitempty"`
	// List of generation targets
	Targets []TargetConfig `json:"targets"`
}

// GetVersion returns the value of Version or the zero value if the receiver or field is nil.
func (x *VdlCodegenConfig) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	var zero int64
	return zero
}

// GetVersionOr returns the value of Version or the provided default if the receiver or field is nil.
func (x *VdlCodegenConfig) GetVersionOr(defaultValue int64) int64 {
	if x != nil {
		return x.Version
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *VdlCodegenConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *VdlCodegenConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetTargets returns the value of Targets or the zero value if the receiver or field is nil.
func (x *VdlCodegenConfig) GetTargets() []TargetConfig {
	if x != nil {
		return x.Targets
	}
	var zero []TargetConfig
	return zero
}

// GetTargetsOr returns the value of Targets or the provided default if the receiver or field is nil.
func (x *VdlCodegenConfig) GetTargetsOr(defaultValue []TargetConfig) []TargetConfig {
	if x != nil {
		return x.Targets
	}
	return defaultValue
}

// preVdlCodegenConfig is the version of VdlCodegenConfig previous to the required field validation
type preVdlCodegenConfig struct {
	Version *int64             `json:"version,omitempty"`
	Schema  *string            `json:"schema,omitempty"`
	Targets *[]preTargetConfig `json:"targets,omitempty"`
}

// validate validates the required fields of VdlCodegenConfig
func (p *preVdlCodegenConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preVdlCodegenConfig is nil")
	}

	// Validation for field "version"
	if p.Version == nil {
		return errorMissingRequiredField("field version is required")
	}

	// Validation for field "schema"

	// Validation for field "targets"
	if p.Targets == nil {
		return errorMissingRequiredField("field targets is required")
	}
	if p.Targets != nil {
		for _, item := range *p.Targets {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field targets: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preVdlCodegenConfig type to the final VdlCodegenConfig type
func (p *preVdlCodegenConfig) transform() VdlCodegenConfig {
	// Transformations
	transVersion := *p.Version
	transSchema := p.Schema
	var transTargets []TargetConfig
	transTargets = make([]TargetConfig, len(*p.Targets))
	for i, v := range *p.Targets {
		var tmp_ TargetConfig
		tmp_ = v.transform()
		transTargets[i] = tmp_
	}

	// Assignments
	return VdlCodegenConfig{
		Version: transVersion,
		Schema:  transSchema,
		Targets: transTargets,
	}
}

// Configuration for unified VDL schema generation (merges all includes and external docs)
type VdlTargetConfig struct {
	// The output directory where generated files will be placed
	Output string `json:"output"`
	// If true, empties the output directory before generation
	Clean *bool `json:"clean,omitempty"`
	// Override the VDL schema file entrypoint for this target
	Schema *string `json:"schema,omitempty"`
	// The name of the output file
	Filename *string `json:"filename,omitempty"`
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *VdlTargetConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	var zero string
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *VdlTargetConfig) GetOutputOr(defaultValue string) string {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// GetClean returns the value of Clean or the zero value if the receiver or field is nil.
func (x *VdlTargetConfig) GetClean() bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	var zero bool
	return zero
}

// GetCleanOr returns the value of Clean or the provided default if the receiver or field is nil.
func (x *VdlTargetConfig) GetCleanOr(defaultValue bool) bool {
	if x != nil && x.Clean != nil {
		return *x.Clean
	}
	return defaultValue
}

// GetSchema returns the value of Schema or the zero value if the receiver or field is nil.
func (x *VdlTargetConfig) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the value of Schema or the provided default if the receiver or field is nil.
func (x *VdlTargetConfig) GetSchemaOr(defaultValue string) string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return defaultValue
}

// GetFilename returns the value of Filename or the zero value if the receiver or field is nil.
func (x *VdlTargetConfig) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	var zero string
	return zero
}

// GetFilenameOr returns the value of Filename or the provided default if the receiver or field is nil.
func (x *VdlTargetConfig) GetFilenameOr(defaultValue string) string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return defaultValue
}

// preVdlTargetConfig is the version of VdlTargetConfig previous to the required field validation
type preVdlTargetConfig struct {
	Output   *string `json:"output,omitempty"`
	Clean    *bool   `json:"clean,omitempty"`
	Schema   *string `json:"schema,omitempty"`
	Filename *string `json:"filename,omitempty"`
}

// validate validates the required fields of VdlTargetConfig
func (p *preVdlTargetConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preVdlTargetConfig is nil")
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}

	// Validation for field "clean"

	// Validation for field "schema"

	// Validation for field "filename"

	return nil
}

// transform transforms the preVdlTargetConfig type to the final VdlTargetConfig type
func (p *preVdlTargetConfig) transform() VdlTargetConfig {
	// Transformations
	transOutput := *p.Output
	transClean := p.Clean
	transSchema := p.Schema
	transFilename := p.Filename

	// Assignments
	return VdlTargetConfig{
		Output:   transOutput,
		Clean:    transClean,
		Schema:   transSchema,
		Filename: transFilename,
	}
}
