// Code generated by VDL v0.0.0-dev. DO NOT EDIT.
// If you edit this file, it will be overwritten the next time it is generated.

// Package wasmtypes contains generated code for VDL.
//
// For more information about VDL, visit https://vdl.varavel.com
package wasmtypes

import (
	"encoding/json"
	"fmt"
)

// -----------------------------------------------------------------------------
// Enumerations
// -----------------------------------------------------------------------------

// Represents a target for codegen function
type CodegenTarget string

// CodegenTarget enum values
const (
	CodegenTargetGo         CodegenTarget = "Go"
	CodegenTargetTypescript CodegenTarget = "Typescript"
	CodegenTargetDart       CodegenTarget = "Dart"
	CodegenTargetPython     CodegenTarget = "Python"
	CodegenTargetOpenApi    CodegenTarget = "OpenApi"
	CodegenTargetJsonSchema CodegenTarget = "JsonSchema"
)

// CodegenTargetList contains all valid CodegenTarget values.
var CodegenTargetList = []CodegenTarget{
	CodegenTargetGo,
	CodegenTargetTypescript,
	CodegenTargetDart,
	CodegenTargetPython,
	CodegenTargetOpenApi,
	CodegenTargetJsonSchema,
}

// String returns the string representation of CodegenTarget.
func (e CodegenTarget) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid CodegenTarget.
func (e CodegenTarget) IsValid() bool {
	switch e {
	case CodegenTargetGo, CodegenTargetTypescript, CodegenTargetDart, CodegenTargetPython, CodegenTargetOpenApi, CodegenTargetJsonSchema:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid CodegenTarget member.
func (e CodegenTarget) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum CodegenTarget", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid CodegenTarget member.
func (e *CodegenTarget) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := CodegenTarget(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum CodegenTarget", s)
	}

	*e = v
	return nil
}

// Import extension for typescript code generator
type CodegenTypescriptImportExtension string

// CodegenTypescriptImportExtension enum values
const (
	CodegenTypescriptImportExtensionNone CodegenTypescriptImportExtension = "none"
	CodegenTypescriptImportExtensionJs   CodegenTypescriptImportExtension = ".js"
	CodegenTypescriptImportExtensionTs   CodegenTypescriptImportExtension = ".ts"
)

// CodegenTypescriptImportExtensionList contains all valid CodegenTypescriptImportExtension values.
var CodegenTypescriptImportExtensionList = []CodegenTypescriptImportExtension{
	CodegenTypescriptImportExtensionNone,
	CodegenTypescriptImportExtensionJs,
	CodegenTypescriptImportExtensionTs,
}

// String returns the string representation of CodegenTypescriptImportExtension.
func (e CodegenTypescriptImportExtension) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid CodegenTypescriptImportExtension.
func (e CodegenTypescriptImportExtension) IsValid() bool {
	switch e {
	case CodegenTypescriptImportExtensionNone, CodegenTypescriptImportExtensionJs, CodegenTypescriptImportExtensionTs:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid CodegenTypescriptImportExtension member.
func (e CodegenTypescriptImportExtension) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum CodegenTypescriptImportExtension", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid CodegenTypescriptImportExtension member.
func (e *CodegenTypescriptImportExtension) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := CodegenTypescriptImportExtension(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum CodegenTypescriptImportExtension", s)
	}

	*e = v
	return nil
}

// Represents a function to be called via WASM
type WasmFunctionName string

// WasmFunctionName enum values
const (
	WasmFunctionNameExpandTypes   WasmFunctionName = "ExpandTypes"
	WasmFunctionNameExtractType   WasmFunctionName = "ExtractType"
	WasmFunctionNameExtractProc   WasmFunctionName = "ExtractProc"
	WasmFunctionNameExtractStream WasmFunctionName = "ExtractStream"
	WasmFunctionNameCodegen       WasmFunctionName = "Codegen"
)

// WasmFunctionNameList contains all valid WasmFunctionName values.
var WasmFunctionNameList = []WasmFunctionName{
	WasmFunctionNameExpandTypes,
	WasmFunctionNameExtractType,
	WasmFunctionNameExtractProc,
	WasmFunctionNameExtractStream,
	WasmFunctionNameCodegen,
}

// String returns the string representation of WasmFunctionName.
func (e WasmFunctionName) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid WasmFunctionName.
func (e WasmFunctionName) IsValid() bool {
	switch e {
	case WasmFunctionNameExpandTypes, WasmFunctionNameExtractType, WasmFunctionNameExtractProc, WasmFunctionNameExtractStream, WasmFunctionNameCodegen:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid WasmFunctionName member.
func (e WasmFunctionName) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum WasmFunctionName", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid WasmFunctionName member.
func (e *WasmFunctionName) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := WasmFunctionName(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum WasmFunctionName", s)
	}

	*e = v
	return nil
}

// -----------------------------------------------------------------------------
// Domain Types
// -----------------------------------------------------------------------------

// Rrepresents a file generated by codegen function
type CodegenFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// GetPath returns the value of Path or the zero value if the receiver or field is nil.
func (x *CodegenFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	var zero string
	return zero
}

// GetPathOr returns the value of Path or the provided default if the receiver or field is nil.
func (x *CodegenFile) GetPathOr(defaultValue string) string {
	if x != nil {
		return x.Path
	}
	return defaultValue
}

// GetContent returns the value of Content or the zero value if the receiver or field is nil.
func (x *CodegenFile) GetContent() string {
	if x != nil {
		return x.Content
	}
	var zero string
	return zero
}

// GetContentOr returns the value of Content or the provided default if the receiver or field is nil.
func (x *CodegenFile) GetContentOr(defaultValue string) string {
	if x != nil {
		return x.Content
	}
	return defaultValue
}

// preCodegenFile is the version of CodegenFile previous to the required field validation
type preCodegenFile struct {
	Path    *string `json:"path,omitempty"`
	Content *string `json:"content,omitempty"`
}

// validate validates the required fields of CodegenFile
func (p *preCodegenFile) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenFile is nil")
	}

	// Validation for field "path"
	if p.Path == nil {
		return errorMissingRequiredField("field path is required")
	}

	// Validation for field "content"
	if p.Content == nil {
		return errorMissingRequiredField("field content is required")
	}

	return nil
}

// transform transforms the preCodegenFile type to the final CodegenFile type
func (p *preCodegenFile) transform() CodegenFile {
	// Transformations
	transPath := *p.Path
	transContent := *p.Content

	// Assignments
	return CodegenFile{
		Path:    transPath,
		Content: transContent,
	}
}

// Input for codegen function
type CodegenInput struct {
	// Schema to generate code from
	VdlSchema string `json:"vdlSchema"`
	// Target to generate code for
	Target CodegenTarget `json:"target"`
	// Configuration if the target is Go
	GoConfig *CodegenInputGoConfig `json:"goConfig,omitempty"`
	// Configuration if the target is Typescript
	TypescriptConfig *CodegenInputTypescriptConfig `json:"typescriptConfig,omitempty"`
	// Configuration if the target is Dart
	DartConfig *CodegenInputDartConfig `json:"dartConfig,omitempty"`
	// Configuration if the target is Python
	PythonConfig *CodegenInputPythonConfig `json:"pythonConfig,omitempty"`
	// Configuration if the target is JsonSchema
	JsonSchemaConfig *CodegenInputJsonSchemaConfig `json:"jsonSchemaConfig,omitempty"`
	// Configuration if the target is OpenApi
	OpenApiConfig *CodegenInputOpenApiConfig `json:"openApiConfig,omitempty"`
}

// GetVdlSchema returns the value of VdlSchema or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetVdlSchema() string {
	if x != nil {
		return x.VdlSchema
	}
	var zero string
	return zero
}

// GetVdlSchemaOr returns the value of VdlSchema or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetVdlSchemaOr(defaultValue string) string {
	if x != nil {
		return x.VdlSchema
	}
	return defaultValue
}

// GetTarget returns the value of Target or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetTarget() CodegenTarget {
	if x != nil {
		return x.Target
	}
	var zero CodegenTarget
	return zero
}

// GetTargetOr returns the value of Target or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetTargetOr(defaultValue CodegenTarget) CodegenTarget {
	if x != nil {
		return x.Target
	}
	return defaultValue
}

// GetGoConfig returns the value of GoConfig or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetGoConfig() CodegenInputGoConfig {
	if x != nil && x.GoConfig != nil {
		return *x.GoConfig
	}
	var zero CodegenInputGoConfig
	return zero
}

// GetGoConfigOr returns the value of GoConfig or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetGoConfigOr(defaultValue CodegenInputGoConfig) CodegenInputGoConfig {
	if x != nil && x.GoConfig != nil {
		return *x.GoConfig
	}
	return defaultValue
}

// GetTypescriptConfig returns the value of TypescriptConfig or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetTypescriptConfig() CodegenInputTypescriptConfig {
	if x != nil && x.TypescriptConfig != nil {
		return *x.TypescriptConfig
	}
	var zero CodegenInputTypescriptConfig
	return zero
}

// GetTypescriptConfigOr returns the value of TypescriptConfig or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetTypescriptConfigOr(defaultValue CodegenInputTypescriptConfig) CodegenInputTypescriptConfig {
	if x != nil && x.TypescriptConfig != nil {
		return *x.TypescriptConfig
	}
	return defaultValue
}

// GetDartConfig returns the value of DartConfig or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetDartConfig() CodegenInputDartConfig {
	if x != nil && x.DartConfig != nil {
		return *x.DartConfig
	}
	var zero CodegenInputDartConfig
	return zero
}

// GetDartConfigOr returns the value of DartConfig or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetDartConfigOr(defaultValue CodegenInputDartConfig) CodegenInputDartConfig {
	if x != nil && x.DartConfig != nil {
		return *x.DartConfig
	}
	return defaultValue
}

// GetPythonConfig returns the value of PythonConfig or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetPythonConfig() CodegenInputPythonConfig {
	if x != nil && x.PythonConfig != nil {
		return *x.PythonConfig
	}
	var zero CodegenInputPythonConfig
	return zero
}

// GetPythonConfigOr returns the value of PythonConfig or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetPythonConfigOr(defaultValue CodegenInputPythonConfig) CodegenInputPythonConfig {
	if x != nil && x.PythonConfig != nil {
		return *x.PythonConfig
	}
	return defaultValue
}

// GetJsonSchemaConfig returns the value of JsonSchemaConfig or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetJsonSchemaConfig() CodegenInputJsonSchemaConfig {
	if x != nil && x.JsonSchemaConfig != nil {
		return *x.JsonSchemaConfig
	}
	var zero CodegenInputJsonSchemaConfig
	return zero
}

// GetJsonSchemaConfigOr returns the value of JsonSchemaConfig or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetJsonSchemaConfigOr(defaultValue CodegenInputJsonSchemaConfig) CodegenInputJsonSchemaConfig {
	if x != nil && x.JsonSchemaConfig != nil {
		return *x.JsonSchemaConfig
	}
	return defaultValue
}

// GetOpenApiConfig returns the value of OpenApiConfig or the zero value if the receiver or field is nil.
func (x *CodegenInput) GetOpenApiConfig() CodegenInputOpenApiConfig {
	if x != nil && x.OpenApiConfig != nil {
		return *x.OpenApiConfig
	}
	var zero CodegenInputOpenApiConfig
	return zero
}

// GetOpenApiConfigOr returns the value of OpenApiConfig or the provided default if the receiver or field is nil.
func (x *CodegenInput) GetOpenApiConfigOr(defaultValue CodegenInputOpenApiConfig) CodegenInputOpenApiConfig {
	if x != nil && x.OpenApiConfig != nil {
		return *x.OpenApiConfig
	}
	return defaultValue
}

type CodegenInputGoConfig struct {
	Package     string `json:"package"`
	GenPatterns bool   `json:"genPatterns"`
	GenConsts   bool   `json:"genConsts"`
	GenClient   bool   `json:"genClient"`
	GenServer   bool   `json:"genServer"`
}

// GetPackage returns the value of Package or the zero value if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetPackage() string {
	if x != nil {
		return x.Package
	}
	var zero string
	return zero
}

// GetPackageOr returns the value of Package or the provided default if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetPackageOr(defaultValue string) string {
	if x != nil {
		return x.Package
	}
	return defaultValue
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenPatterns() bool {
	if x != nil {
		return x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenConsts() bool {
	if x != nil {
		return x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenConsts
	}
	return defaultValue
}

// GetGenClient returns the value of GenClient or the zero value if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenClient() bool {
	if x != nil {
		return x.GenClient
	}
	var zero bool
	return zero
}

// GetGenClientOr returns the value of GenClient or the provided default if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenClientOr(defaultValue bool) bool {
	if x != nil {
		return x.GenClient
	}
	return defaultValue
}

// GetGenServer returns the value of GenServer or the zero value if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenServer() bool {
	if x != nil {
		return x.GenServer
	}
	var zero bool
	return zero
}

// GetGenServerOr returns the value of GenServer or the provided default if the receiver or field is nil.
func (x *CodegenInputGoConfig) GetGenServerOr(defaultValue bool) bool {
	if x != nil {
		return x.GenServer
	}
	return defaultValue
}

type CodegenInputTypescriptConfig struct {
	ImportExtension CodegenTypescriptImportExtension `json:"importExtension"`
	GenPatterns     bool                             `json:"genPatterns"`
	GenConsts       bool                             `json:"genConsts"`
	GenClient       bool                             `json:"genClient"`
	GenServer       bool                             `json:"genServer"`
}

// GetImportExtension returns the value of ImportExtension or the zero value if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetImportExtension() CodegenTypescriptImportExtension {
	if x != nil {
		return x.ImportExtension
	}
	var zero CodegenTypescriptImportExtension
	return zero
}

// GetImportExtensionOr returns the value of ImportExtension or the provided default if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetImportExtensionOr(defaultValue CodegenTypescriptImportExtension) CodegenTypescriptImportExtension {
	if x != nil {
		return x.ImportExtension
	}
	return defaultValue
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenPatterns() bool {
	if x != nil {
		return x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenConsts() bool {
	if x != nil {
		return x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenConsts
	}
	return defaultValue
}

// GetGenClient returns the value of GenClient or the zero value if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenClient() bool {
	if x != nil {
		return x.GenClient
	}
	var zero bool
	return zero
}

// GetGenClientOr returns the value of GenClient or the provided default if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenClientOr(defaultValue bool) bool {
	if x != nil {
		return x.GenClient
	}
	return defaultValue
}

// GetGenServer returns the value of GenServer or the zero value if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenServer() bool {
	if x != nil {
		return x.GenServer
	}
	var zero bool
	return zero
}

// GetGenServerOr returns the value of GenServer or the provided default if the receiver or field is nil.
func (x *CodegenInputTypescriptConfig) GetGenServerOr(defaultValue bool) bool {
	if x != nil {
		return x.GenServer
	}
	return defaultValue
}

type CodegenInputDartConfig struct {
	GenPatterns bool `json:"genPatterns"`
	GenConsts   bool `json:"genConsts"`
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *CodegenInputDartConfig) GetGenPatterns() bool {
	if x != nil {
		return x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *CodegenInputDartConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *CodegenInputDartConfig) GetGenConsts() bool {
	if x != nil {
		return x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *CodegenInputDartConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenConsts
	}
	return defaultValue
}

type CodegenInputPythonConfig struct {
	GenPatterns bool `json:"genPatterns"`
	GenConsts   bool `json:"genConsts"`
}

// GetGenPatterns returns the value of GenPatterns or the zero value if the receiver or field is nil.
func (x *CodegenInputPythonConfig) GetGenPatterns() bool {
	if x != nil {
		return x.GenPatterns
	}
	var zero bool
	return zero
}

// GetGenPatternsOr returns the value of GenPatterns or the provided default if the receiver or field is nil.
func (x *CodegenInputPythonConfig) GetGenPatternsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenPatterns
	}
	return defaultValue
}

// GetGenConsts returns the value of GenConsts or the zero value if the receiver or field is nil.
func (x *CodegenInputPythonConfig) GetGenConsts() bool {
	if x != nil {
		return x.GenConsts
	}
	var zero bool
	return zero
}

// GetGenConstsOr returns the value of GenConsts or the provided default if the receiver or field is nil.
func (x *CodegenInputPythonConfig) GetGenConstsOr(defaultValue bool) bool {
	if x != nil {
		return x.GenConsts
	}
	return defaultValue
}

type CodegenInputJsonSchemaConfig struct {
	SchemaId string `json:"schemaId"`
}

// GetSchemaId returns the value of SchemaId or the zero value if the receiver or field is nil.
func (x *CodegenInputJsonSchemaConfig) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	var zero string
	return zero
}

// GetSchemaIdOr returns the value of SchemaId or the provided default if the receiver or field is nil.
func (x *CodegenInputJsonSchemaConfig) GetSchemaIdOr(defaultValue string) string {
	if x != nil {
		return x.SchemaId
	}
	return defaultValue
}

type CodegenInputOpenApiConfig struct {
	Title        string  `json:"title"`
	Version      string  `json:"version"`
	Description  *string `json:"description,omitempty"`
	BaseUrl      *string `json:"baseUrl,omitempty"`
	ContactName  *string `json:"contactName,omitempty"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	LicenseName  *string `json:"licenseName,omitempty"`
}

// GetTitle returns the value of Title or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetTitle() string {
	if x != nil {
		return x.Title
	}
	var zero string
	return zero
}

// GetTitleOr returns the value of Title or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetTitleOr(defaultValue string) string {
	if x != nil {
		return x.Title
	}
	return defaultValue
}

// GetVersion returns the value of Version or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	var zero string
	return zero
}

// GetVersionOr returns the value of Version or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetVersionOr(defaultValue string) string {
	if x != nil {
		return x.Version
	}
	return defaultValue
}

// GetDescription returns the value of Description or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	var zero string
	return zero
}

// GetDescriptionOr returns the value of Description or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetDescriptionOr(defaultValue string) string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return defaultValue
}

// GetBaseUrl returns the value of BaseUrl or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	var zero string
	return zero
}

// GetBaseUrlOr returns the value of BaseUrl or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetBaseUrlOr(defaultValue string) string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return defaultValue
}

// GetContactName returns the value of ContactName or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetContactName() string {
	if x != nil && x.ContactName != nil {
		return *x.ContactName
	}
	var zero string
	return zero
}

// GetContactNameOr returns the value of ContactName or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetContactNameOr(defaultValue string) string {
	if x != nil && x.ContactName != nil {
		return *x.ContactName
	}
	return defaultValue
}

// GetContactEmail returns the value of ContactEmail or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetContactEmail() string {
	if x != nil && x.ContactEmail != nil {
		return *x.ContactEmail
	}
	var zero string
	return zero
}

// GetContactEmailOr returns the value of ContactEmail or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetContactEmailOr(defaultValue string) string {
	if x != nil && x.ContactEmail != nil {
		return *x.ContactEmail
	}
	return defaultValue
}

// GetLicenseName returns the value of LicenseName or the zero value if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetLicenseName() string {
	if x != nil && x.LicenseName != nil {
		return *x.LicenseName
	}
	var zero string
	return zero
}

// GetLicenseNameOr returns the value of LicenseName or the provided default if the receiver or field is nil.
func (x *CodegenInputOpenApiConfig) GetLicenseNameOr(defaultValue string) string {
	if x != nil && x.LicenseName != nil {
		return *x.LicenseName
	}
	return defaultValue
}

// preCodegenInput is the version of CodegenInput previous to the required field validation
type preCodegenInput struct {
	VdlSchema        *string                          `json:"vdlSchema,omitempty"`
	Target           *CodegenTarget                   `json:"target,omitempty"`
	GoConfig         *preCodegenInputGoConfig         `json:"goConfig,omitempty"`
	TypescriptConfig *preCodegenInputTypescriptConfig `json:"typescriptConfig,omitempty"`
	DartConfig       *preCodegenInputDartConfig       `json:"dartConfig,omitempty"`
	PythonConfig     *preCodegenInputPythonConfig     `json:"pythonConfig,omitempty"`
	JsonSchemaConfig *preCodegenInputJsonSchemaConfig `json:"jsonSchemaConfig,omitempty"`
	OpenApiConfig    *preCodegenInputOpenApiConfig    `json:"openApiConfig,omitempty"`
}

// preCodegenInputGoConfig is the version of CodegenInputGoConfig previous to the required field validation
type preCodegenInputGoConfig struct {
	Package     *string `json:"package,omitempty"`
	GenPatterns *bool   `json:"genPatterns,omitempty"`
	GenConsts   *bool   `json:"genConsts,omitempty"`
	GenClient   *bool   `json:"genClient,omitempty"`
	GenServer   *bool   `json:"genServer,omitempty"`
}

// validate validates the required fields of CodegenInputGoConfig
func (p *preCodegenInputGoConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInputGoConfig is nil")
	}

	// Validation for field "package"
	if p.Package == nil {
		return errorMissingRequiredField("field package is required")
	}

	// Validation for field "genPatterns"
	if p.GenPatterns == nil {
		return errorMissingRequiredField("field genPatterns is required")
	}

	// Validation for field "genConsts"
	if p.GenConsts == nil {
		return errorMissingRequiredField("field genConsts is required")
	}

	// Validation for field "genClient"
	if p.GenClient == nil {
		return errorMissingRequiredField("field genClient is required")
	}

	// Validation for field "genServer"
	if p.GenServer == nil {
		return errorMissingRequiredField("field genServer is required")
	}

	return nil
}

// transform transforms the preCodegenInputGoConfig type to the final CodegenInputGoConfig type
func (p *preCodegenInputGoConfig) transform() CodegenInputGoConfig {
	// Transformations
	transPackage := *p.Package
	transGenPatterns := *p.GenPatterns
	transGenConsts := *p.GenConsts
	transGenClient := *p.GenClient
	transGenServer := *p.GenServer

	// Assignments
	return CodegenInputGoConfig{
		Package:     transPackage,
		GenPatterns: transGenPatterns,
		GenConsts:   transGenConsts,
		GenClient:   transGenClient,
		GenServer:   transGenServer,
	}
}

// preCodegenInputTypescriptConfig is the version of CodegenInputTypescriptConfig previous to the required field validation
type preCodegenInputTypescriptConfig struct {
	ImportExtension *CodegenTypescriptImportExtension `json:"importExtension,omitempty"`
	GenPatterns     *bool                             `json:"genPatterns,omitempty"`
	GenConsts       *bool                             `json:"genConsts,omitempty"`
	GenClient       *bool                             `json:"genClient,omitempty"`
	GenServer       *bool                             `json:"genServer,omitempty"`
}

// validate validates the required fields of CodegenInputTypescriptConfig
func (p *preCodegenInputTypescriptConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInputTypescriptConfig is nil")
	}

	// Validation for field "importExtension"
	if p.ImportExtension == nil {
		return errorMissingRequiredField("field importExtension is required")
	}

	// Validation for field "genPatterns"
	if p.GenPatterns == nil {
		return errorMissingRequiredField("field genPatterns is required")
	}

	// Validation for field "genConsts"
	if p.GenConsts == nil {
		return errorMissingRequiredField("field genConsts is required")
	}

	// Validation for field "genClient"
	if p.GenClient == nil {
		return errorMissingRequiredField("field genClient is required")
	}

	// Validation for field "genServer"
	if p.GenServer == nil {
		return errorMissingRequiredField("field genServer is required")
	}

	return nil
}

// transform transforms the preCodegenInputTypescriptConfig type to the final CodegenInputTypescriptConfig type
func (p *preCodegenInputTypescriptConfig) transform() CodegenInputTypescriptConfig {
	// Transformations
	transImportExtension := *p.ImportExtension
	transGenPatterns := *p.GenPatterns
	transGenConsts := *p.GenConsts
	transGenClient := *p.GenClient
	transGenServer := *p.GenServer

	// Assignments
	return CodegenInputTypescriptConfig{
		ImportExtension: transImportExtension,
		GenPatterns:     transGenPatterns,
		GenConsts:       transGenConsts,
		GenClient:       transGenClient,
		GenServer:       transGenServer,
	}
}

// preCodegenInputDartConfig is the version of CodegenInputDartConfig previous to the required field validation
type preCodegenInputDartConfig struct {
	GenPatterns *bool `json:"genPatterns,omitempty"`
	GenConsts   *bool `json:"genConsts,omitempty"`
}

// validate validates the required fields of CodegenInputDartConfig
func (p *preCodegenInputDartConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInputDartConfig is nil")
	}

	// Validation for field "genPatterns"
	if p.GenPatterns == nil {
		return errorMissingRequiredField("field genPatterns is required")
	}

	// Validation for field "genConsts"
	if p.GenConsts == nil {
		return errorMissingRequiredField("field genConsts is required")
	}

	return nil
}

// transform transforms the preCodegenInputDartConfig type to the final CodegenInputDartConfig type
func (p *preCodegenInputDartConfig) transform() CodegenInputDartConfig {
	// Transformations
	transGenPatterns := *p.GenPatterns
	transGenConsts := *p.GenConsts

	// Assignments
	return CodegenInputDartConfig{
		GenPatterns: transGenPatterns,
		GenConsts:   transGenConsts,
	}
}

// preCodegenInputPythonConfig is the version of CodegenInputPythonConfig previous to the required field validation
type preCodegenInputPythonConfig struct {
	GenPatterns *bool `json:"genPatterns,omitempty"`
	GenConsts   *bool `json:"genConsts,omitempty"`
}

// validate validates the required fields of CodegenInputPythonConfig
func (p *preCodegenInputPythonConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInputPythonConfig is nil")
	}

	// Validation for field "genPatterns"
	if p.GenPatterns == nil {
		return errorMissingRequiredField("field genPatterns is required")
	}

	// Validation for field "genConsts"
	if p.GenConsts == nil {
		return errorMissingRequiredField("field genConsts is required")
	}

	return nil
}

// transform transforms the preCodegenInputPythonConfig type to the final CodegenInputPythonConfig type
func (p *preCodegenInputPythonConfig) transform() CodegenInputPythonConfig {
	// Transformations
	transGenPatterns := *p.GenPatterns
	transGenConsts := *p.GenConsts

	// Assignments
	return CodegenInputPythonConfig{
		GenPatterns: transGenPatterns,
		GenConsts:   transGenConsts,
	}
}

// preCodegenInputJsonSchemaConfig is the version of CodegenInputJsonSchemaConfig previous to the required field validation
type preCodegenInputJsonSchemaConfig struct {
	SchemaId *string `json:"schemaId,omitempty"`
}

// validate validates the required fields of CodegenInputJsonSchemaConfig
func (p *preCodegenInputJsonSchemaConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInputJsonSchemaConfig is nil")
	}

	// Validation for field "schemaId"
	if p.SchemaId == nil {
		return errorMissingRequiredField("field schemaId is required")
	}

	return nil
}

// transform transforms the preCodegenInputJsonSchemaConfig type to the final CodegenInputJsonSchemaConfig type
func (p *preCodegenInputJsonSchemaConfig) transform() CodegenInputJsonSchemaConfig {
	// Transformations
	transSchemaId := *p.SchemaId

	// Assignments
	return CodegenInputJsonSchemaConfig{
		SchemaId: transSchemaId,
	}
}

// preCodegenInputOpenApiConfig is the version of CodegenInputOpenApiConfig previous to the required field validation
type preCodegenInputOpenApiConfig struct {
	Title        *string `json:"title,omitempty"`
	Version      *string `json:"version,omitempty"`
	Description  *string `json:"description,omitempty"`
	BaseUrl      *string `json:"baseUrl,omitempty"`
	ContactName  *string `json:"contactName,omitempty"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	LicenseName  *string `json:"licenseName,omitempty"`
}

// validate validates the required fields of CodegenInputOpenApiConfig
func (p *preCodegenInputOpenApiConfig) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInputOpenApiConfig is nil")
	}

	// Validation for field "title"
	if p.Title == nil {
		return errorMissingRequiredField("field title is required")
	}

	// Validation for field "version"
	if p.Version == nil {
		return errorMissingRequiredField("field version is required")
	}

	// Validation for field "description"

	// Validation for field "baseUrl"

	// Validation for field "contactName"

	// Validation for field "contactEmail"

	// Validation for field "licenseName"

	return nil
}

// transform transforms the preCodegenInputOpenApiConfig type to the final CodegenInputOpenApiConfig type
func (p *preCodegenInputOpenApiConfig) transform() CodegenInputOpenApiConfig {
	// Transformations
	transTitle := *p.Title
	transVersion := *p.Version
	transDescription := p.Description
	transBaseUrl := p.BaseUrl
	transContactName := p.ContactName
	transContactEmail := p.ContactEmail
	transLicenseName := p.LicenseName

	// Assignments
	return CodegenInputOpenApiConfig{
		Title:        transTitle,
		Version:      transVersion,
		Description:  transDescription,
		BaseUrl:      transBaseUrl,
		ContactName:  transContactName,
		ContactEmail: transContactEmail,
		LicenseName:  transLicenseName,
	}
}

// validate validates the required fields of CodegenInput
func (p *preCodegenInput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenInput is nil")
	}

	// Validation for field "vdlSchema"
	if p.VdlSchema == nil {
		return errorMissingRequiredField("field vdlSchema is required")
	}

	// Validation for field "target"
	if p.Target == nil {
		return errorMissingRequiredField("field target is required")
	}

	// Validation for field "goConfig"
	if p.GoConfig != nil {
		if err := p.GoConfig.validate(); err != nil {
			return errorMissingRequiredField("field goConfig: " + err.Error())
		}
	}

	// Validation for field "typescriptConfig"
	if p.TypescriptConfig != nil {
		if err := p.TypescriptConfig.validate(); err != nil {
			return errorMissingRequiredField("field typescriptConfig: " + err.Error())
		}
	}

	// Validation for field "dartConfig"
	if p.DartConfig != nil {
		if err := p.DartConfig.validate(); err != nil {
			return errorMissingRequiredField("field dartConfig: " + err.Error())
		}
	}

	// Validation for field "pythonConfig"
	if p.PythonConfig != nil {
		if err := p.PythonConfig.validate(); err != nil {
			return errorMissingRequiredField("field pythonConfig: " + err.Error())
		}
	}

	// Validation for field "jsonSchemaConfig"
	if p.JsonSchemaConfig != nil {
		if err := p.JsonSchemaConfig.validate(); err != nil {
			return errorMissingRequiredField("field jsonSchemaConfig: " + err.Error())
		}
	}

	// Validation for field "openApiConfig"
	if p.OpenApiConfig != nil {
		if err := p.OpenApiConfig.validate(); err != nil {
			return errorMissingRequiredField("field openApiConfig: " + err.Error())
		}
	}

	return nil
}

// transform transforms the preCodegenInput type to the final CodegenInput type
func (p *preCodegenInput) transform() CodegenInput {
	// Transformations
	transVdlSchema := *p.VdlSchema
	transTarget := *p.Target
	var transGoConfig *CodegenInputGoConfig
	if p.GoConfig != nil {
		var valGoConfig CodegenInputGoConfig
		valGoConfig = p.GoConfig.transform()
		transGoConfig = &valGoConfig
	}
	var transTypescriptConfig *CodegenInputTypescriptConfig
	if p.TypescriptConfig != nil {
		var valTypescriptConfig CodegenInputTypescriptConfig
		valTypescriptConfig = p.TypescriptConfig.transform()
		transTypescriptConfig = &valTypescriptConfig
	}
	var transDartConfig *CodegenInputDartConfig
	if p.DartConfig != nil {
		var valDartConfig CodegenInputDartConfig
		valDartConfig = p.DartConfig.transform()
		transDartConfig = &valDartConfig
	}
	var transPythonConfig *CodegenInputPythonConfig
	if p.PythonConfig != nil {
		var valPythonConfig CodegenInputPythonConfig
		valPythonConfig = p.PythonConfig.transform()
		transPythonConfig = &valPythonConfig
	}
	var transJsonSchemaConfig *CodegenInputJsonSchemaConfig
	if p.JsonSchemaConfig != nil {
		var valJsonSchemaConfig CodegenInputJsonSchemaConfig
		valJsonSchemaConfig = p.JsonSchemaConfig.transform()
		transJsonSchemaConfig = &valJsonSchemaConfig
	}
	var transOpenApiConfig *CodegenInputOpenApiConfig
	if p.OpenApiConfig != nil {
		var valOpenApiConfig CodegenInputOpenApiConfig
		valOpenApiConfig = p.OpenApiConfig.transform()
		transOpenApiConfig = &valOpenApiConfig
	}

	// Assignments
	return CodegenInput{
		VdlSchema:        transVdlSchema,
		Target:           transTarget,
		GoConfig:         transGoConfig,
		TypescriptConfig: transTypescriptConfig,
		DartConfig:       transDartConfig,
		PythonConfig:     transPythonConfig,
		JsonSchemaConfig: transJsonSchemaConfig,
		OpenApiConfig:    transOpenApiConfig,
	}
}

// Output for codegen function
type CodegenOutput struct {
	// The files generated for the picked code generator target
	Files []CodegenFile `json:"files"`
}

// GetFiles returns the value of Files or the zero value if the receiver or field is nil.
func (x *CodegenOutput) GetFiles() []CodegenFile {
	if x != nil {
		return x.Files
	}
	var zero []CodegenFile
	return zero
}

// GetFilesOr returns the value of Files or the provided default if the receiver or field is nil.
func (x *CodegenOutput) GetFilesOr(defaultValue []CodegenFile) []CodegenFile {
	if x != nil {
		return x.Files
	}
	return defaultValue
}

// preCodegenOutput is the version of CodegenOutput previous to the required field validation
type preCodegenOutput struct {
	Files *[]preCodegenFile `json:"files,omitempty"`
}

// validate validates the required fields of CodegenOutput
func (p *preCodegenOutput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preCodegenOutput is nil")
	}

	// Validation for field "files"
	if p.Files == nil {
		return errorMissingRequiredField("field files is required")
	}
	if p.Files != nil {
		for _, item := range *p.Files {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field files: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preCodegenOutput type to the final CodegenOutput type
func (p *preCodegenOutput) transform() CodegenOutput {
	// Transformations
	var transFiles []CodegenFile
	transFiles = make([]CodegenFile, len(*p.Files))
	for i, v := range *p.Files {
		var tmp_ CodegenFile
		tmp_ = v.transform()
		transFiles[i] = tmp_
	}

	// Assignments
	return CodegenOutput{
		Files: transFiles,
	}
}

// Input for expandTypes function
type ExpandTypesInput struct {
	VdlSchema string `json:"vdlSchema"`
}

// GetVdlSchema returns the value of VdlSchema or the zero value if the receiver or field is nil.
func (x *ExpandTypesInput) GetVdlSchema() string {
	if x != nil {
		return x.VdlSchema
	}
	var zero string
	return zero
}

// GetVdlSchemaOr returns the value of VdlSchema or the provided default if the receiver or field is nil.
func (x *ExpandTypesInput) GetVdlSchemaOr(defaultValue string) string {
	if x != nil {
		return x.VdlSchema
	}
	return defaultValue
}

// preExpandTypesInput is the version of ExpandTypesInput previous to the required field validation
type preExpandTypesInput struct {
	VdlSchema *string `json:"vdlSchema,omitempty"`
}

// validate validates the required fields of ExpandTypesInput
func (p *preExpandTypesInput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExpandTypesInput is nil")
	}

	// Validation for field "vdlSchema"
	if p.VdlSchema == nil {
		return errorMissingRequiredField("field vdlSchema is required")
	}

	return nil
}

// transform transforms the preExpandTypesInput type to the final ExpandTypesInput type
func (p *preExpandTypesInput) transform() ExpandTypesInput {
	// Transformations
	transVdlSchema := *p.VdlSchema

	// Assignments
	return ExpandTypesInput{
		VdlSchema: transVdlSchema,
	}
}

// Output for expandTypes function
type ExpandTypesOutput struct {
	ExpandedSchema string `json:"expandedSchema"`
}

// GetExpandedSchema returns the value of ExpandedSchema or the zero value if the receiver or field is nil.
func (x *ExpandTypesOutput) GetExpandedSchema() string {
	if x != nil {
		return x.ExpandedSchema
	}
	var zero string
	return zero
}

// GetExpandedSchemaOr returns the value of ExpandedSchema or the provided default if the receiver or field is nil.
func (x *ExpandTypesOutput) GetExpandedSchemaOr(defaultValue string) string {
	if x != nil {
		return x.ExpandedSchema
	}
	return defaultValue
}

// preExpandTypesOutput is the version of ExpandTypesOutput previous to the required field validation
type preExpandTypesOutput struct {
	ExpandedSchema *string `json:"expandedSchema,omitempty"`
}

// validate validates the required fields of ExpandTypesOutput
func (p *preExpandTypesOutput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExpandTypesOutput is nil")
	}

	// Validation for field "expandedSchema"
	if p.ExpandedSchema == nil {
		return errorMissingRequiredField("field expandedSchema is required")
	}

	return nil
}

// transform transforms the preExpandTypesOutput type to the final ExpandTypesOutput type
func (p *preExpandTypesOutput) transform() ExpandTypesOutput {
	// Transformations
	transExpandedSchema := *p.ExpandedSchema

	// Assignments
	return ExpandTypesOutput{
		ExpandedSchema: transExpandedSchema,
	}
}

// Input for extractProc function
type ExtractProcInput struct {
	VdlSchema string `json:"vdlSchema"`
	RpcName   string `json:"rpcName"`
	ProcName  string `json:"procName"`
}

// GetVdlSchema returns the value of VdlSchema or the zero value if the receiver or field is nil.
func (x *ExtractProcInput) GetVdlSchema() string {
	if x != nil {
		return x.VdlSchema
	}
	var zero string
	return zero
}

// GetVdlSchemaOr returns the value of VdlSchema or the provided default if the receiver or field is nil.
func (x *ExtractProcInput) GetVdlSchemaOr(defaultValue string) string {
	if x != nil {
		return x.VdlSchema
	}
	return defaultValue
}

// GetRpcName returns the value of RpcName or the zero value if the receiver or field is nil.
func (x *ExtractProcInput) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	var zero string
	return zero
}

// GetRpcNameOr returns the value of RpcName or the provided default if the receiver or field is nil.
func (x *ExtractProcInput) GetRpcNameOr(defaultValue string) string {
	if x != nil {
		return x.RpcName
	}
	return defaultValue
}

// GetProcName returns the value of ProcName or the zero value if the receiver or field is nil.
func (x *ExtractProcInput) GetProcName() string {
	if x != nil {
		return x.ProcName
	}
	var zero string
	return zero
}

// GetProcNameOr returns the value of ProcName or the provided default if the receiver or field is nil.
func (x *ExtractProcInput) GetProcNameOr(defaultValue string) string {
	if x != nil {
		return x.ProcName
	}
	return defaultValue
}

// preExtractProcInput is the version of ExtractProcInput previous to the required field validation
type preExtractProcInput struct {
	VdlSchema *string `json:"vdlSchema,omitempty"`
	RpcName   *string `json:"rpcName,omitempty"`
	ProcName  *string `json:"procName,omitempty"`
}

// validate validates the required fields of ExtractProcInput
func (p *preExtractProcInput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExtractProcInput is nil")
	}

	// Validation for field "vdlSchema"
	if p.VdlSchema == nil {
		return errorMissingRequiredField("field vdlSchema is required")
	}

	// Validation for field "rpcName"
	if p.RpcName == nil {
		return errorMissingRequiredField("field rpcName is required")
	}

	// Validation for field "procName"
	if p.ProcName == nil {
		return errorMissingRequiredField("field procName is required")
	}

	return nil
}

// transform transforms the preExtractProcInput type to the final ExtractProcInput type
func (p *preExtractProcInput) transform() ExtractProcInput {
	// Transformations
	transVdlSchema := *p.VdlSchema
	transRpcName := *p.RpcName
	transProcName := *p.ProcName

	// Assignments
	return ExtractProcInput{
		VdlSchema: transVdlSchema,
		RpcName:   transRpcName,
		ProcName:  transProcName,
	}
}

// Output for extractProc function
type ExtractProcOutput struct {
	ProcSchema string `json:"procSchema"`
}

// GetProcSchema returns the value of ProcSchema or the zero value if the receiver or field is nil.
func (x *ExtractProcOutput) GetProcSchema() string {
	if x != nil {
		return x.ProcSchema
	}
	var zero string
	return zero
}

// GetProcSchemaOr returns the value of ProcSchema or the provided default if the receiver or field is nil.
func (x *ExtractProcOutput) GetProcSchemaOr(defaultValue string) string {
	if x != nil {
		return x.ProcSchema
	}
	return defaultValue
}

// preExtractProcOutput is the version of ExtractProcOutput previous to the required field validation
type preExtractProcOutput struct {
	ProcSchema *string `json:"procSchema,omitempty"`
}

// validate validates the required fields of ExtractProcOutput
func (p *preExtractProcOutput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExtractProcOutput is nil")
	}

	// Validation for field "procSchema"
	if p.ProcSchema == nil {
		return errorMissingRequiredField("field procSchema is required")
	}

	return nil
}

// transform transforms the preExtractProcOutput type to the final ExtractProcOutput type
func (p *preExtractProcOutput) transform() ExtractProcOutput {
	// Transformations
	transProcSchema := *p.ProcSchema

	// Assignments
	return ExtractProcOutput{
		ProcSchema: transProcSchema,
	}
}

// Input for extractStream function
type ExtractStreamInput struct {
	VdlSchema  string `json:"vdlSchema"`
	RpcName    string `json:"rpcName"`
	StreamName string `json:"streamName"`
}

// GetVdlSchema returns the value of VdlSchema or the zero value if the receiver or field is nil.
func (x *ExtractStreamInput) GetVdlSchema() string {
	if x != nil {
		return x.VdlSchema
	}
	var zero string
	return zero
}

// GetVdlSchemaOr returns the value of VdlSchema or the provided default if the receiver or field is nil.
func (x *ExtractStreamInput) GetVdlSchemaOr(defaultValue string) string {
	if x != nil {
		return x.VdlSchema
	}
	return defaultValue
}

// GetRpcName returns the value of RpcName or the zero value if the receiver or field is nil.
func (x *ExtractStreamInput) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	var zero string
	return zero
}

// GetRpcNameOr returns the value of RpcName or the provided default if the receiver or field is nil.
func (x *ExtractStreamInput) GetRpcNameOr(defaultValue string) string {
	if x != nil {
		return x.RpcName
	}
	return defaultValue
}

// GetStreamName returns the value of StreamName or the zero value if the receiver or field is nil.
func (x *ExtractStreamInput) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	var zero string
	return zero
}

// GetStreamNameOr returns the value of StreamName or the provided default if the receiver or field is nil.
func (x *ExtractStreamInput) GetStreamNameOr(defaultValue string) string {
	if x != nil {
		return x.StreamName
	}
	return defaultValue
}

// preExtractStreamInput is the version of ExtractStreamInput previous to the required field validation
type preExtractStreamInput struct {
	VdlSchema  *string `json:"vdlSchema,omitempty"`
	RpcName    *string `json:"rpcName,omitempty"`
	StreamName *string `json:"streamName,omitempty"`
}

// validate validates the required fields of ExtractStreamInput
func (p *preExtractStreamInput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExtractStreamInput is nil")
	}

	// Validation for field "vdlSchema"
	if p.VdlSchema == nil {
		return errorMissingRequiredField("field vdlSchema is required")
	}

	// Validation for field "rpcName"
	if p.RpcName == nil {
		return errorMissingRequiredField("field rpcName is required")
	}

	// Validation for field "streamName"
	if p.StreamName == nil {
		return errorMissingRequiredField("field streamName is required")
	}

	return nil
}

// transform transforms the preExtractStreamInput type to the final ExtractStreamInput type
func (p *preExtractStreamInput) transform() ExtractStreamInput {
	// Transformations
	transVdlSchema := *p.VdlSchema
	transRpcName := *p.RpcName
	transStreamName := *p.StreamName

	// Assignments
	return ExtractStreamInput{
		VdlSchema:  transVdlSchema,
		RpcName:    transRpcName,
		StreamName: transStreamName,
	}
}

// Output for extractStream function
type ExtractStreamOutput struct {
	StreamSchema string `json:"streamSchema"`
}

// GetStreamSchema returns the value of StreamSchema or the zero value if the receiver or field is nil.
func (x *ExtractStreamOutput) GetStreamSchema() string {
	if x != nil {
		return x.StreamSchema
	}
	var zero string
	return zero
}

// GetStreamSchemaOr returns the value of StreamSchema or the provided default if the receiver or field is nil.
func (x *ExtractStreamOutput) GetStreamSchemaOr(defaultValue string) string {
	if x != nil {
		return x.StreamSchema
	}
	return defaultValue
}

// preExtractStreamOutput is the version of ExtractStreamOutput previous to the required field validation
type preExtractStreamOutput struct {
	StreamSchema *string `json:"streamSchema,omitempty"`
}

// validate validates the required fields of ExtractStreamOutput
func (p *preExtractStreamOutput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExtractStreamOutput is nil")
	}

	// Validation for field "streamSchema"
	if p.StreamSchema == nil {
		return errorMissingRequiredField("field streamSchema is required")
	}

	return nil
}

// transform transforms the preExtractStreamOutput type to the final ExtractStreamOutput type
func (p *preExtractStreamOutput) transform() ExtractStreamOutput {
	// Transformations
	transStreamSchema := *p.StreamSchema

	// Assignments
	return ExtractStreamOutput{
		StreamSchema: transStreamSchema,
	}
}

// Input for extractType function
type ExtractTypeInput struct {
	VdlSchema string `json:"vdlSchema"`
	TypeName  string `json:"typeName"`
}

// GetVdlSchema returns the value of VdlSchema or the zero value if the receiver or field is nil.
func (x *ExtractTypeInput) GetVdlSchema() string {
	if x != nil {
		return x.VdlSchema
	}
	var zero string
	return zero
}

// GetVdlSchemaOr returns the value of VdlSchema or the provided default if the receiver or field is nil.
func (x *ExtractTypeInput) GetVdlSchemaOr(defaultValue string) string {
	if x != nil {
		return x.VdlSchema
	}
	return defaultValue
}

// GetTypeName returns the value of TypeName or the zero value if the receiver or field is nil.
func (x *ExtractTypeInput) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	var zero string
	return zero
}

// GetTypeNameOr returns the value of TypeName or the provided default if the receiver or field is nil.
func (x *ExtractTypeInput) GetTypeNameOr(defaultValue string) string {
	if x != nil {
		return x.TypeName
	}
	return defaultValue
}

// preExtractTypeInput is the version of ExtractTypeInput previous to the required field validation
type preExtractTypeInput struct {
	VdlSchema *string `json:"vdlSchema,omitempty"`
	TypeName  *string `json:"typeName,omitempty"`
}

// validate validates the required fields of ExtractTypeInput
func (p *preExtractTypeInput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExtractTypeInput is nil")
	}

	// Validation for field "vdlSchema"
	if p.VdlSchema == nil {
		return errorMissingRequiredField("field vdlSchema is required")
	}

	// Validation for field "typeName"
	if p.TypeName == nil {
		return errorMissingRequiredField("field typeName is required")
	}

	return nil
}

// transform transforms the preExtractTypeInput type to the final ExtractTypeInput type
func (p *preExtractTypeInput) transform() ExtractTypeInput {
	// Transformations
	transVdlSchema := *p.VdlSchema
	transTypeName := *p.TypeName

	// Assignments
	return ExtractTypeInput{
		VdlSchema: transVdlSchema,
		TypeName:  transTypeName,
	}
}

// Output for extractType function
type ExtractTypeOutput struct {
	TypeSchema string `json:"typeSchema"`
}

// GetTypeSchema returns the value of TypeSchema or the zero value if the receiver or field is nil.
func (x *ExtractTypeOutput) GetTypeSchema() string {
	if x != nil {
		return x.TypeSchema
	}
	var zero string
	return zero
}

// GetTypeSchemaOr returns the value of TypeSchema or the provided default if the receiver or field is nil.
func (x *ExtractTypeOutput) GetTypeSchemaOr(defaultValue string) string {
	if x != nil {
		return x.TypeSchema
	}
	return defaultValue
}

// preExtractTypeOutput is the version of ExtractTypeOutput previous to the required field validation
type preExtractTypeOutput struct {
	TypeSchema *string `json:"typeSchema,omitempty"`
}

// validate validates the required fields of ExtractTypeOutput
func (p *preExtractTypeOutput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preExtractTypeOutput is nil")
	}

	// Validation for field "typeSchema"
	if p.TypeSchema == nil {
		return errorMissingRequiredField("field typeSchema is required")
	}

	return nil
}

// transform transforms the preExtractTypeOutput type to the final ExtractTypeOutput type
func (p *preExtractTypeOutput) transform() ExtractTypeOutput {
	// Transformations
	transTypeSchema := *p.TypeSchema

	// Assignments
	return ExtractTypeOutput{
		TypeSchema: transTypeSchema,
	}
}

// The input for the WASM function call
type WasmInput struct {
	FunctionName  WasmFunctionName    `json:"functionName"`
	ExpandTypes   *ExpandTypesInput   `json:"expandTypes,omitempty"`
	ExtractType   *ExtractTypeInput   `json:"extractType,omitempty"`
	ExtractProc   *ExtractProcInput   `json:"extractProc,omitempty"`
	ExtractStream *ExtractStreamInput `json:"extractStream,omitempty"`
	Codegen       *CodegenInput       `json:"codegen,omitempty"`
}

// GetFunctionName returns the value of FunctionName or the zero value if the receiver or field is nil.
func (x *WasmInput) GetFunctionName() WasmFunctionName {
	if x != nil {
		return x.FunctionName
	}
	var zero WasmFunctionName
	return zero
}

// GetFunctionNameOr returns the value of FunctionName or the provided default if the receiver or field is nil.
func (x *WasmInput) GetFunctionNameOr(defaultValue WasmFunctionName) WasmFunctionName {
	if x != nil {
		return x.FunctionName
	}
	return defaultValue
}

// GetExpandTypes returns the value of ExpandTypes or the zero value if the receiver or field is nil.
func (x *WasmInput) GetExpandTypes() ExpandTypesInput {
	if x != nil && x.ExpandTypes != nil {
		return *x.ExpandTypes
	}
	var zero ExpandTypesInput
	return zero
}

// GetExpandTypesOr returns the value of ExpandTypes or the provided default if the receiver or field is nil.
func (x *WasmInput) GetExpandTypesOr(defaultValue ExpandTypesInput) ExpandTypesInput {
	if x != nil && x.ExpandTypes != nil {
		return *x.ExpandTypes
	}
	return defaultValue
}

// GetExtractType returns the value of ExtractType or the zero value if the receiver or field is nil.
func (x *WasmInput) GetExtractType() ExtractTypeInput {
	if x != nil && x.ExtractType != nil {
		return *x.ExtractType
	}
	var zero ExtractTypeInput
	return zero
}

// GetExtractTypeOr returns the value of ExtractType or the provided default if the receiver or field is nil.
func (x *WasmInput) GetExtractTypeOr(defaultValue ExtractTypeInput) ExtractTypeInput {
	if x != nil && x.ExtractType != nil {
		return *x.ExtractType
	}
	return defaultValue
}

// GetExtractProc returns the value of ExtractProc or the zero value if the receiver or field is nil.
func (x *WasmInput) GetExtractProc() ExtractProcInput {
	if x != nil && x.ExtractProc != nil {
		return *x.ExtractProc
	}
	var zero ExtractProcInput
	return zero
}

// GetExtractProcOr returns the value of ExtractProc or the provided default if the receiver or field is nil.
func (x *WasmInput) GetExtractProcOr(defaultValue ExtractProcInput) ExtractProcInput {
	if x != nil && x.ExtractProc != nil {
		return *x.ExtractProc
	}
	return defaultValue
}

// GetExtractStream returns the value of ExtractStream or the zero value if the receiver or field is nil.
func (x *WasmInput) GetExtractStream() ExtractStreamInput {
	if x != nil && x.ExtractStream != nil {
		return *x.ExtractStream
	}
	var zero ExtractStreamInput
	return zero
}

// GetExtractStreamOr returns the value of ExtractStream or the provided default if the receiver or field is nil.
func (x *WasmInput) GetExtractStreamOr(defaultValue ExtractStreamInput) ExtractStreamInput {
	if x != nil && x.ExtractStream != nil {
		return *x.ExtractStream
	}
	return defaultValue
}

// GetCodegen returns the value of Codegen or the zero value if the receiver or field is nil.
func (x *WasmInput) GetCodegen() CodegenInput {
	if x != nil && x.Codegen != nil {
		return *x.Codegen
	}
	var zero CodegenInput
	return zero
}

// GetCodegenOr returns the value of Codegen or the provided default if the receiver or field is nil.
func (x *WasmInput) GetCodegenOr(defaultValue CodegenInput) CodegenInput {
	if x != nil && x.Codegen != nil {
		return *x.Codegen
	}
	return defaultValue
}

// preWasmInput is the version of WasmInput previous to the required field validation
type preWasmInput struct {
	FunctionName  *WasmFunctionName      `json:"functionName,omitempty"`
	ExpandTypes   *preExpandTypesInput   `json:"expandTypes,omitempty"`
	ExtractType   *preExtractTypeInput   `json:"extractType,omitempty"`
	ExtractProc   *preExtractProcInput   `json:"extractProc,omitempty"`
	ExtractStream *preExtractStreamInput `json:"extractStream,omitempty"`
	Codegen       *preCodegenInput       `json:"codegen,omitempty"`
}

// validate validates the required fields of WasmInput
func (p *preWasmInput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preWasmInput is nil")
	}

	// Validation for field "functionName"
	if p.FunctionName == nil {
		return errorMissingRequiredField("field functionName is required")
	}

	// Validation for field "expandTypes"
	if p.ExpandTypes != nil {
		if err := p.ExpandTypes.validate(); err != nil {
			return errorMissingRequiredField("field expandTypes: " + err.Error())
		}
	}

	// Validation for field "extractType"
	if p.ExtractType != nil {
		if err := p.ExtractType.validate(); err != nil {
			return errorMissingRequiredField("field extractType: " + err.Error())
		}
	}

	// Validation for field "extractProc"
	if p.ExtractProc != nil {
		if err := p.ExtractProc.validate(); err != nil {
			return errorMissingRequiredField("field extractProc: " + err.Error())
		}
	}

	// Validation for field "extractStream"
	if p.ExtractStream != nil {
		if err := p.ExtractStream.validate(); err != nil {
			return errorMissingRequiredField("field extractStream: " + err.Error())
		}
	}

	// Validation for field "codegen"
	if p.Codegen != nil {
		if err := p.Codegen.validate(); err != nil {
			return errorMissingRequiredField("field codegen: " + err.Error())
		}
	}

	return nil
}

// transform transforms the preWasmInput type to the final WasmInput type
func (p *preWasmInput) transform() WasmInput {
	// Transformations
	transFunctionName := *p.FunctionName
	var transExpandTypes *ExpandTypesInput
	if p.ExpandTypes != nil {
		var valExpandTypes ExpandTypesInput
		valExpandTypes = p.ExpandTypes.transform()
		transExpandTypes = &valExpandTypes
	}
	var transExtractType *ExtractTypeInput
	if p.ExtractType != nil {
		var valExtractType ExtractTypeInput
		valExtractType = p.ExtractType.transform()
		transExtractType = &valExtractType
	}
	var transExtractProc *ExtractProcInput
	if p.ExtractProc != nil {
		var valExtractProc ExtractProcInput
		valExtractProc = p.ExtractProc.transform()
		transExtractProc = &valExtractProc
	}
	var transExtractStream *ExtractStreamInput
	if p.ExtractStream != nil {
		var valExtractStream ExtractStreamInput
		valExtractStream = p.ExtractStream.transform()
		transExtractStream = &valExtractStream
	}
	var transCodegen *CodegenInput
	if p.Codegen != nil {
		var valCodegen CodegenInput
		valCodegen = p.Codegen.transform()
		transCodegen = &valCodegen
	}

	// Assignments
	return WasmInput{
		FunctionName:  transFunctionName,
		ExpandTypes:   transExpandTypes,
		ExtractType:   transExtractType,
		ExtractProc:   transExtractProc,
		ExtractStream: transExtractStream,
		Codegen:       transCodegen,
	}
}

// The output for the WASM function call
type WasmOutput struct {
	ExpandTypes   *ExpandTypesOutput   `json:"expandTypes,omitempty"`
	ExtractType   *ExtractTypeOutput   `json:"extractType,omitempty"`
	ExtractProc   *ExtractProcOutput   `json:"extractProc,omitempty"`
	ExtractStream *ExtractStreamOutput `json:"extractStream,omitempty"`
	Codegen       *CodegenOutput       `json:"codegen,omitempty"`
}

// GetExpandTypes returns the value of ExpandTypes or the zero value if the receiver or field is nil.
func (x *WasmOutput) GetExpandTypes() ExpandTypesOutput {
	if x != nil && x.ExpandTypes != nil {
		return *x.ExpandTypes
	}
	var zero ExpandTypesOutput
	return zero
}

// GetExpandTypesOr returns the value of ExpandTypes or the provided default if the receiver or field is nil.
func (x *WasmOutput) GetExpandTypesOr(defaultValue ExpandTypesOutput) ExpandTypesOutput {
	if x != nil && x.ExpandTypes != nil {
		return *x.ExpandTypes
	}
	return defaultValue
}

// GetExtractType returns the value of ExtractType or the zero value if the receiver or field is nil.
func (x *WasmOutput) GetExtractType() ExtractTypeOutput {
	if x != nil && x.ExtractType != nil {
		return *x.ExtractType
	}
	var zero ExtractTypeOutput
	return zero
}

// GetExtractTypeOr returns the value of ExtractType or the provided default if the receiver or field is nil.
func (x *WasmOutput) GetExtractTypeOr(defaultValue ExtractTypeOutput) ExtractTypeOutput {
	if x != nil && x.ExtractType != nil {
		return *x.ExtractType
	}
	return defaultValue
}

// GetExtractProc returns the value of ExtractProc or the zero value if the receiver or field is nil.
func (x *WasmOutput) GetExtractProc() ExtractProcOutput {
	if x != nil && x.ExtractProc != nil {
		return *x.ExtractProc
	}
	var zero ExtractProcOutput
	return zero
}

// GetExtractProcOr returns the value of ExtractProc or the provided default if the receiver or field is nil.
func (x *WasmOutput) GetExtractProcOr(defaultValue ExtractProcOutput) ExtractProcOutput {
	if x != nil && x.ExtractProc != nil {
		return *x.ExtractProc
	}
	return defaultValue
}

// GetExtractStream returns the value of ExtractStream or the zero value if the receiver or field is nil.
func (x *WasmOutput) GetExtractStream() ExtractStreamOutput {
	if x != nil && x.ExtractStream != nil {
		return *x.ExtractStream
	}
	var zero ExtractStreamOutput
	return zero
}

// GetExtractStreamOr returns the value of ExtractStream or the provided default if the receiver or field is nil.
func (x *WasmOutput) GetExtractStreamOr(defaultValue ExtractStreamOutput) ExtractStreamOutput {
	if x != nil && x.ExtractStream != nil {
		return *x.ExtractStream
	}
	return defaultValue
}

// GetCodegen returns the value of Codegen or the zero value if the receiver or field is nil.
func (x *WasmOutput) GetCodegen() CodegenOutput {
	if x != nil && x.Codegen != nil {
		return *x.Codegen
	}
	var zero CodegenOutput
	return zero
}

// GetCodegenOr returns the value of Codegen or the provided default if the receiver or field is nil.
func (x *WasmOutput) GetCodegenOr(defaultValue CodegenOutput) CodegenOutput {
	if x != nil && x.Codegen != nil {
		return *x.Codegen
	}
	return defaultValue
}

// preWasmOutput is the version of WasmOutput previous to the required field validation
type preWasmOutput struct {
	ExpandTypes   *preExpandTypesOutput   `json:"expandTypes,omitempty"`
	ExtractType   *preExtractTypeOutput   `json:"extractType,omitempty"`
	ExtractProc   *preExtractProcOutput   `json:"extractProc,omitempty"`
	ExtractStream *preExtractStreamOutput `json:"extractStream,omitempty"`
	Codegen       *preCodegenOutput       `json:"codegen,omitempty"`
}

// validate validates the required fields of WasmOutput
func (p *preWasmOutput) validate() error {
	if p == nil {
		return errorMissingRequiredField("preWasmOutput is nil")
	}

	// Validation for field "expandTypes"
	if p.ExpandTypes != nil {
		if err := p.ExpandTypes.validate(); err != nil {
			return errorMissingRequiredField("field expandTypes: " + err.Error())
		}
	}

	// Validation for field "extractType"
	if p.ExtractType != nil {
		if err := p.ExtractType.validate(); err != nil {
			return errorMissingRequiredField("field extractType: " + err.Error())
		}
	}

	// Validation for field "extractProc"
	if p.ExtractProc != nil {
		if err := p.ExtractProc.validate(); err != nil {
			return errorMissingRequiredField("field extractProc: " + err.Error())
		}
	}

	// Validation for field "extractStream"
	if p.ExtractStream != nil {
		if err := p.ExtractStream.validate(); err != nil {
			return errorMissingRequiredField("field extractStream: " + err.Error())
		}
	}

	// Validation for field "codegen"
	if p.Codegen != nil {
		if err := p.Codegen.validate(); err != nil {
			return errorMissingRequiredField("field codegen: " + err.Error())
		}
	}

	return nil
}

// transform transforms the preWasmOutput type to the final WasmOutput type
func (p *preWasmOutput) transform() WasmOutput {
	// Transformations
	var transExpandTypes *ExpandTypesOutput
	if p.ExpandTypes != nil {
		var valExpandTypes ExpandTypesOutput
		valExpandTypes = p.ExpandTypes.transform()
		transExpandTypes = &valExpandTypes
	}
	var transExtractType *ExtractTypeOutput
	if p.ExtractType != nil {
		var valExtractType ExtractTypeOutput
		valExtractType = p.ExtractType.transform()
		transExtractType = &valExtractType
	}
	var transExtractProc *ExtractProcOutput
	if p.ExtractProc != nil {
		var valExtractProc ExtractProcOutput
		valExtractProc = p.ExtractProc.transform()
		transExtractProc = &valExtractProc
	}
	var transExtractStream *ExtractStreamOutput
	if p.ExtractStream != nil {
		var valExtractStream ExtractStreamOutput
		valExtractStream = p.ExtractStream.transform()
		transExtractStream = &valExtractStream
	}
	var transCodegen *CodegenOutput
	if p.Codegen != nil {
		var valCodegen CodegenOutput
		valCodegen = p.Codegen.transform()
		transCodegen = &valCodegen
	}

	// Assignments
	return WasmOutput{
		ExpandTypes:   transExpandTypes,
		ExtractType:   transExtractType,
		ExtractProc:   transExtractProc,
		ExtractStream: transExtractStream,
		Codegen:       transCodegen,
	}
}
