package plugin

import "github.com/varavelio/vdl/toolchain/internal/core/ir/irtypes"

// Input represents the data sent to the plugin via Stdin.
type Input struct {
	// IR is the complete VDL Intermediate Representation.
	IR *irtypes.IrSchema `json:"ir"`
	// Options is the map of arbitrary options defined in vdl.yaml.
	Options map[string]any `json:"options"`
}

// Output represents the data received from the plugin via Stdout.
type Output struct {
	// Files is the list of virtual files generated by the plugin.
	Files []File `json:"files"`
}

// File represents a single generated file.
type File struct {
	// Path is the relative path to the output directory (e.g. "src/api.py").
	Path string `json:"path"`
	// Content is the textual content of the file.
	Content string `json:"content"`
}
