// Code generated by VDL v0.0.0-dev. DO NOT EDIT.
// If you edit this file, it will be overwritten the next time it is generated.

// Package irtypes contains generated code for VDL.
//
// For more information about VDL, visit https://vdl.varavel.com
package irtypes

import (
	"encoding/json"
	"fmt"
)

// -----------------------------------------------------------------------------
// Enumerations
// -----------------------------------------------------------------------------

// The type of a constant value
type ConstType string

// ConstType enum values
const (
	ConstTypeString ConstType = "string"
	ConstTypeInt    ConstType = "int"
	ConstTypeFloat  ConstType = "float"
	ConstTypeBool   ConstType = "bool"
)

// ConstTypeList contains all valid ConstType values.
var ConstTypeList = []ConstType{
	ConstTypeString,
	ConstTypeInt,
	ConstTypeFloat,
	ConstTypeBool,
}

// String returns the string representation of ConstType.
func (e ConstType) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid ConstType.
func (e ConstType) IsValid() bool {
	switch e {
	case ConstTypeString, ConstTypeInt, ConstTypeFloat, ConstTypeBool:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid ConstType member.
func (e ConstType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum ConstType", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid ConstType member.
func (e *ConstType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := ConstType(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum ConstType", s)
	}

	*e = v
	return nil
}

// The underlying value type of an enum
type EnumType string

// EnumType enum values
const (
	EnumTypeString EnumType = "string"
	EnumTypeInt    EnumType = "int"
)

// EnumTypeList contains all valid EnumType values.
var EnumTypeList = []EnumType{
	EnumTypeString,
	EnumTypeInt,
}

// String returns the string representation of EnumType.
func (e EnumType) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid EnumType.
func (e EnumType) IsValid() bool {
	switch e {
	case EnumTypeString, EnumTypeInt:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid EnumType member.
func (e EnumType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum EnumType", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid EnumType member.
func (e *EnumType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := EnumType(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum EnumType", s)
	}

	*e = v
	return nil
}

// Field primitive types
type PrimitiveType string

// PrimitiveType enum values
const (
	PrimitiveTypeString   PrimitiveType = "string"
	PrimitiveTypeInt      PrimitiveType = "int"
	PrimitiveTypeFloat    PrimitiveType = "float"
	PrimitiveTypeBool     PrimitiveType = "bool"
	PrimitiveTypeDatetime PrimitiveType = "datetime"
)

// PrimitiveTypeList contains all valid PrimitiveType values.
var PrimitiveTypeList = []PrimitiveType{
	PrimitiveTypeString,
	PrimitiveTypeInt,
	PrimitiveTypeFloat,
	PrimitiveTypeBool,
	PrimitiveTypeDatetime,
}

// String returns the string representation of PrimitiveType.
func (e PrimitiveType) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid PrimitiveType.
func (e PrimitiveType) IsValid() bool {
	switch e {
	case PrimitiveTypeString, PrimitiveTypeInt, PrimitiveTypeFloat, PrimitiveTypeBool, PrimitiveTypeDatetime:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid PrimitiveType member.
func (e PrimitiveType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum PrimitiveType", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid PrimitiveType member.
func (e *PrimitiveType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := PrimitiveType(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum PrimitiveType", s)
	}

	*e = v
	return nil
}

// Categories for a type
type TypeKind string

// TypeKind enum values
const (
	TypeKindPrimitive TypeKind = "primitive"
	TypeKindType      TypeKind = "type"
	TypeKindEnum      TypeKind = "enum"
	TypeKindArray     TypeKind = "array"
	TypeKindMap       TypeKind = "map"
	TypeKindObject    TypeKind = "object"
)

// TypeKindList contains all valid TypeKind values.
var TypeKindList = []TypeKind{
	TypeKindPrimitive,
	TypeKindType,
	TypeKindEnum,
	TypeKindArray,
	TypeKindMap,
	TypeKindObject,
}

// String returns the string representation of TypeKind.
func (e TypeKind) String() string {
	return string(e)
}

// IsValid returns true if the value is a valid TypeKind.
func (e TypeKind) IsValid() bool {
	switch e {
	case TypeKindPrimitive, TypeKindType, TypeKindEnum, TypeKindArray, TypeKindMap, TypeKindObject:
		return true
	}
	return false
}

// MarshalJSON implements json.Marshaler.
// Returns an error if the value is not a valid TypeKind member.
func (e TypeKind) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("cannot marshal invalid value '%s' for enum TypeKind", string(e))
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON implements json.Unmarshaler.
// Returns an error if the value is not a valid TypeKind member.
func (e *TypeKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	v := TypeKind(s)
	if !v.IsValid() {
		return fmt.Errorf("invalid value '%s' for enum TypeKind", s)
	}

	*e = v
	return nil
}

// -----------------------------------------------------------------------------
// Domain Types
// -----------------------------------------------------------------------------

// Represents a constant definition
type ConstantDef struct {
	// The name of the constant
	Name string `json:"name"`
	// Documentation for the constant
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
	// The type of the constant value
	ConstType ConstType `json:"constType"`
	// The value of the constant as a string
	Value string `json:"value"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *ConstantDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *ConstantDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *ConstantDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *ConstantDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *ConstantDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *ConstantDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// GetConstType returns the value of ConstType or the zero value if the receiver or field is nil.
func (x *ConstantDef) GetConstType() ConstType {
	if x != nil {
		return x.ConstType
	}
	var zero ConstType
	return zero
}

// GetConstTypeOr returns the value of ConstType or the provided default if the receiver or field is nil.
func (x *ConstantDef) GetConstTypeOr(defaultValue ConstType) ConstType {
	if x != nil {
		return x.ConstType
	}
	return defaultValue
}

// GetValue returns the value of Value or the zero value if the receiver or field is nil.
func (x *ConstantDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	var zero string
	return zero
}

// GetValueOr returns the value of Value or the provided default if the receiver or field is nil.
func (x *ConstantDef) GetValueOr(defaultValue string) string {
	if x != nil {
		return x.Value
	}
	return defaultValue
}

// preConstantDef is the version of ConstantDef previous to the required field validation
type preConstantDef struct {
	Name       *string    `json:"name,omitempty"`
	Doc        *string    `json:"doc,omitempty"`
	Deprecated *string    `json:"deprecated,omitempty"`
	ConstType  *ConstType `json:"constType,omitempty"`
	Value      *string    `json:"value,omitempty"`
}

// validate validates the required fields of ConstantDef
func (p *preConstantDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preConstantDef is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	// Validation for field "constType"
	if p.ConstType == nil {
		return errorMissingRequiredField("field constType is required")
	}

	// Validation for field "value"
	if p.Value == nil {
		return errorMissingRequiredField("field value is required")
	}

	return nil
}

// transform transforms the preConstantDef type to the final ConstantDef type
func (p *preConstantDef) transform() ConstantDef {
	// Transformations
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated
	transConstType := *p.ConstType
	transValue := *p.Value

	// Assignments
	return ConstantDef{
		Name:       transName,
		Doc:        transDoc,
		Deprecated: transDeprecated,
		ConstType:  transConstType,
		Value:      transValue,
	}
}

// Represents a standalone documentation block
type DocDef struct {
	// The name of the RPC this doc belongs to. If empty this is a global standalone documentation block.
	RpcName *string `json:"rpcName,omitempty"`
	// The content of the documentation
	Content string `json:"content"`
}

// GetRpcName returns the value of RpcName or the zero value if the receiver or field is nil.
func (x *DocDef) GetRpcName() string {
	if x != nil && x.RpcName != nil {
		return *x.RpcName
	}
	var zero string
	return zero
}

// GetRpcNameOr returns the value of RpcName or the provided default if the receiver or field is nil.
func (x *DocDef) GetRpcNameOr(defaultValue string) string {
	if x != nil && x.RpcName != nil {
		return *x.RpcName
	}
	return defaultValue
}

// GetContent returns the value of Content or the zero value if the receiver or field is nil.
func (x *DocDef) GetContent() string {
	if x != nil {
		return x.Content
	}
	var zero string
	return zero
}

// GetContentOr returns the value of Content or the provided default if the receiver or field is nil.
func (x *DocDef) GetContentOr(defaultValue string) string {
	if x != nil {
		return x.Content
	}
	return defaultValue
}

// preDocDef is the version of DocDef previous to the required field validation
type preDocDef struct {
	RpcName *string `json:"rpcName,omitempty"`
	Content *string `json:"content,omitempty"`
}

// validate validates the required fields of DocDef
func (p *preDocDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preDocDef is nil")
	}

	// Validation for field "rpcName"

	// Validation for field "content"
	if p.Content == nil {
		return errorMissingRequiredField("field content is required")
	}

	return nil
}

// transform transforms the preDocDef type to the final DocDef type
func (p *preDocDef) transform() DocDef {
	// Transformations
	transRpcName := p.RpcName
	transContent := *p.Content

	// Assignments
	return DocDef{
		RpcName: transRpcName,
		Content: transContent,
	}
}

// Represents an enum definition
type EnumDef struct {
	// The name of the enum
	Name string `json:"name"`
	// Documentation for the enum
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
	// The type of this enum
	EnumType EnumType `json:"enumType"`
	// List of enum members
	Members []EnumDefMember `json:"members"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *EnumDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *EnumDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *EnumDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *EnumDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *EnumDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *EnumDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// GetEnumType returns the value of EnumType or the zero value if the receiver or field is nil.
func (x *EnumDef) GetEnumType() EnumType {
	if x != nil {
		return x.EnumType
	}
	var zero EnumType
	return zero
}

// GetEnumTypeOr returns the value of EnumType or the provided default if the receiver or field is nil.
func (x *EnumDef) GetEnumTypeOr(defaultValue EnumType) EnumType {
	if x != nil {
		return x.EnumType
	}
	return defaultValue
}

// GetMembers returns the value of Members or the zero value if the receiver or field is nil.
func (x *EnumDef) GetMembers() []EnumDefMember {
	if x != nil {
		return x.Members
	}
	var zero []EnumDefMember
	return zero
}

// GetMembersOr returns the value of Members or the provided default if the receiver or field is nil.
func (x *EnumDef) GetMembersOr(defaultValue []EnumDefMember) []EnumDefMember {
	if x != nil {
		return x.Members
	}
	return defaultValue
}

// preEnumDef is the version of EnumDef previous to the required field validation
type preEnumDef struct {
	Name       *string             `json:"name,omitempty"`
	Doc        *string             `json:"doc,omitempty"`
	Deprecated *string             `json:"deprecated,omitempty"`
	EnumType   *EnumType           `json:"enumType,omitempty"`
	Members    *[]preEnumDefMember `json:"members,omitempty"`
}

// validate validates the required fields of EnumDef
func (p *preEnumDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preEnumDef is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	// Validation for field "enumType"
	if p.EnumType == nil {
		return errorMissingRequiredField("field enumType is required")
	}

	// Validation for field "members"
	if p.Members == nil {
		return errorMissingRequiredField("field members is required")
	}
	if p.Members != nil {
		for _, item := range *p.Members {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field members: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preEnumDef type to the final EnumDef type
func (p *preEnumDef) transform() EnumDef {
	// Transformations
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated
	transEnumType := *p.EnumType
	var transMembers []EnumDefMember
	transMembers = make([]EnumDefMember, len(*p.Members))
	for i, v := range *p.Members {
		var tmp_ EnumDefMember
		tmp_ = v.transform()
		transMembers[i] = tmp_
	}

	// Assignments
	return EnumDef{
		Name:       transName,
		Doc:        transDoc,
		Deprecated: transDeprecated,
		EnumType:   transEnumType,
		Members:    transMembers,
	}
}

// A member of an enum
type EnumDefMember struct {
	// The name of the enum member
	Name string `json:"name"`
	// The value of the enum member as a string
	Value string `json:"value"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *EnumDefMember) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *EnumDefMember) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetValue returns the value of Value or the zero value if the receiver or field is nil.
func (x *EnumDefMember) GetValue() string {
	if x != nil {
		return x.Value
	}
	var zero string
	return zero
}

// GetValueOr returns the value of Value or the provided default if the receiver or field is nil.
func (x *EnumDefMember) GetValueOr(defaultValue string) string {
	if x != nil {
		return x.Value
	}
	return defaultValue
}

// preEnumDefMember is the version of EnumDefMember previous to the required field validation
type preEnumDefMember struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// validate validates the required fields of EnumDefMember
func (p *preEnumDefMember) validate() error {
	if p == nil {
		return errorMissingRequiredField("preEnumDefMember is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "value"
	if p.Value == nil {
		return errorMissingRequiredField("field value is required")
	}

	return nil
}

// transform transforms the preEnumDefMember type to the final EnumDefMember type
func (p *preEnumDefMember) transform() EnumDefMember {
	// Transformations
	transName := *p.Name
	transValue := *p.Value

	// Assignments
	return EnumDefMember{
		Name:  transName,
		Value: transValue,
	}
}

// Represents a field with its type fully resolved
type Field struct {
	// The name of the field
	Name string `json:"name"`
	// Documentation for the field
	Doc *string `json:"doc,omitempty"`
	// Whether the field is optional
	Optional bool `json:"optional"`
	// The type definition of the field
	TypeRef TypeRef `json:"typeRef"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *Field) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *Field) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *Field) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetOptional returns the value of Optional or the zero value if the receiver or field is nil.
func (x *Field) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	var zero bool
	return zero
}

// GetOptionalOr returns the value of Optional or the provided default if the receiver or field is nil.
func (x *Field) GetOptionalOr(defaultValue bool) bool {
	if x != nil {
		return x.Optional
	}
	return defaultValue
}

// GetTypeRef returns the value of TypeRef or the zero value if the receiver or field is nil.
func (x *Field) GetTypeRef() TypeRef {
	if x != nil {
		return x.TypeRef
	}
	var zero TypeRef
	return zero
}

// GetTypeRefOr returns the value of TypeRef or the provided default if the receiver or field is nil.
func (x *Field) GetTypeRefOr(defaultValue TypeRef) TypeRef {
	if x != nil {
		return x.TypeRef
	}
	return defaultValue
}

// preField is the version of Field previous to the required field validation
type preField struct {
	Name     *string     `json:"name,omitempty"`
	Doc      *string     `json:"doc,omitempty"`
	Optional *bool       `json:"optional,omitempty"`
	TypeRef  *preTypeRef `json:"typeRef,omitempty"`
}

// validate validates the required fields of Field
func (p *preField) validate() error {
	if p == nil {
		return errorMissingRequiredField("preField is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "optional"
	if p.Optional == nil {
		return errorMissingRequiredField("field optional is required")
	}

	// Validation for field "typeRef"
	if p.TypeRef == nil {
		return errorMissingRequiredField("field typeRef is required")
	}
	if p.TypeRef != nil {
		if err := p.TypeRef.validate(); err != nil {
			return errorMissingRequiredField("field typeRef: " + err.Error())
		}
	}

	return nil
}

// transform transforms the preField type to the final Field type
func (p *preField) transform() Field {
	// Transformations
	transName := *p.Name
	transDoc := p.Doc
	transOptional := *p.Optional
	var transTypeRef TypeRef
	transTypeRef = p.TypeRef.transform()

	// Assignments
	return Field{
		Name:     transName,
		Doc:      transDoc,
		Optional: transOptional,
		TypeRef:  transTypeRef,
	}
}

// IrSchema represents the root of the VDL Intermediate Representation (IR).
//
// It acts as the canonical, simplified view of the domain model, abstracting away
// the complexity of parsing, file structures, and syntactic sugar.
//
// This structure is the "Golden Platter" for code generators, plugins, and analysis tools:
// a flattened, fully resolved, and read-only data structure ready for consumption.
//
// To ensure reproducible builds and consistent outputs across different environments,
// all collections within the IRSchema are strictly sorted alphabetically.
//
// This is the structure on which code generators and plugins are executed, as it is the
// purest and simplest form of representation of the entire IDL.
type IrSchema struct {
	// List of all constant definitions in the schema
	Constants []ConstantDef `json:"constants"`
	// List of all pattern definitions in the schema
	Patterns []PatternDef `json:"patterns"`
	// List of all enum definitions in the schema
	Enums []EnumDef `json:"enums"`
	// List of all type definitions in the schema
	Types []TypeDef `json:"types"`
	// List of all RPC definitions in the schema
	Rpcs []RpcDef `json:"rpcs"`
	// Flattened list of all procedures from all RPCs
	Procedures []ProcedureDef `json:"procedures"`
	// Flattened list of all streams from all RPCs
	Streams []StreamDef `json:"streams"`
	// List of all standalone documentation blocks (even from all RPCs)
	Docs []DocDef `json:"docs"`
}

// GetConstants returns the value of Constants or the zero value if the receiver or field is nil.
func (x *IrSchema) GetConstants() []ConstantDef {
	if x != nil {
		return x.Constants
	}
	var zero []ConstantDef
	return zero
}

// GetConstantsOr returns the value of Constants or the provided default if the receiver or field is nil.
func (x *IrSchema) GetConstantsOr(defaultValue []ConstantDef) []ConstantDef {
	if x != nil {
		return x.Constants
	}
	return defaultValue
}

// GetPatterns returns the value of Patterns or the zero value if the receiver or field is nil.
func (x *IrSchema) GetPatterns() []PatternDef {
	if x != nil {
		return x.Patterns
	}
	var zero []PatternDef
	return zero
}

// GetPatternsOr returns the value of Patterns or the provided default if the receiver or field is nil.
func (x *IrSchema) GetPatternsOr(defaultValue []PatternDef) []PatternDef {
	if x != nil {
		return x.Patterns
	}
	return defaultValue
}

// GetEnums returns the value of Enums or the zero value if the receiver or field is nil.
func (x *IrSchema) GetEnums() []EnumDef {
	if x != nil {
		return x.Enums
	}
	var zero []EnumDef
	return zero
}

// GetEnumsOr returns the value of Enums or the provided default if the receiver or field is nil.
func (x *IrSchema) GetEnumsOr(defaultValue []EnumDef) []EnumDef {
	if x != nil {
		return x.Enums
	}
	return defaultValue
}

// GetTypes returns the value of Types or the zero value if the receiver or field is nil.
func (x *IrSchema) GetTypes() []TypeDef {
	if x != nil {
		return x.Types
	}
	var zero []TypeDef
	return zero
}

// GetTypesOr returns the value of Types or the provided default if the receiver or field is nil.
func (x *IrSchema) GetTypesOr(defaultValue []TypeDef) []TypeDef {
	if x != nil {
		return x.Types
	}
	return defaultValue
}

// GetRpcs returns the value of Rpcs or the zero value if the receiver or field is nil.
func (x *IrSchema) GetRpcs() []RpcDef {
	if x != nil {
		return x.Rpcs
	}
	var zero []RpcDef
	return zero
}

// GetRpcsOr returns the value of Rpcs or the provided default if the receiver or field is nil.
func (x *IrSchema) GetRpcsOr(defaultValue []RpcDef) []RpcDef {
	if x != nil {
		return x.Rpcs
	}
	return defaultValue
}

// GetProcedures returns the value of Procedures or the zero value if the receiver or field is nil.
func (x *IrSchema) GetProcedures() []ProcedureDef {
	if x != nil {
		return x.Procedures
	}
	var zero []ProcedureDef
	return zero
}

// GetProceduresOr returns the value of Procedures or the provided default if the receiver or field is nil.
func (x *IrSchema) GetProceduresOr(defaultValue []ProcedureDef) []ProcedureDef {
	if x != nil {
		return x.Procedures
	}
	return defaultValue
}

// GetStreams returns the value of Streams or the zero value if the receiver or field is nil.
func (x *IrSchema) GetStreams() []StreamDef {
	if x != nil {
		return x.Streams
	}
	var zero []StreamDef
	return zero
}

// GetStreamsOr returns the value of Streams or the provided default if the receiver or field is nil.
func (x *IrSchema) GetStreamsOr(defaultValue []StreamDef) []StreamDef {
	if x != nil {
		return x.Streams
	}
	return defaultValue
}

// GetDocs returns the value of Docs or the zero value if the receiver or field is nil.
func (x *IrSchema) GetDocs() []DocDef {
	if x != nil {
		return x.Docs
	}
	var zero []DocDef
	return zero
}

// GetDocsOr returns the value of Docs or the provided default if the receiver or field is nil.
func (x *IrSchema) GetDocsOr(defaultValue []DocDef) []DocDef {
	if x != nil {
		return x.Docs
	}
	return defaultValue
}

// preIrSchema is the version of IrSchema previous to the required field validation
type preIrSchema struct {
	Constants  *[]preConstantDef  `json:"constants,omitempty"`
	Patterns   *[]prePatternDef   `json:"patterns,omitempty"`
	Enums      *[]preEnumDef      `json:"enums,omitempty"`
	Types      *[]preTypeDef      `json:"types,omitempty"`
	Rpcs       *[]preRpcDef       `json:"rpcs,omitempty"`
	Procedures *[]preProcedureDef `json:"procedures,omitempty"`
	Streams    *[]preStreamDef    `json:"streams,omitempty"`
	Docs       *[]preDocDef       `json:"docs,omitempty"`
}

// validate validates the required fields of IrSchema
func (p *preIrSchema) validate() error {
	if p == nil {
		return errorMissingRequiredField("preIrSchema is nil")
	}

	// Validation for field "constants"
	if p.Constants == nil {
		return errorMissingRequiredField("field constants is required")
	}
	if p.Constants != nil {
		for _, item := range *p.Constants {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field constants: " + err.Error())
			}
		}
	}

	// Validation for field "patterns"
	if p.Patterns == nil {
		return errorMissingRequiredField("field patterns is required")
	}
	if p.Patterns != nil {
		for _, item := range *p.Patterns {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field patterns: " + err.Error())
			}
		}
	}

	// Validation for field "enums"
	if p.Enums == nil {
		return errorMissingRequiredField("field enums is required")
	}
	if p.Enums != nil {
		for _, item := range *p.Enums {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field enums: " + err.Error())
			}
		}
	}

	// Validation for field "types"
	if p.Types == nil {
		return errorMissingRequiredField("field types is required")
	}
	if p.Types != nil {
		for _, item := range *p.Types {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field types: " + err.Error())
			}
		}
	}

	// Validation for field "rpcs"
	if p.Rpcs == nil {
		return errorMissingRequiredField("field rpcs is required")
	}
	if p.Rpcs != nil {
		for _, item := range *p.Rpcs {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field rpcs: " + err.Error())
			}
		}
	}

	// Validation for field "procedures"
	if p.Procedures == nil {
		return errorMissingRequiredField("field procedures is required")
	}
	if p.Procedures != nil {
		for _, item := range *p.Procedures {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field procedures: " + err.Error())
			}
		}
	}

	// Validation for field "streams"
	if p.Streams == nil {
		return errorMissingRequiredField("field streams is required")
	}
	if p.Streams != nil {
		for _, item := range *p.Streams {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field streams: " + err.Error())
			}
		}
	}

	// Validation for field "docs"
	if p.Docs == nil {
		return errorMissingRequiredField("field docs is required")
	}
	if p.Docs != nil {
		for _, item := range *p.Docs {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field docs: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preIrSchema type to the final IrSchema type
func (p *preIrSchema) transform() IrSchema {
	// Transformations
	var transConstants []ConstantDef
	transConstants = make([]ConstantDef, len(*p.Constants))
	for i, v := range *p.Constants {
		var tmp_ ConstantDef
		tmp_ = v.transform()
		transConstants[i] = tmp_
	}
	var transPatterns []PatternDef
	transPatterns = make([]PatternDef, len(*p.Patterns))
	for i, v := range *p.Patterns {
		var tmp_ PatternDef
		tmp_ = v.transform()
		transPatterns[i] = tmp_
	}
	var transEnums []EnumDef
	transEnums = make([]EnumDef, len(*p.Enums))
	for i, v := range *p.Enums {
		var tmp_ EnumDef
		tmp_ = v.transform()
		transEnums[i] = tmp_
	}
	var transTypes []TypeDef
	transTypes = make([]TypeDef, len(*p.Types))
	for i, v := range *p.Types {
		var tmp_ TypeDef
		tmp_ = v.transform()
		transTypes[i] = tmp_
	}
	var transRpcs []RpcDef
	transRpcs = make([]RpcDef, len(*p.Rpcs))
	for i, v := range *p.Rpcs {
		var tmp_ RpcDef
		tmp_ = v.transform()
		transRpcs[i] = tmp_
	}
	var transProcedures []ProcedureDef
	transProcedures = make([]ProcedureDef, len(*p.Procedures))
	for i, v := range *p.Procedures {
		var tmp_ ProcedureDef
		tmp_ = v.transform()
		transProcedures[i] = tmp_
	}
	var transStreams []StreamDef
	transStreams = make([]StreamDef, len(*p.Streams))
	for i, v := range *p.Streams {
		var tmp_ StreamDef
		tmp_ = v.transform()
		transStreams[i] = tmp_
	}
	var transDocs []DocDef
	transDocs = make([]DocDef, len(*p.Docs))
	for i, v := range *p.Docs {
		var tmp_ DocDef
		tmp_ = v.transform()
		transDocs[i] = tmp_
	}

	// Assignments
	return IrSchema{
		Constants:  transConstants,
		Patterns:   transPatterns,
		Enums:      transEnums,
		Types:      transTypes,
		Rpcs:       transRpcs,
		Procedures: transProcedures,
		Streams:    transStreams,
		Docs:       transDocs,
	}
}

// Represents a pattern template for generating dynamic strings
type PatternDef struct {
	// The name of the pattern
	Name string `json:"name"`
	// Documentation for the pattern
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
	// The template string containing placeholders
	Template string `json:"template"`
	// List of placeholder names extracted from the template
	Placeholders []string `json:"placeholders"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *PatternDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *PatternDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *PatternDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *PatternDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *PatternDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *PatternDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// GetTemplate returns the value of Template or the zero value if the receiver or field is nil.
func (x *PatternDef) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	var zero string
	return zero
}

// GetTemplateOr returns the value of Template or the provided default if the receiver or field is nil.
func (x *PatternDef) GetTemplateOr(defaultValue string) string {
	if x != nil {
		return x.Template
	}
	return defaultValue
}

// GetPlaceholders returns the value of Placeholders or the zero value if the receiver or field is nil.
func (x *PatternDef) GetPlaceholders() []string {
	if x != nil {
		return x.Placeholders
	}
	var zero []string
	return zero
}

// GetPlaceholdersOr returns the value of Placeholders or the provided default if the receiver or field is nil.
func (x *PatternDef) GetPlaceholdersOr(defaultValue []string) []string {
	if x != nil {
		return x.Placeholders
	}
	return defaultValue
}

// prePatternDef is the version of PatternDef previous to the required field validation
type prePatternDef struct {
	Name         *string   `json:"name,omitempty"`
	Doc          *string   `json:"doc,omitempty"`
	Deprecated   *string   `json:"deprecated,omitempty"`
	Template     *string   `json:"template,omitempty"`
	Placeholders *[]string `json:"placeholders,omitempty"`
}

// validate validates the required fields of PatternDef
func (p *prePatternDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("prePatternDef is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	// Validation for field "template"
	if p.Template == nil {
		return errorMissingRequiredField("field template is required")
	}

	// Validation for field "placeholders"
	if p.Placeholders == nil {
		return errorMissingRequiredField("field placeholders is required")
	}

	return nil
}

// transform transforms the prePatternDef type to the final PatternDef type
func (p *prePatternDef) transform() PatternDef {
	// Transformations
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated
	transTemplate := *p.Template
	transPlaceholders := *p.Placeholders

	// Assignments
	return PatternDef{
		Name:         transName,
		Doc:          transDoc,
		Deprecated:   transDeprecated,
		Template:     transTemplate,
		Placeholders: transPlaceholders,
	}
}

// Represents an RPC procedure
type ProcedureDef struct {
	// The name of the parent RPC
	RpcName string `json:"rpcName"`
	// The name of the procedure
	Name string `json:"name"`
	// Documentation for the procedure
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
	// List of input fields in the same order in which they were written
	Input []Field `json:"input"`
	// List of output fields in the same order in which they were written
	Output []Field `json:"output"`
}

// GetRpcName returns the value of RpcName or the zero value if the receiver or field is nil.
func (x *ProcedureDef) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	var zero string
	return zero
}

// GetRpcNameOr returns the value of RpcName or the provided default if the receiver or field is nil.
func (x *ProcedureDef) GetRpcNameOr(defaultValue string) string {
	if x != nil {
		return x.RpcName
	}
	return defaultValue
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *ProcedureDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *ProcedureDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *ProcedureDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *ProcedureDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *ProcedureDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *ProcedureDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// GetInput returns the value of Input or the zero value if the receiver or field is nil.
func (x *ProcedureDef) GetInput() []Field {
	if x != nil {
		return x.Input
	}
	var zero []Field
	return zero
}

// GetInputOr returns the value of Input or the provided default if the receiver or field is nil.
func (x *ProcedureDef) GetInputOr(defaultValue []Field) []Field {
	if x != nil {
		return x.Input
	}
	return defaultValue
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *ProcedureDef) GetOutput() []Field {
	if x != nil {
		return x.Output
	}
	var zero []Field
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *ProcedureDef) GetOutputOr(defaultValue []Field) []Field {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// preProcedureDef is the version of ProcedureDef previous to the required field validation
type preProcedureDef struct {
	RpcName    *string     `json:"rpcName,omitempty"`
	Name       *string     `json:"name,omitempty"`
	Doc        *string     `json:"doc,omitempty"`
	Deprecated *string     `json:"deprecated,omitempty"`
	Input      *[]preField `json:"input,omitempty"`
	Output     *[]preField `json:"output,omitempty"`
}

// validate validates the required fields of ProcedureDef
func (p *preProcedureDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preProcedureDef is nil")
	}

	// Validation for field "rpcName"
	if p.RpcName == nil {
		return errorMissingRequiredField("field rpcName is required")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	// Validation for field "input"
	if p.Input == nil {
		return errorMissingRequiredField("field input is required")
	}
	if p.Input != nil {
		for _, item := range *p.Input {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field input: " + err.Error())
			}
		}
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}
	if p.Output != nil {
		for _, item := range *p.Output {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field output: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preProcedureDef type to the final ProcedureDef type
func (p *preProcedureDef) transform() ProcedureDef {
	// Transformations
	transRpcName := *p.RpcName
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated
	var transInput []Field
	transInput = make([]Field, len(*p.Input))
	for i, v := range *p.Input {
		var tmp_ Field
		tmp_ = v.transform()
		transInput[i] = tmp_
	}
	var transOutput []Field
	transOutput = make([]Field, len(*p.Output))
	for i, v := range *p.Output {
		var tmp_ Field
		tmp_ = v.transform()
		transOutput[i] = tmp_
	}

	// Assignments
	return ProcedureDef{
		RpcName:    transRpcName,
		Name:       transName,
		Doc:        transDoc,
		Deprecated: transDeprecated,
		Input:      transInput,
		Output:     transOutput,
	}
}

// Represents an RPC definition
type RpcDef struct {
	// The name of the RPC
	Name string `json:"name"`
	// Documentation for the RPC
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *RpcDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *RpcDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *RpcDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *RpcDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *RpcDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *RpcDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// preRpcDef is the version of RpcDef previous to the required field validation
type preRpcDef struct {
	Name       *string `json:"name,omitempty"`
	Doc        *string `json:"doc,omitempty"`
	Deprecated *string `json:"deprecated,omitempty"`
}

// validate validates the required fields of RpcDef
func (p *preRpcDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preRpcDef is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	return nil
}

// transform transforms the preRpcDef type to the final RpcDef type
func (p *preRpcDef) transform() RpcDef {
	// Transformations
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated

	// Assignments
	return RpcDef{
		Name:       transName,
		Doc:        transDoc,
		Deprecated: transDeprecated,
	}
}

// Represents an RPC stream
type StreamDef struct {
	// The name of the parent RPC
	RpcName string `json:"rpcName"`
	// The name of the stream
	Name string `json:"name"`
	// Documentation for the stream
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
	// List of input fields in the same order in which they were written
	Input []Field `json:"input"`
	// List of output fields in the same order in which they were written
	Output []Field `json:"output"`
}

// GetRpcName returns the value of RpcName or the zero value if the receiver or field is nil.
func (x *StreamDef) GetRpcName() string {
	if x != nil {
		return x.RpcName
	}
	var zero string
	return zero
}

// GetRpcNameOr returns the value of RpcName or the provided default if the receiver or field is nil.
func (x *StreamDef) GetRpcNameOr(defaultValue string) string {
	if x != nil {
		return x.RpcName
	}
	return defaultValue
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *StreamDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *StreamDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *StreamDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *StreamDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *StreamDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *StreamDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// GetInput returns the value of Input or the zero value if the receiver or field is nil.
func (x *StreamDef) GetInput() []Field {
	if x != nil {
		return x.Input
	}
	var zero []Field
	return zero
}

// GetInputOr returns the value of Input or the provided default if the receiver or field is nil.
func (x *StreamDef) GetInputOr(defaultValue []Field) []Field {
	if x != nil {
		return x.Input
	}
	return defaultValue
}

// GetOutput returns the value of Output or the zero value if the receiver or field is nil.
func (x *StreamDef) GetOutput() []Field {
	if x != nil {
		return x.Output
	}
	var zero []Field
	return zero
}

// GetOutputOr returns the value of Output or the provided default if the receiver or field is nil.
func (x *StreamDef) GetOutputOr(defaultValue []Field) []Field {
	if x != nil {
		return x.Output
	}
	return defaultValue
}

// preStreamDef is the version of StreamDef previous to the required field validation
type preStreamDef struct {
	RpcName    *string     `json:"rpcName,omitempty"`
	Name       *string     `json:"name,omitempty"`
	Doc        *string     `json:"doc,omitempty"`
	Deprecated *string     `json:"deprecated,omitempty"`
	Input      *[]preField `json:"input,omitempty"`
	Output     *[]preField `json:"output,omitempty"`
}

// validate validates the required fields of StreamDef
func (p *preStreamDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preStreamDef is nil")
	}

	// Validation for field "rpcName"
	if p.RpcName == nil {
		return errorMissingRequiredField("field rpcName is required")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	// Validation for field "input"
	if p.Input == nil {
		return errorMissingRequiredField("field input is required")
	}
	if p.Input != nil {
		for _, item := range *p.Input {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field input: " + err.Error())
			}
		}
	}

	// Validation for field "output"
	if p.Output == nil {
		return errorMissingRequiredField("field output is required")
	}
	if p.Output != nil {
		for _, item := range *p.Output {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field output: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preStreamDef type to the final StreamDef type
func (p *preStreamDef) transform() StreamDef {
	// Transformations
	transRpcName := *p.RpcName
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated
	var transInput []Field
	transInput = make([]Field, len(*p.Input))
	for i, v := range *p.Input {
		var tmp_ Field
		tmp_ = v.transform()
		transInput[i] = tmp_
	}
	var transOutput []Field
	transOutput = make([]Field, len(*p.Output))
	for i, v := range *p.Output {
		var tmp_ Field
		tmp_ = v.transform()
		transOutput[i] = tmp_
	}

	// Assignments
	return StreamDef{
		RpcName:    transRpcName,
		Name:       transName,
		Doc:        transDoc,
		Deprecated: transDeprecated,
		Input:      transInput,
		Output:     transOutput,
	}
}

// Represents a type definition
type TypeDef struct {
	// The name of the type
	Name string `json:"name"`
	// Documentation for the type
	Doc *string `json:"doc,omitempty"`
	// Deprecation status if deprecated
	Deprecated *string `json:"deprecated,omitempty"`
	// List of fields in the type in the same order in which they were written
	Fields []Field `json:"fields"`
}

// GetName returns the value of Name or the zero value if the receiver or field is nil.
func (x *TypeDef) GetName() string {
	if x != nil {
		return x.Name
	}
	var zero string
	return zero
}

// GetNameOr returns the value of Name or the provided default if the receiver or field is nil.
func (x *TypeDef) GetNameOr(defaultValue string) string {
	if x != nil {
		return x.Name
	}
	return defaultValue
}

// GetDoc returns the value of Doc or the zero value if the receiver or field is nil.
func (x *TypeDef) GetDoc() string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	var zero string
	return zero
}

// GetDocOr returns the value of Doc or the provided default if the receiver or field is nil.
func (x *TypeDef) GetDocOr(defaultValue string) string {
	if x != nil && x.Doc != nil {
		return *x.Doc
	}
	return defaultValue
}

// GetDeprecated returns the value of Deprecated or the zero value if the receiver or field is nil.
func (x *TypeDef) GetDeprecated() string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	var zero string
	return zero
}

// GetDeprecatedOr returns the value of Deprecated or the provided default if the receiver or field is nil.
func (x *TypeDef) GetDeprecatedOr(defaultValue string) string {
	if x != nil && x.Deprecated != nil {
		return *x.Deprecated
	}
	return defaultValue
}

// GetFields returns the value of Fields or the zero value if the receiver or field is nil.
func (x *TypeDef) GetFields() []Field {
	if x != nil {
		return x.Fields
	}
	var zero []Field
	return zero
}

// GetFieldsOr returns the value of Fields or the provided default if the receiver or field is nil.
func (x *TypeDef) GetFieldsOr(defaultValue []Field) []Field {
	if x != nil {
		return x.Fields
	}
	return defaultValue
}

// preTypeDef is the version of TypeDef previous to the required field validation
type preTypeDef struct {
	Name       *string     `json:"name,omitempty"`
	Doc        *string     `json:"doc,omitempty"`
	Deprecated *string     `json:"deprecated,omitempty"`
	Fields     *[]preField `json:"fields,omitempty"`
}

// validate validates the required fields of TypeDef
func (p *preTypeDef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preTypeDef is nil")
	}

	// Validation for field "name"
	if p.Name == nil {
		return errorMissingRequiredField("field name is required")
	}

	// Validation for field "doc"

	// Validation for field "deprecated"

	// Validation for field "fields"
	if p.Fields == nil {
		return errorMissingRequiredField("field fields is required")
	}
	if p.Fields != nil {
		for _, item := range *p.Fields {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field fields: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preTypeDef type to the final TypeDef type
func (p *preTypeDef) transform() TypeDef {
	// Transformations
	transName := *p.Name
	transDoc := p.Doc
	transDeprecated := p.Deprecated
	var transFields []Field
	transFields = make([]Field, len(*p.Fields))
	for i, v := range *p.Fields {
		var tmp_ Field
		tmp_ = v.transform()
		transFields[i] = tmp_
	}

	// Assignments
	return TypeDef{
		Name:       transName,
		Doc:        transDoc,
		Deprecated: transDeprecated,
		Fields:     transFields,
	}
}

// Represents any referenced type in a unified way
type TypeRef struct {
	// The category of the type
	Kind TypeKind `json:"kind"`
	// The name of the primitive type if Kind is primitive
	PrimitiveName *PrimitiveType `json:"primitiveName,omitempty"`
	// The name of the type if Kind is type
	TypeName *string `json:"typeName,omitempty"`
	// The name of the enum if Kind is enum
	EnumName *string `json:"enumName,omitempty"`
	// The type of the enum if Kind is enum
	EnumType *EnumType `json:"enumType,omitempty"`
	// The type of elements in the array if Kind is array
	ArrayType *TypeRef `json:"arrayType,omitempty"`
	// Number of array dimensions (e.g. 2 for int[][]) if Kind is array
	ArrayDims *int64 `json:"arrayDims,omitempty"`
	// The type of values in the map if Kind is map
	MapType *TypeRef `json:"mapType,omitempty"`
	// Fields of the inline object if Kind is object, in the same order in which they were written
	ObjectFields *[]Field `json:"objectFields,omitempty"`
}

// GetKind returns the value of Kind or the zero value if the receiver or field is nil.
func (x *TypeRef) GetKind() TypeKind {
	if x != nil {
		return x.Kind
	}
	var zero TypeKind
	return zero
}

// GetKindOr returns the value of Kind or the provided default if the receiver or field is nil.
func (x *TypeRef) GetKindOr(defaultValue TypeKind) TypeKind {
	if x != nil {
		return x.Kind
	}
	return defaultValue
}

// GetPrimitiveName returns the value of PrimitiveName or the zero value if the receiver or field is nil.
func (x *TypeRef) GetPrimitiveName() PrimitiveType {
	if x != nil && x.PrimitiveName != nil {
		return *x.PrimitiveName
	}
	var zero PrimitiveType
	return zero
}

// GetPrimitiveNameOr returns the value of PrimitiveName or the provided default if the receiver or field is nil.
func (x *TypeRef) GetPrimitiveNameOr(defaultValue PrimitiveType) PrimitiveType {
	if x != nil && x.PrimitiveName != nil {
		return *x.PrimitiveName
	}
	return defaultValue
}

// GetTypeName returns the value of TypeName or the zero value if the receiver or field is nil.
func (x *TypeRef) GetTypeName() string {
	if x != nil && x.TypeName != nil {
		return *x.TypeName
	}
	var zero string
	return zero
}

// GetTypeNameOr returns the value of TypeName or the provided default if the receiver or field is nil.
func (x *TypeRef) GetTypeNameOr(defaultValue string) string {
	if x != nil && x.TypeName != nil {
		return *x.TypeName
	}
	return defaultValue
}

// GetEnumName returns the value of EnumName or the zero value if the receiver or field is nil.
func (x *TypeRef) GetEnumName() string {
	if x != nil && x.EnumName != nil {
		return *x.EnumName
	}
	var zero string
	return zero
}

// GetEnumNameOr returns the value of EnumName or the provided default if the receiver or field is nil.
func (x *TypeRef) GetEnumNameOr(defaultValue string) string {
	if x != nil && x.EnumName != nil {
		return *x.EnumName
	}
	return defaultValue
}

// GetEnumType returns the value of EnumType or the zero value if the receiver or field is nil.
func (x *TypeRef) GetEnumType() EnumType {
	if x != nil && x.EnumType != nil {
		return *x.EnumType
	}
	var zero EnumType
	return zero
}

// GetEnumTypeOr returns the value of EnumType or the provided default if the receiver or field is nil.
func (x *TypeRef) GetEnumTypeOr(defaultValue EnumType) EnumType {
	if x != nil && x.EnumType != nil {
		return *x.EnumType
	}
	return defaultValue
}

// GetArrayType returns the value of ArrayType or the zero value if the receiver or field is nil.
func (x *TypeRef) GetArrayType() TypeRef {
	if x != nil && x.ArrayType != nil {
		return *x.ArrayType
	}
	var zero TypeRef
	return zero
}

// GetArrayTypeOr returns the value of ArrayType or the provided default if the receiver or field is nil.
func (x *TypeRef) GetArrayTypeOr(defaultValue TypeRef) TypeRef {
	if x != nil && x.ArrayType != nil {
		return *x.ArrayType
	}
	return defaultValue
}

// GetArrayDims returns the value of ArrayDims or the zero value if the receiver or field is nil.
func (x *TypeRef) GetArrayDims() int64 {
	if x != nil && x.ArrayDims != nil {
		return *x.ArrayDims
	}
	var zero int64
	return zero
}

// GetArrayDimsOr returns the value of ArrayDims or the provided default if the receiver or field is nil.
func (x *TypeRef) GetArrayDimsOr(defaultValue int64) int64 {
	if x != nil && x.ArrayDims != nil {
		return *x.ArrayDims
	}
	return defaultValue
}

// GetMapType returns the value of MapType or the zero value if the receiver or field is nil.
func (x *TypeRef) GetMapType() TypeRef {
	if x != nil && x.MapType != nil {
		return *x.MapType
	}
	var zero TypeRef
	return zero
}

// GetMapTypeOr returns the value of MapType or the provided default if the receiver or field is nil.
func (x *TypeRef) GetMapTypeOr(defaultValue TypeRef) TypeRef {
	if x != nil && x.MapType != nil {
		return *x.MapType
	}
	return defaultValue
}

// GetObjectFields returns the value of ObjectFields or the zero value if the receiver or field is nil.
func (x *TypeRef) GetObjectFields() []Field {
	if x != nil && x.ObjectFields != nil {
		return *x.ObjectFields
	}
	var zero []Field
	return zero
}

// GetObjectFieldsOr returns the value of ObjectFields or the provided default if the receiver or field is nil.
func (x *TypeRef) GetObjectFieldsOr(defaultValue []Field) []Field {
	if x != nil && x.ObjectFields != nil {
		return *x.ObjectFields
	}
	return defaultValue
}

// preTypeRef is the version of TypeRef previous to the required field validation
type preTypeRef struct {
	Kind          *TypeKind      `json:"kind,omitempty"`
	PrimitiveName *PrimitiveType `json:"primitiveName,omitempty"`
	TypeName      *string        `json:"typeName,omitempty"`
	EnumName      *string        `json:"enumName,omitempty"`
	EnumType      *EnumType      `json:"enumType,omitempty"`
	ArrayType     *preTypeRef    `json:"arrayType,omitempty"`
	ArrayDims     *int64         `json:"arrayDims,omitempty"`
	MapType       *preTypeRef    `json:"mapType,omitempty"`
	ObjectFields  *[]preField    `json:"objectFields,omitempty"`
}

// validate validates the required fields of TypeRef
func (p *preTypeRef) validate() error {
	if p == nil {
		return errorMissingRequiredField("preTypeRef is nil")
	}

	// Validation for field "kind"
	if p.Kind == nil {
		return errorMissingRequiredField("field kind is required")
	}

	// Validation for field "primitiveName"

	// Validation for field "typeName"

	// Validation for field "enumName"

	// Validation for field "enumType"

	// Validation for field "arrayType"
	if p.ArrayType != nil {
		if err := p.ArrayType.validate(); err != nil {
			return errorMissingRequiredField("field arrayType: " + err.Error())
		}
	}

	// Validation for field "arrayDims"

	// Validation for field "mapType"
	if p.MapType != nil {
		if err := p.MapType.validate(); err != nil {
			return errorMissingRequiredField("field mapType: " + err.Error())
		}
	}

	// Validation for field "objectFields"
	if p.ObjectFields != nil {
		for _, item := range *p.ObjectFields {
			if err := item.validate(); err != nil {
				return errorMissingRequiredField("field objectFields: " + err.Error())
			}
		}
	}

	return nil
}

// transform transforms the preTypeRef type to the final TypeRef type
func (p *preTypeRef) transform() TypeRef {
	// Transformations
	transKind := *p.Kind
	transPrimitiveName := p.PrimitiveName
	transTypeName := p.TypeName
	transEnumName := p.EnumName
	transEnumType := p.EnumType
	var transArrayType *TypeRef
	if p.ArrayType != nil {
		var valArrayType TypeRef
		valArrayType = p.ArrayType.transform()
		transArrayType = &valArrayType
	}
	transArrayDims := p.ArrayDims
	var transMapType *TypeRef
	if p.MapType != nil {
		var valMapType TypeRef
		valMapType = p.MapType.transform()
		transMapType = &valMapType
	}
	var transObjectFields *[]Field
	if p.ObjectFields != nil {
		var valObjectFields []Field
		valObjectFields = make([]Field, len(*p.ObjectFields))
		for i, v := range *p.ObjectFields {
			var tmp_ Field
			tmp_ = v.transform()
			valObjectFields[i] = tmp_
		}
		transObjectFields = &valObjectFields
	}

	// Assignments
	return TypeRef{
		Kind:          transKind,
		PrimitiveName: transPrimitiveName,
		TypeName:      transTypeName,
		EnumName:      transEnumName,
		EnumType:      transEnumType,
		ArrayType:     transArrayType,
		ArrayDims:     transArrayDims,
		MapType:       transMapType,
		ObjectFields:  transObjectFields,
	}
}
