package dart

import (
	_ "embed"
	"strings"

	"github.com/varavelio/vdl/toolchain/internal/core/ir"
)

//go:embed pieces/core.dart
var coreRawPiece string

func generateCore(_ *ir.Schema, _ *flatSchema, _ Config) (string, error) {
	// Ensure the embedded core includes a clear top-level notice; keep content unchanged otherwise.
	if !strings.Contains(coreRawPiece, "Code generated by VDL") {
		return "// Code generated by VDL. DO NOT EDIT.\n" + coreRawPiece, nil
	}
	return coreRawPiece, nil
}
