package dart

import (
	_ "embed"
	"strings"

	"github.com/uforg/uforpc/urpc/internal/schema"
)

//go:embed pieces/core.dart
var coreRawPiece string

func generateCore(_ schema.Schema, _ Config) (string, error) {
	// Ensure the embedded core includes a clear top-level notice; keep content unchanged otherwise.
	if !strings.Contains(coreRawPiece, "Code generated by UFO RPC") {
		return "// Code generated by UFO RPC. DO NOT EDIT.\n" + coreRawPiece, nil
	}
	return coreRawPiece, nil
}
