// Code generated by VDL v0.0.0-dev (commit unknown) using varavelio/vdl-plugin-go@v0.1.0 (hash c4cd3d26)
// Any changes will be overwritten the next time VDL is run. DO NOT EDIT.
// Learn more: https://github.com/varavelio/vdl

package configtypes

import (
	"encoding/json"
	"fmt"
)

// VDL configuration file schema.
type VdlConfig struct {
	// The version of the configuration file format. This should be set to 1.
	Version int64 `json:"version"`
	// If VDL should clean the output directories before generating code. Default is true.
	CleanOutDir *bool `json:"cleanOutDir,omitempty"`
	// Optional list of remote repositories or servers that can be used to fetch plugins.
	// Not required but useful if you want to use plugins from private repositories or
	// servers that require authentication. Each plugin will be matched against the remotes
	// based on the host.
	Remotes *[]VdlConfigRemote `json:"remotes,omitempty"`
	// List of plugins to be used for code generation.
	Plugins *[]VdlConfigPlugin `json:"plugins,omitempty"`
	// Global lifecycle hooks executed on the host machine.
	// These hooks are ignored in cloud or otherwise sandboxed execution environments.
	Hooks *VdlConfigHooks `json:"hooks,omitempty"`
}

// preVdlConfig mirrors VdlConfig during strict JSON decoding.
type preVdlConfig struct {
	Version     *int64                `json:"version"`
	CleanOutDir *bool                 `json:"cleanOutDir,omitempty"`
	Remotes     *[]preVdlConfigRemote `json:"remotes,omitempty"`
	Plugins     *[]preVdlConfigPlugin `json:"plugins,omitempty"`
	Hooks       *VdlConfigHooks       `json:"hooks,omitempty"`
}

// validate reports whether preVdlConfig satisfies strict JSON requirements.
func (p *preVdlConfig) validate(parentPath string) error {
	vdlPathVersion := "version"
	if parentPath != "" {
		vdlPathVersion = parentPath + ".version"
	}
	if p.Version == nil {
		return fmt.Errorf("field %s is required", vdlPathVersion)
	}

	vdlPathRemotes := "remotes"
	if parentPath != "" {
		vdlPathRemotes = parentPath + ".remotes"
	}
	if p.Remotes != nil {
		for vdlIndex0, vdlItem0 := range *p.Remotes {
			vdlItemPath0 := fmt.Sprintf("%s[%d]", vdlPathRemotes, vdlIndex0)
			if err := vdlItem0.validate(vdlItemPath0); err != nil {
				return err
			}
		}
	}

	vdlPathPlugins := "plugins"
	if parentPath != "" {
		vdlPathPlugins = parentPath + ".plugins"
	}
	if p.Plugins != nil {
		for vdlIndex0, vdlItem0 := range *p.Plugins {
			vdlItemPath0 := fmt.Sprintf("%s[%d]", vdlPathPlugins, vdlIndex0)
			if err := vdlItem0.validate(vdlItemPath0); err != nil {
				return err
			}
		}
	}

	return nil
}

// transform converts preVdlConfig to VdlConfig.
func (p *preVdlConfig) transform() VdlConfig {
	var transVersion int64
	transVersion = *p.Version

	var transCleanOutDir *bool
	transCleanOutDir = p.CleanOutDir

	var transRemotes *[]VdlConfigRemote
	if p.Remotes != nil {
		var valueRemotes []VdlConfigRemote
		valueRemotes = make([]VdlConfigRemote, len(*p.Remotes))
		for vdlIndex0, vdlItem0 := range *p.Remotes {
			var vdlTransformed0 VdlConfigRemote
			vdlTransformed0 = VdlConfigRemote(vdlItem0.transform())
			valueRemotes[vdlIndex0] = vdlTransformed0
		}
		transRemotes = &valueRemotes
	}

	var transPlugins *[]VdlConfigPlugin
	if p.Plugins != nil {
		var valuePlugins []VdlConfigPlugin
		valuePlugins = make([]VdlConfigPlugin, len(*p.Plugins))
		for vdlIndex0, vdlItem0 := range *p.Plugins {
			var vdlTransformed0 VdlConfigPlugin
			vdlTransformed0 = VdlConfigPlugin(vdlItem0.transform())
			valuePlugins[vdlIndex0] = vdlTransformed0
		}
		transPlugins = &valuePlugins
	}

	var transHooks *VdlConfigHooks
	transHooks = p.Hooks

	return VdlConfig{
		Version:     transVersion,
		CleanOutDir: transCleanOutDir,
		Remotes:     transRemotes,
		Plugins:     transPlugins,
		Hooks:       transHooks,
	}
}

// UnmarshalJSON decodes VdlConfig while requiring every non-optional JSON field.
func (x *VdlConfig) UnmarshalJSON(data []byte) error {
	var pre preVdlConfig
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetVersion returns the Version field. It returns the zero value when the receiver is nil.
func (x *VdlConfig) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	var zero int64
	return zero
}

// GetVersionOr returns the Version field. It returns defaultValue when the receiver is nil.
func (x *VdlConfig) GetVersionOr(defaultValue int64) int64 {
	if x != nil {
		return x.Version
	}
	return defaultValue
}

// GetCleanOutDir returns the CleanOutDir field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfig) GetCleanOutDir() bool {
	if x != nil && x.CleanOutDir != nil {
		return *x.CleanOutDir
	}
	var zero bool
	return zero
}

// GetCleanOutDirOr returns the CleanOutDir field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfig) GetCleanOutDirOr(defaultValue bool) bool {
	if x != nil && x.CleanOutDir != nil {
		return *x.CleanOutDir
	}
	return defaultValue
}

// GetRemotes returns the Remotes field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfig) GetRemotes() []VdlConfigRemote {
	if x != nil && x.Remotes != nil {
		return *x.Remotes
	}
	var zero []VdlConfigRemote
	return zero
}

// GetRemotesOr returns the Remotes field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfig) GetRemotesOr(defaultValue []VdlConfigRemote) []VdlConfigRemote {
	if x != nil && x.Remotes != nil {
		return *x.Remotes
	}
	return defaultValue
}

// GetPlugins returns the Plugins field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfig) GetPlugins() []VdlConfigPlugin {
	if x != nil && x.Plugins != nil {
		return *x.Plugins
	}
	var zero []VdlConfigPlugin
	return zero
}

// GetPluginsOr returns the Plugins field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfig) GetPluginsOr(defaultValue []VdlConfigPlugin) []VdlConfigPlugin {
	if x != nil && x.Plugins != nil {
		return *x.Plugins
	}
	return defaultValue
}

// GetHooks returns the Hooks field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfig) GetHooks() VdlConfigHooks {
	if x != nil && x.Hooks != nil {
		return *x.Hooks
	}
	var zero VdlConfigHooks
	return zero
}

// GetHooksOr returns the Hooks field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfig) GetHooksOr(defaultValue VdlConfigHooks) VdlConfigHooks {
	if x != nil && x.Hooks != nil {
		return *x.Hooks
	}
	return defaultValue
}

// VDL global hook configuration.
type VdlConfigHooks struct {
	// Commands executed before the generation pipeline starts.
	// If any command fails, generation stops immediately.
	PreGenerate *[]string `json:"preGenerate,omitempty"`
	// Commands executed after generated files are written to disk.
	// Failed commands are reported as warnings and do not roll back generated files.
	PostGenerate *[]string `json:"postGenerate,omitempty"`
}

// GetPreGenerate returns the PreGenerate field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigHooks) GetPreGenerate() []string {
	if x != nil && x.PreGenerate != nil {
		return *x.PreGenerate
	}
	var zero []string
	return zero
}

// GetPreGenerateOr returns the PreGenerate field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigHooks) GetPreGenerateOr(defaultValue []string) []string {
	if x != nil && x.PreGenerate != nil {
		return *x.PreGenerate
	}
	return defaultValue
}

// GetPostGenerate returns the PostGenerate field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigHooks) GetPostGenerate() []string {
	if x != nil && x.PostGenerate != nil {
		return *x.PostGenerate
	}
	var zero []string
	return zero
}

// GetPostGenerateOr returns the PostGenerate field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigHooks) GetPostGenerateOr(defaultValue []string) []string {
	if x != nil && x.PostGenerate != nil {
		return *x.PostGenerate
	}
	return defaultValue
}

// VDL plugin configuration.
type VdlConfigPlugin struct {
	// The source of the plugin, it can be:
	//
	// - A GitHub repo in the format "owner/repo@ref" containing a plugin file at ./dist/index.js.
	//   The ref MUST be a tag (release version) or a full commit hash (branches are highly discouraged
	//   to prevent lockfile conflicts).
	// - A local path to a plugin file, e.g. "./plugins/<plugin-name>/plugin/index.js" (always start with . or /).
	// - A remote URL to a plugin file, e.g. "https://example.com/plugin/index.js". (always start with https://).
	Src string `json:"src"`
	// Relative path to the input schema file for this plugin. VDL passes the processed intermediate
	// representation of this schema to the plugin for code generation and then writes the generated
	// code to the output directory specified by outDir.
	Schema string `json:"schema"`
	// The output directory for the generated code. All generated files from this plugin will be relatively
	// placed under this directory.
	OutDir string `json:"outDir"`
	// Whether to generate header comments in the generated files. Default is true.
	//
	// If true, VDL will add a header comment to each generated file indicating that it was generated
	// by VDL and should not be edited manually, along with the VDL and plugin version information
	// for auditing purposes.
	GenerateHeader *bool `json:"generateHeader,omitempty"`
	// Optional map of options to be passed to the plugin. The content of this map will be plugin-specific
	// and is passed as-is to the plugin. The plugin can define its own options so read the plugin
	// documentation for details.
	Options *map[string]string `json:"options,omitempty"`
}

// preVdlConfigPlugin mirrors VdlConfigPlugin during strict JSON decoding.
type preVdlConfigPlugin struct {
	Src            *string            `json:"src"`
	Schema         *string            `json:"schema"`
	OutDir         *string            `json:"outDir"`
	GenerateHeader *bool              `json:"generateHeader,omitempty"`
	Options        *map[string]string `json:"options,omitempty"`
}

// validate reports whether preVdlConfigPlugin satisfies strict JSON requirements.
func (p *preVdlConfigPlugin) validate(parentPath string) error {
	vdlPathSrc := "src"
	if parentPath != "" {
		vdlPathSrc = parentPath + ".src"
	}
	if p.Src == nil {
		return fmt.Errorf("field %s is required", vdlPathSrc)
	}

	vdlPathSchema := "schema"
	if parentPath != "" {
		vdlPathSchema = parentPath + ".schema"
	}
	if p.Schema == nil {
		return fmt.Errorf("field %s is required", vdlPathSchema)
	}

	vdlPathOutDir := "outDir"
	if parentPath != "" {
		vdlPathOutDir = parentPath + ".outDir"
	}
	if p.OutDir == nil {
		return fmt.Errorf("field %s is required", vdlPathOutDir)
	}

	return nil
}

// transform converts preVdlConfigPlugin to VdlConfigPlugin.
func (p *preVdlConfigPlugin) transform() VdlConfigPlugin {
	var transSrc string
	transSrc = *p.Src

	var transSchema string
	transSchema = *p.Schema

	var transOutDir string
	transOutDir = *p.OutDir

	var transGenerateHeader *bool
	transGenerateHeader = p.GenerateHeader

	var transOptions *map[string]string
	transOptions = p.Options

	return VdlConfigPlugin{
		Src:            transSrc,
		Schema:         transSchema,
		OutDir:         transOutDir,
		GenerateHeader: transGenerateHeader,
		Options:        transOptions,
	}
}

// UnmarshalJSON decodes VdlConfigPlugin while requiring every non-optional JSON field.
func (x *VdlConfigPlugin) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigPlugin
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetSrc returns the Src field. It returns the zero value when the receiver is nil.
func (x *VdlConfigPlugin) GetSrc() string {
	if x != nil {
		return x.Src
	}
	var zero string
	return zero
}

// GetSrcOr returns the Src field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigPlugin) GetSrcOr(defaultValue string) string {
	if x != nil {
		return x.Src
	}
	return defaultValue
}

// GetSchema returns the Schema field. It returns the zero value when the receiver is nil.
func (x *VdlConfigPlugin) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	var zero string
	return zero
}

// GetSchemaOr returns the Schema field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigPlugin) GetSchemaOr(defaultValue string) string {
	if x != nil {
		return x.Schema
	}
	return defaultValue
}

// GetOutDir returns the OutDir field. It returns the zero value when the receiver is nil.
func (x *VdlConfigPlugin) GetOutDir() string {
	if x != nil {
		return x.OutDir
	}
	var zero string
	return zero
}

// GetOutDirOr returns the OutDir field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigPlugin) GetOutDirOr(defaultValue string) string {
	if x != nil {
		return x.OutDir
	}
	return defaultValue
}

// GetGenerateHeader returns the GenerateHeader field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigPlugin) GetGenerateHeader() bool {
	if x != nil && x.GenerateHeader != nil {
		return *x.GenerateHeader
	}
	var zero bool
	return zero
}

// GetGenerateHeaderOr returns the GenerateHeader field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigPlugin) GetGenerateHeaderOr(defaultValue bool) bool {
	if x != nil && x.GenerateHeader != nil {
		return *x.GenerateHeader
	}
	return defaultValue
}

// GetOptions returns the Options field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigPlugin) GetOptions() map[string]string {
	if x != nil && x.Options != nil {
		return *x.Options
	}
	var zero map[string]string
	return zero
}

// GetOptionsOr returns the Options field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigPlugin) GetOptionsOr(defaultValue map[string]string) map[string]string {
	if x != nil && x.Options != nil {
		return *x.Options
	}
	return defaultValue
}

// VDL remote configuration.
type VdlConfigRemote struct {
	// The host URL of the remote repository or server without http(s):// prefix
	// e.g. "github.com", "github.com/owner/repo", "example.com" or "example.com/plugins".
	//
	// If a plugin match multiple remotes, the most specific match will be used
	// e.g. if a plugin is from "github.com/owner/repo/dist/index.js", the remote with
	// host "github.com/owner/repo" will be used instead of the remote with host "github.com".
	Host string `json:"host"`
	// Authentication details for accessing this remote host.
	Auth *VdlConfigRemoteAuth `json:"auth,omitempty"`
}

// preVdlConfigRemote mirrors VdlConfigRemote during strict JSON decoding.
type preVdlConfigRemote struct {
	Host *string                 `json:"host"`
	Auth *preVdlConfigRemoteAuth `json:"auth,omitempty"`
}

// validate reports whether preVdlConfigRemote satisfies strict JSON requirements.
func (p *preVdlConfigRemote) validate(parentPath string) error {
	vdlPathHost := "host"
	if parentPath != "" {
		vdlPathHost = parentPath + ".host"
	}
	if p.Host == nil {
		return fmt.Errorf("field %s is required", vdlPathHost)
	}

	vdlPathAuth := "auth"
	if parentPath != "" {
		vdlPathAuth = parentPath + ".auth"
	}
	if p.Auth != nil {
		if err := p.Auth.validate(vdlPathAuth); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preVdlConfigRemote to VdlConfigRemote.
func (p *preVdlConfigRemote) transform() VdlConfigRemote {
	var transHost string
	transHost = *p.Host

	var transAuth *VdlConfigRemoteAuth
	if p.Auth != nil {
		var valueAuth VdlConfigRemoteAuth
		valueAuth = VdlConfigRemoteAuth(p.Auth.transform())
		transAuth = &valueAuth
	}

	return VdlConfigRemote{
		Host: transHost,
		Auth: transAuth,
	}
}

// UnmarshalJSON decodes VdlConfigRemote while requiring every non-optional JSON field.
func (x *VdlConfigRemote) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigRemote
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetHost returns the Host field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemote) GetHost() string {
	if x != nil {
		return x.Host
	}
	var zero string
	return zero
}

// GetHostOr returns the Host field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemote) GetHostOr(defaultValue string) string {
	if x != nil {
		return x.Host
	}
	return defaultValue
}

// GetAuth returns the Auth field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigRemote) GetAuth() VdlConfigRemoteAuth {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	var zero VdlConfigRemoteAuth
	return zero
}

// GetAuthOr returns the Auth field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigRemote) GetAuthOr(defaultValue VdlConfigRemoteAuth) VdlConfigRemoteAuth {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return defaultValue
}

// VDL remote authentication configuration.
type VdlConfigRemoteAuth struct {
	// GitHub authentication details.
	Github *VdlConfigRemoteAuthGithub `json:"github,omitempty"`
	// Header-based authentication details.
	Header *VdlConfigRemoteAuthHeader `json:"header,omitempty"`
	// Bearer token authentication details.
	Bearer *VdlConfigRemoteAuthBearer `json:"bearer,omitempty"`
	// Basic authentication details.
	Basic *VdlConfigRemoteAuthBasic `json:"basic,omitempty"`
}

// preVdlConfigRemoteAuth mirrors VdlConfigRemoteAuth during strict JSON decoding.
type preVdlConfigRemoteAuth struct {
	Github *preVdlConfigRemoteAuthGithub `json:"github,omitempty"`
	Header *preVdlConfigRemoteAuthHeader `json:"header,omitempty"`
	Bearer *preVdlConfigRemoteAuthBearer `json:"bearer,omitempty"`
	Basic  *preVdlConfigRemoteAuthBasic  `json:"basic,omitempty"`
}

// validate reports whether preVdlConfigRemoteAuth satisfies strict JSON requirements.
func (p *preVdlConfigRemoteAuth) validate(parentPath string) error {
	vdlPathGithub := "github"
	if parentPath != "" {
		vdlPathGithub = parentPath + ".github"
	}
	if p.Github != nil {
		if err := p.Github.validate(vdlPathGithub); err != nil {
			return err
		}
	}

	vdlPathHeader := "header"
	if parentPath != "" {
		vdlPathHeader = parentPath + ".header"
	}
	if p.Header != nil {
		if err := p.Header.validate(vdlPathHeader); err != nil {
			return err
		}
	}

	vdlPathBearer := "bearer"
	if parentPath != "" {
		vdlPathBearer = parentPath + ".bearer"
	}
	if p.Bearer != nil {
		if err := p.Bearer.validate(vdlPathBearer); err != nil {
			return err
		}
	}

	vdlPathBasic := "basic"
	if parentPath != "" {
		vdlPathBasic = parentPath + ".basic"
	}
	if p.Basic != nil {
		if err := p.Basic.validate(vdlPathBasic); err != nil {
			return err
		}
	}
	return nil
}

// transform converts preVdlConfigRemoteAuth to VdlConfigRemoteAuth.
func (p *preVdlConfigRemoteAuth) transform() VdlConfigRemoteAuth {
	var transGithub *VdlConfigRemoteAuthGithub
	if p.Github != nil {
		var valueGithub VdlConfigRemoteAuthGithub
		valueGithub = VdlConfigRemoteAuthGithub(p.Github.transform())
		transGithub = &valueGithub
	}

	var transHeader *VdlConfigRemoteAuthHeader
	if p.Header != nil {
		var valueHeader VdlConfigRemoteAuthHeader
		valueHeader = VdlConfigRemoteAuthHeader(p.Header.transform())
		transHeader = &valueHeader
	}

	var transBearer *VdlConfigRemoteAuthBearer
	if p.Bearer != nil {
		var valueBearer VdlConfigRemoteAuthBearer
		valueBearer = VdlConfigRemoteAuthBearer(p.Bearer.transform())
		transBearer = &valueBearer
	}

	var transBasic *VdlConfigRemoteAuthBasic
	if p.Basic != nil {
		var valueBasic VdlConfigRemoteAuthBasic
		valueBasic = VdlConfigRemoteAuthBasic(p.Basic.transform())
		transBasic = &valueBasic
	}

	return VdlConfigRemoteAuth{
		Github: transGithub,
		Header: transHeader,
		Bearer: transBearer,
		Basic:  transBasic,
	}
}

// UnmarshalJSON decodes VdlConfigRemoteAuth while requiring every non-optional JSON field.
func (x *VdlConfigRemoteAuth) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigRemoteAuth
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetGithub returns the Github field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetGithub() VdlConfigRemoteAuthGithub {
	if x != nil && x.Github != nil {
		return *x.Github
	}
	var zero VdlConfigRemoteAuthGithub
	return zero
}

// GetGithubOr returns the Github field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetGithubOr(defaultValue VdlConfigRemoteAuthGithub) VdlConfigRemoteAuthGithub {
	if x != nil && x.Github != nil {
		return *x.Github
	}
	return defaultValue
}

// GetHeader returns the Header field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetHeader() VdlConfigRemoteAuthHeader {
	if x != nil && x.Header != nil {
		return *x.Header
	}
	var zero VdlConfigRemoteAuthHeader
	return zero
}

// GetHeaderOr returns the Header field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetHeaderOr(defaultValue VdlConfigRemoteAuthHeader) VdlConfigRemoteAuthHeader {
	if x != nil && x.Header != nil {
		return *x.Header
	}
	return defaultValue
}

// GetBearer returns the Bearer field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetBearer() VdlConfigRemoteAuthBearer {
	if x != nil && x.Bearer != nil {
		return *x.Bearer
	}
	var zero VdlConfigRemoteAuthBearer
	return zero
}

// GetBearerOr returns the Bearer field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetBearerOr(defaultValue VdlConfigRemoteAuthBearer) VdlConfigRemoteAuthBearer {
	if x != nil && x.Bearer != nil {
		return *x.Bearer
	}
	return defaultValue
}

// GetBasic returns the Basic field. It returns the zero value when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetBasic() VdlConfigRemoteAuthBasic {
	if x != nil && x.Basic != nil {
		return *x.Basic
	}
	var zero VdlConfigRemoteAuthBasic
	return zero
}

// GetBasicOr returns the Basic field. It returns defaultValue when the receiver or field is nil.
func (x *VdlConfigRemoteAuth) GetBasicOr(defaultValue VdlConfigRemoteAuthBasic) VdlConfigRemoteAuthBasic {
	if x != nil && x.Basic != nil {
		return *x.Basic
	}
	return defaultValue
}

// Basic authentication configuration. The environment variables should contain the
// username and password to be sent as a header with the name "Authorization" and
// the value will be "Basic <base64-encoded credentials>".
type VdlConfigRemoteAuthBasic struct {
	// The name of the environment variable that contains the username.
	UserEnv string `json:"userEnv"`
	// The name of the environment variable that contains the password.
	PassEnv string `json:"passEnv"`
}

// preVdlConfigRemoteAuthBasic mirrors VdlConfigRemoteAuthBasic during strict JSON decoding.
type preVdlConfigRemoteAuthBasic struct {
	UserEnv *string `json:"userEnv"`
	PassEnv *string `json:"passEnv"`
}

// validate reports whether preVdlConfigRemoteAuthBasic satisfies strict JSON requirements.
func (p *preVdlConfigRemoteAuthBasic) validate(parentPath string) error {
	vdlPathUserEnv := "userEnv"
	if parentPath != "" {
		vdlPathUserEnv = parentPath + ".userEnv"
	}
	if p.UserEnv == nil {
		return fmt.Errorf("field %s is required", vdlPathUserEnv)
	}

	vdlPathPassEnv := "passEnv"
	if parentPath != "" {
		vdlPathPassEnv = parentPath + ".passEnv"
	}
	if p.PassEnv == nil {
		return fmt.Errorf("field %s is required", vdlPathPassEnv)
	}
	return nil
}

// transform converts preVdlConfigRemoteAuthBasic to VdlConfigRemoteAuthBasic.
func (p *preVdlConfigRemoteAuthBasic) transform() VdlConfigRemoteAuthBasic {
	var transUserEnv string
	transUserEnv = *p.UserEnv

	var transPassEnv string
	transPassEnv = *p.PassEnv

	return VdlConfigRemoteAuthBasic{
		UserEnv: transUserEnv,
		PassEnv: transPassEnv,
	}
}

// UnmarshalJSON decodes VdlConfigRemoteAuthBasic while requiring every non-optional JSON field.
func (x *VdlConfigRemoteAuthBasic) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigRemoteAuthBasic
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetUserEnv returns the UserEnv field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemoteAuthBasic) GetUserEnv() string {
	if x != nil {
		return x.UserEnv
	}
	var zero string
	return zero
}

// GetUserEnvOr returns the UserEnv field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemoteAuthBasic) GetUserEnvOr(defaultValue string) string {
	if x != nil {
		return x.UserEnv
	}
	return defaultValue
}

// GetPassEnv returns the PassEnv field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemoteAuthBasic) GetPassEnv() string {
	if x != nil {
		return x.PassEnv
	}
	var zero string
	return zero
}

// GetPassEnvOr returns the PassEnv field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemoteAuthBasic) GetPassEnvOr(defaultValue string) string {
	if x != nil {
		return x.PassEnv
	}
	return defaultValue
}

// Bearer token authentication configuration. The environment variable should contain
// the token to be sent as a header with the name "Authorization" and the value
// will be "Bearer <token>".
type VdlConfigRemoteAuthBearer struct {
	// The name of the environment variable that contains the bearer token to be sent.
	TokenEnv string `json:"tokenEnv"`
}

// preVdlConfigRemoteAuthBearer mirrors VdlConfigRemoteAuthBearer during strict JSON decoding.
type preVdlConfigRemoteAuthBearer struct {
	TokenEnv *string `json:"tokenEnv"`
}

// validate reports whether preVdlConfigRemoteAuthBearer satisfies strict JSON requirements.
func (p *preVdlConfigRemoteAuthBearer) validate(parentPath string) error {
	vdlPathTokenEnv := "tokenEnv"
	if parentPath != "" {
		vdlPathTokenEnv = parentPath + ".tokenEnv"
	}
	if p.TokenEnv == nil {
		return fmt.Errorf("field %s is required", vdlPathTokenEnv)
	}
	return nil
}

// transform converts preVdlConfigRemoteAuthBearer to VdlConfigRemoteAuthBearer.
func (p *preVdlConfigRemoteAuthBearer) transform() VdlConfigRemoteAuthBearer {
	var transTokenEnv string
	transTokenEnv = *p.TokenEnv

	return VdlConfigRemoteAuthBearer{
		TokenEnv: transTokenEnv,
	}
}

// UnmarshalJSON decodes VdlConfigRemoteAuthBearer while requiring every non-optional JSON field.
func (x *VdlConfigRemoteAuthBearer) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigRemoteAuthBearer
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetTokenEnv returns the TokenEnv field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemoteAuthBearer) GetTokenEnv() string {
	if x != nil {
		return x.TokenEnv
	}
	var zero string
	return zero
}

// GetTokenEnvOr returns the TokenEnv field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemoteAuthBearer) GetTokenEnvOr(defaultValue string) string {
	if x != nil {
		return x.TokenEnv
	}
	return defaultValue
}

// GitHub authentication configuration. The environment variable should contain a
// GitHub Personal Access Token (PAT). The token should have "repo" scope for private
// repos or "public_repo" scope for public repos.
type VdlConfigRemoteAuthGithub struct {
	// The name of the environment variable that contains the GitHub Personal Access Token (PAT).
	TokenEnv string `json:"tokenEnv"`
}

// preVdlConfigRemoteAuthGithub mirrors VdlConfigRemoteAuthGithub during strict JSON decoding.
type preVdlConfigRemoteAuthGithub struct {
	TokenEnv *string `json:"tokenEnv"`
}

// validate reports whether preVdlConfigRemoteAuthGithub satisfies strict JSON requirements.
func (p *preVdlConfigRemoteAuthGithub) validate(parentPath string) error {
	vdlPathTokenEnv := "tokenEnv"
	if parentPath != "" {
		vdlPathTokenEnv = parentPath + ".tokenEnv"
	}
	if p.TokenEnv == nil {
		return fmt.Errorf("field %s is required", vdlPathTokenEnv)
	}
	return nil
}

// transform converts preVdlConfigRemoteAuthGithub to VdlConfigRemoteAuthGithub.
func (p *preVdlConfigRemoteAuthGithub) transform() VdlConfigRemoteAuthGithub {
	var transTokenEnv string
	transTokenEnv = *p.TokenEnv

	return VdlConfigRemoteAuthGithub{
		TokenEnv: transTokenEnv,
	}
}

// UnmarshalJSON decodes VdlConfigRemoteAuthGithub while requiring every non-optional JSON field.
func (x *VdlConfigRemoteAuthGithub) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigRemoteAuthGithub
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetTokenEnv returns the TokenEnv field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemoteAuthGithub) GetTokenEnv() string {
	if x != nil {
		return x.TokenEnv
	}
	var zero string
	return zero
}

// GetTokenEnvOr returns the TokenEnv field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemoteAuthGithub) GetTokenEnvOr(defaultValue string) string {
	if x != nil {
		return x.TokenEnv
	}
	return defaultValue
}

// Header-based authentication configuration. The environment variables should contain the header
// name and value to be sent with each request to the remote host.
type VdlConfigRemoteAuthHeader struct {
	// The name of the environment variable that contains the header name to be sent.
	NameEnv string `json:"nameEnv"`
	// The name of the environment variable that contains the header value to be sent.
	ValueEnv string `json:"valueEnv"`
}

// preVdlConfigRemoteAuthHeader mirrors VdlConfigRemoteAuthHeader during strict JSON decoding.
type preVdlConfigRemoteAuthHeader struct {
	NameEnv  *string `json:"nameEnv"`
	ValueEnv *string `json:"valueEnv"`
}

// validate reports whether preVdlConfigRemoteAuthHeader satisfies strict JSON requirements.
func (p *preVdlConfigRemoteAuthHeader) validate(parentPath string) error {
	vdlPathNameEnv := "nameEnv"
	if parentPath != "" {
		vdlPathNameEnv = parentPath + ".nameEnv"
	}
	if p.NameEnv == nil {
		return fmt.Errorf("field %s is required", vdlPathNameEnv)
	}

	vdlPathValueEnv := "valueEnv"
	if parentPath != "" {
		vdlPathValueEnv = parentPath + ".valueEnv"
	}
	if p.ValueEnv == nil {
		return fmt.Errorf("field %s is required", vdlPathValueEnv)
	}
	return nil
}

// transform converts preVdlConfigRemoteAuthHeader to VdlConfigRemoteAuthHeader.
func (p *preVdlConfigRemoteAuthHeader) transform() VdlConfigRemoteAuthHeader {
	var transNameEnv string
	transNameEnv = *p.NameEnv

	var transValueEnv string
	transValueEnv = *p.ValueEnv

	return VdlConfigRemoteAuthHeader{
		NameEnv:  transNameEnv,
		ValueEnv: transValueEnv,
	}
}

// UnmarshalJSON decodes VdlConfigRemoteAuthHeader while requiring every non-optional JSON field.
func (x *VdlConfigRemoteAuthHeader) UnmarshalJSON(data []byte) error {
	var pre preVdlConfigRemoteAuthHeader
	if err := json.Unmarshal(data, &pre); err != nil {
		return err
	}
	if err := pre.validate(""); err != nil {
		return err
	}
	*x = pre.transform()
	return nil
}

// GetNameEnv returns the NameEnv field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemoteAuthHeader) GetNameEnv() string {
	if x != nil {
		return x.NameEnv
	}
	var zero string
	return zero
}

// GetNameEnvOr returns the NameEnv field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemoteAuthHeader) GetNameEnvOr(defaultValue string) string {
	if x != nil {
		return x.NameEnv
	}
	return defaultValue
}

// GetValueEnv returns the ValueEnv field. It returns the zero value when the receiver is nil.
func (x *VdlConfigRemoteAuthHeader) GetValueEnv() string {
	if x != nil {
		return x.ValueEnv
	}
	var zero string
	return zero
}

// GetValueEnvOr returns the ValueEnv field. It returns defaultValue when the receiver is nil.
func (x *VdlConfigRemoteAuthHeader) GetValueEnvOr(defaultValue string) string {
	if x != nil {
		return x.ValueEnv
	}
	return defaultValue
}
