package codegen

import (
	"context"

	"github.com/varavelio/vdl/toolchain/internal/core/ir"
)

// File represents a virtual file generated by the compiler.
// It is not written to disk yet.
type File struct {
	// RelativePath is the path relative to the output directory.
	// Examples: "types.go", "src/client.ts", "internal/api/handler.go"
	RelativePath string

	// Content is the raw bytes of the file.
	Content []byte
}

// Generator is the common interface for all VDL backends.
type Generator interface {
	// Name returns the unique name of the generator (e.g., "golang", "typescript").
	Name() string

	// Generate produces a set of files based on the intermediate representation.
	// It does NOT write to disk.
	Generate(ctx context.Context, schema *ir.Schema) ([]File, error)
}
