// Code generated by VDL v0.0.0-dev. DO NOT EDIT.
// If you edit this file, it will be overwritten the next time it is generated.
//
// For more information about VDL, visit https://vdl.varavel.com

/* eslint-disable */
/* tslint:disable */
// biome-ignore-all lint: Generated by VDL

// -----------------------------------------------------------------------------
// Enumerations
// -----------------------------------------------------------------------------

/**
 * Represents a target for codegen function
 */
export type CodegenTarget = "Go" | "Typescript" | "Dart" | "Python" | "OpenApi" | "JsonSchema";

export const CodegenTargetList: CodegenTarget[] = [
  "Go",
  "Typescript",
  "Dart",
  "Python",
  "OpenApi",
  "JsonSchema",
];

export function isCodegenTarget(value: unknown): value is CodegenTarget {
  return CodegenTargetList.includes(value as CodegenTarget);
}

/**
 * Import extension for typescript code generator
 */
export type CodegenTypescriptImportExtension = "none" | ".js" | ".ts";

export const CodegenTypescriptImportExtensionList: CodegenTypescriptImportExtension[] = [
  "none",
  ".js",
  ".ts",
];

export function isCodegenTypescriptImportExtension(value: unknown): value is CodegenTypescriptImportExtension {
  return CodegenTypescriptImportExtensionList.includes(value as CodegenTypescriptImportExtension);
}

/**
 * Represents a function to be called via WASM
 */
export type WasmFunctionName = "ExpandTypes" | "ExtractType" | "ExtractProc" | "ExtractStream" | "Codegen";

export const WasmFunctionNameList: WasmFunctionName[] = [
  "ExpandTypes",
  "ExtractType",
  "ExtractProc",
  "ExtractStream",
  "Codegen",
];

export function isWasmFunctionName(value: unknown): value is WasmFunctionName {
  return WasmFunctionNameList.includes(value as WasmFunctionName);
}

// -----------------------------------------------------------------------------
// Domain Types
// -----------------------------------------------------------------------------

/**
 * CodegenFile Rrepresents a file generated by codegen function
 */
export type CodegenFile = {
  path: string
  content: string
}

export function hydrateCodegenFile(input: CodegenFile): CodegenFile {
  const hydratedPath = input.path
  const hydratedContent = input.content
  return {
    path: hydratedPath,
    content: hydratedContent,
  }
}

export function validateCodegenFile(_input: unknown, _path = "CodegenFile"): string | null {
  return null;
}

/**
 * CodegenInput Input for codegen function
 */
export type CodegenInput = {
  vdlSchema: string
  target: CodegenTarget
  goConfig?: CodegenInputGoConfig
  typescriptConfig?: CodegenInputTypescriptConfig
  dartConfig?: CodegenInputDartConfig
  pythonConfig?: CodegenInputPythonConfig
  jsonSchemaConfig?: CodegenInputJsonSchemaConfig
  openApiConfig?: CodegenInputOpenApiConfig
}

export type CodegenInputGoConfig = {
  package: string
  genPatterns: boolean
  genConsts: boolean
  genClient: boolean
  genServer: boolean
}

export type CodegenInputTypescriptConfig = {
  importExtension: CodegenTypescriptImportExtension
  genPatterns: boolean
  genConsts: boolean
  genClient: boolean
  genServer: boolean
}

export type CodegenInputDartConfig = {
  genPatterns: boolean
  genConsts: boolean
}

export type CodegenInputPythonConfig = {
  genPatterns: boolean
  genConsts: boolean
}

export type CodegenInputJsonSchemaConfig = {
  schemaId: string
}

export type CodegenInputOpenApiConfig = {
  title: string
  version: string
  description?: string
  baseUrl?: string
  contactName?: string
  contactEmail?: string
  licenseName?: string
}

export function hydrateCodegenInput(input: CodegenInput): CodegenInput {
  const hydratedVdlSchema = input.vdlSchema
  const hydratedTarget = input.target
  const hydratedGoConfig = input.goConfig ? hydrateCodegenInputGoConfig(input.goConfig) : input.goConfig
  const hydratedTypescriptConfig = input.typescriptConfig ? hydrateCodegenInputTypescriptConfig(input.typescriptConfig) : input.typescriptConfig
  const hydratedDartConfig = input.dartConfig ? hydrateCodegenInputDartConfig(input.dartConfig) : input.dartConfig
  const hydratedPythonConfig = input.pythonConfig ? hydrateCodegenInputPythonConfig(input.pythonConfig) : input.pythonConfig
  const hydratedJsonSchemaConfig = input.jsonSchemaConfig ? hydrateCodegenInputJsonSchemaConfig(input.jsonSchemaConfig) : input.jsonSchemaConfig
  const hydratedOpenApiConfig = input.openApiConfig ? hydrateCodegenInputOpenApiConfig(input.openApiConfig) : input.openApiConfig
  return {
    vdlSchema: hydratedVdlSchema,
    target: hydratedTarget,
    goConfig: hydratedGoConfig,
    typescriptConfig: hydratedTypescriptConfig,
    dartConfig: hydratedDartConfig,
    pythonConfig: hydratedPythonConfig,
    jsonSchemaConfig: hydratedJsonSchemaConfig,
    openApiConfig: hydratedOpenApiConfig,
  }
}

export function hydrateCodegenInputGoConfig(input: CodegenInputGoConfig): CodegenInputGoConfig {
  const hydratedPackage = input.package
  const hydratedGenPatterns = input.genPatterns
  const hydratedGenConsts = input.genConsts
  const hydratedGenClient = input.genClient
  const hydratedGenServer = input.genServer
  return {
    package: hydratedPackage,
    genPatterns: hydratedGenPatterns,
    genConsts: hydratedGenConsts,
    genClient: hydratedGenClient,
    genServer: hydratedGenServer,
  }
}

export function hydrateCodegenInputTypescriptConfig(input: CodegenInputTypescriptConfig): CodegenInputTypescriptConfig {
  const hydratedImportExtension = input.importExtension
  const hydratedGenPatterns = input.genPatterns
  const hydratedGenConsts = input.genConsts
  const hydratedGenClient = input.genClient
  const hydratedGenServer = input.genServer
  return {
    importExtension: hydratedImportExtension,
    genPatterns: hydratedGenPatterns,
    genConsts: hydratedGenConsts,
    genClient: hydratedGenClient,
    genServer: hydratedGenServer,
  }
}

export function hydrateCodegenInputDartConfig(input: CodegenInputDartConfig): CodegenInputDartConfig {
  const hydratedGenPatterns = input.genPatterns
  const hydratedGenConsts = input.genConsts
  return {
    genPatterns: hydratedGenPatterns,
    genConsts: hydratedGenConsts,
  }
}

export function hydrateCodegenInputPythonConfig(input: CodegenInputPythonConfig): CodegenInputPythonConfig {
  const hydratedGenPatterns = input.genPatterns
  const hydratedGenConsts = input.genConsts
  return {
    genPatterns: hydratedGenPatterns,
    genConsts: hydratedGenConsts,
  }
}

export function hydrateCodegenInputJsonSchemaConfig(input: CodegenInputJsonSchemaConfig): CodegenInputJsonSchemaConfig {
  const hydratedSchemaId = input.schemaId
  return {
    schemaId: hydratedSchemaId,
  }
}

export function hydrateCodegenInputOpenApiConfig(input: CodegenInputOpenApiConfig): CodegenInputOpenApiConfig {
  const hydratedTitle = input.title
  const hydratedVersion = input.version
  const hydratedDescription = input.description ? input.description : input.description
  const hydratedBaseUrl = input.baseUrl ? input.baseUrl : input.baseUrl
  const hydratedContactName = input.contactName ? input.contactName : input.contactName
  const hydratedContactEmail = input.contactEmail ? input.contactEmail : input.contactEmail
  const hydratedLicenseName = input.licenseName ? input.licenseName : input.licenseName
  return {
    title: hydratedTitle,
    version: hydratedVersion,
    description: hydratedDescription,
    baseUrl: hydratedBaseUrl,
    contactName: hydratedContactName,
    contactEmail: hydratedContactEmail,
    licenseName: hydratedLicenseName,
  }
}

export function validateCodegenInput(input: unknown, path = "CodegenInput"): string | null {
  if (input === null || input === undefined || typeof input !== "object") {
    return `${path}: expected object, got ${typeof input}`;
  }
  const obj = input as Record<string, unknown>;

  if (obj.target === undefined || obj.target === null) {
    return `${path}.target: required field is missing`;
  }
  {
    if (!isCodegenTarget(obj.target)) {
      return `${path}.target: invalid enum value '${obj.target}' for CodegenTarget`;
    }
  }
  if (obj.typescriptConfig !== undefined && obj.typescriptConfig !== null) {
    {
      const err = validateCodegenInputTypescriptConfig(obj.typescriptConfig, `${path}.typescriptConfig`);
      if (err !== null) return err;
    }
  }
  return null;
}

export function validateCodegenInputGoConfig(_input: unknown, _path = "CodegenInputGoConfig"): string | null {
  return null;
}

export function validateCodegenInputTypescriptConfig(input: unknown, path = "CodegenInputTypescriptConfig"): string | null {
  if (input === null || input === undefined || typeof input !== "object") {
    return `${path}: expected object, got ${typeof input}`;
  }
  const obj = input as Record<string, unknown>;

  if (obj.importExtension === undefined || obj.importExtension === null) {
    return `${path}.importExtension: required field is missing`;
  }
  {
    if (!isCodegenTypescriptImportExtension(obj.importExtension)) {
      return `${path}.importExtension: invalid enum value '${obj.importExtension}' for CodegenTypescriptImportExtension`;
    }
  }
  return null;
}

export function validateCodegenInputDartConfig(_input: unknown, _path = "CodegenInputDartConfig"): string | null {
  return null;
}

export function validateCodegenInputPythonConfig(_input: unknown, _path = "CodegenInputPythonConfig"): string | null {
  return null;
}

export function validateCodegenInputJsonSchemaConfig(_input: unknown, _path = "CodegenInputJsonSchemaConfig"): string | null {
  return null;
}

export function validateCodegenInputOpenApiConfig(_input: unknown, _path = "CodegenInputOpenApiConfig"): string | null {
  return null;
}

/**
 * CodegenOutput Output for codegen function
 */
export type CodegenOutput = {
  files: CodegenFile[]
}

export function hydrateCodegenOutput(input: CodegenOutput): CodegenOutput {
  const hydratedFiles = input.files.map(el => hydrateCodegenFile(el))
  return {
    files: hydratedFiles,
  }
}

export function validateCodegenOutput(input: unknown, path = "CodegenOutput"): string | null {
  if (input === null || input === undefined || typeof input !== "object") {
    return `${path}: expected object, got ${typeof input}`;
  }
  const obj = input as Record<string, unknown>;

  if (obj.files === undefined || obj.files === null) {
    return `${path}.files: required field is missing`;
  }
  {
    if (!Array.isArray(obj.files)) {
      return `${path}.files: expected array, got ${typeof obj.files}`;
    }
    for (let i = 0; i < obj.files.length; i++) {
      {
        const err = validateCodegenFile(obj.files[i], `${path}.files[${i}]`);
        if (err !== null) return err;
      }
    }
  }
  return null;
}

/**
 * ExpandTypesInput Input for expandTypes function
 */
export type ExpandTypesInput = {
  vdlSchema: string
}

export function hydrateExpandTypesInput(input: ExpandTypesInput): ExpandTypesInput {
  const hydratedVdlSchema = input.vdlSchema
  return {
    vdlSchema: hydratedVdlSchema,
  }
}

export function validateExpandTypesInput(_input: unknown, _path = "ExpandTypesInput"): string | null {
  return null;
}

/**
 * ExpandTypesOutput Output for expandTypes function
 */
export type ExpandTypesOutput = {
  expandedSchema: string
}

export function hydrateExpandTypesOutput(input: ExpandTypesOutput): ExpandTypesOutput {
  const hydratedExpandedSchema = input.expandedSchema
  return {
    expandedSchema: hydratedExpandedSchema,
  }
}

export function validateExpandTypesOutput(_input: unknown, _path = "ExpandTypesOutput"): string | null {
  return null;
}

/**
 * ExtractProcInput Input for extractProc function
 */
export type ExtractProcInput = {
  vdlSchema: string
  rpcName: string
  procName: string
}

export function hydrateExtractProcInput(input: ExtractProcInput): ExtractProcInput {
  const hydratedVdlSchema = input.vdlSchema
  const hydratedRpcName = input.rpcName
  const hydratedProcName = input.procName
  return {
    vdlSchema: hydratedVdlSchema,
    rpcName: hydratedRpcName,
    procName: hydratedProcName,
  }
}

export function validateExtractProcInput(_input: unknown, _path = "ExtractProcInput"): string | null {
  return null;
}

/**
 * ExtractProcOutput Output for extractProc function
 */
export type ExtractProcOutput = {
  procSchema: string
}

export function hydrateExtractProcOutput(input: ExtractProcOutput): ExtractProcOutput {
  const hydratedProcSchema = input.procSchema
  return {
    procSchema: hydratedProcSchema,
  }
}

export function validateExtractProcOutput(_input: unknown, _path = "ExtractProcOutput"): string | null {
  return null;
}

/**
 * ExtractStreamInput Input for extractStream function
 */
export type ExtractStreamInput = {
  vdlSchema: string
  rpcName: string
  streamName: string
}

export function hydrateExtractStreamInput(input: ExtractStreamInput): ExtractStreamInput {
  const hydratedVdlSchema = input.vdlSchema
  const hydratedRpcName = input.rpcName
  const hydratedStreamName = input.streamName
  return {
    vdlSchema: hydratedVdlSchema,
    rpcName: hydratedRpcName,
    streamName: hydratedStreamName,
  }
}

export function validateExtractStreamInput(_input: unknown, _path = "ExtractStreamInput"): string | null {
  return null;
}

/**
 * ExtractStreamOutput Output for extractStream function
 */
export type ExtractStreamOutput = {
  streamSchema: string
}

export function hydrateExtractStreamOutput(input: ExtractStreamOutput): ExtractStreamOutput {
  const hydratedStreamSchema = input.streamSchema
  return {
    streamSchema: hydratedStreamSchema,
  }
}

export function validateExtractStreamOutput(_input: unknown, _path = "ExtractStreamOutput"): string | null {
  return null;
}

/**
 * ExtractTypeInput Input for extractType function
 */
export type ExtractTypeInput = {
  vdlSchema: string
  typeName: string
}

export function hydrateExtractTypeInput(input: ExtractTypeInput): ExtractTypeInput {
  const hydratedVdlSchema = input.vdlSchema
  const hydratedTypeName = input.typeName
  return {
    vdlSchema: hydratedVdlSchema,
    typeName: hydratedTypeName,
  }
}

export function validateExtractTypeInput(_input: unknown, _path = "ExtractTypeInput"): string | null {
  return null;
}

/**
 * ExtractTypeOutput Output for extractType function
 */
export type ExtractTypeOutput = {
  typeSchema: string
}

export function hydrateExtractTypeOutput(input: ExtractTypeOutput): ExtractTypeOutput {
  const hydratedTypeSchema = input.typeSchema
  return {
    typeSchema: hydratedTypeSchema,
  }
}

export function validateExtractTypeOutput(_input: unknown, _path = "ExtractTypeOutput"): string | null {
  return null;
}

/**
 * WasmInput The input for the WASM function call
 */
export type WasmInput = {
  functionName: WasmFunctionName
  expandTypes?: ExpandTypesInput
  extractType?: ExtractTypeInput
  extractProc?: ExtractProcInput
  extractStream?: ExtractStreamInput
  codegen?: CodegenInput
}

export function hydrateWasmInput(input: WasmInput): WasmInput {
  const hydratedFunctionName = input.functionName
  const hydratedExpandTypes = input.expandTypes ? hydrateExpandTypesInput(input.expandTypes) : input.expandTypes
  const hydratedExtractType = input.extractType ? hydrateExtractTypeInput(input.extractType) : input.extractType
  const hydratedExtractProc = input.extractProc ? hydrateExtractProcInput(input.extractProc) : input.extractProc
  const hydratedExtractStream = input.extractStream ? hydrateExtractStreamInput(input.extractStream) : input.extractStream
  const hydratedCodegen = input.codegen ? hydrateCodegenInput(input.codegen) : input.codegen
  return {
    functionName: hydratedFunctionName,
    expandTypes: hydratedExpandTypes,
    extractType: hydratedExtractType,
    extractProc: hydratedExtractProc,
    extractStream: hydratedExtractStream,
    codegen: hydratedCodegen,
  }
}

export function validateWasmInput(input: unknown, path = "WasmInput"): string | null {
  if (input === null || input === undefined || typeof input !== "object") {
    return `${path}: expected object, got ${typeof input}`;
  }
  const obj = input as Record<string, unknown>;

  if (obj.functionName === undefined || obj.functionName === null) {
    return `${path}.functionName: required field is missing`;
  }
  {
    if (!isWasmFunctionName(obj.functionName)) {
      return `${path}.functionName: invalid enum value '${obj.functionName}' for WasmFunctionName`;
    }
  }
  if (obj.expandTypes !== undefined && obj.expandTypes !== null) {
    {
      const err = validateExpandTypesInput(obj.expandTypes, `${path}.expandTypes`);
      if (err !== null) return err;
    }
  }
  if (obj.extractType !== undefined && obj.extractType !== null) {
    {
      const err = validateExtractTypeInput(obj.extractType, `${path}.extractType`);
      if (err !== null) return err;
    }
  }
  if (obj.extractProc !== undefined && obj.extractProc !== null) {
    {
      const err = validateExtractProcInput(obj.extractProc, `${path}.extractProc`);
      if (err !== null) return err;
    }
  }
  if (obj.extractStream !== undefined && obj.extractStream !== null) {
    {
      const err = validateExtractStreamInput(obj.extractStream, `${path}.extractStream`);
      if (err !== null) return err;
    }
  }
  if (obj.codegen !== undefined && obj.codegen !== null) {
    {
      const err = validateCodegenInput(obj.codegen, `${path}.codegen`);
      if (err !== null) return err;
    }
  }
  return null;
}

/**
 * WasmOutput The output for the WASM function call
 */
export type WasmOutput = {
  expandTypes?: ExpandTypesOutput
  extractType?: ExtractTypeOutput
  extractProc?: ExtractProcOutput
  extractStream?: ExtractStreamOutput
  codegen?: CodegenOutput
}

export function hydrateWasmOutput(input: WasmOutput): WasmOutput {
  const hydratedExpandTypes = input.expandTypes ? hydrateExpandTypesOutput(input.expandTypes) : input.expandTypes
  const hydratedExtractType = input.extractType ? hydrateExtractTypeOutput(input.extractType) : input.extractType
  const hydratedExtractProc = input.extractProc ? hydrateExtractProcOutput(input.extractProc) : input.extractProc
  const hydratedExtractStream = input.extractStream ? hydrateExtractStreamOutput(input.extractStream) : input.extractStream
  const hydratedCodegen = input.codegen ? hydrateCodegenOutput(input.codegen) : input.codegen
  return {
    expandTypes: hydratedExpandTypes,
    extractType: hydratedExtractType,
    extractProc: hydratedExtractProc,
    extractStream: hydratedExtractStream,
    codegen: hydratedCodegen,
  }
}

export function validateWasmOutput(input: unknown, path = "WasmOutput"): string | null {
  if (input === null || input === undefined || typeof input !== "object") {
    return `${path}: expected object, got ${typeof input}`;
  }
  const obj = input as Record<string, unknown>;

  if (obj.expandTypes !== undefined && obj.expandTypes !== null) {
    {
      const err = validateExpandTypesOutput(obj.expandTypes, `${path}.expandTypes`);
      if (err !== null) return err;
    }
  }
  if (obj.extractType !== undefined && obj.extractType !== null) {
    {
      const err = validateExtractTypeOutput(obj.extractType, `${path}.extractType`);
      if (err !== null) return err;
    }
  }
  if (obj.extractProc !== undefined && obj.extractProc !== null) {
    {
      const err = validateExtractProcOutput(obj.extractProc, `${path}.extractProc`);
      if (err !== null) return err;
    }
  }
  if (obj.extractStream !== undefined && obj.extractStream !== null) {
    {
      const err = validateExtractStreamOutput(obj.extractStream, `${path}.extractStream`);
      if (err !== null) return err;
    }
  }
  if (obj.codegen !== undefined && obj.codegen !== null) {
    {
      const err = validateCodegenOutput(obj.codegen, `${path}.codegen`);
      if (err !== null) return err;
    }
  }
  return null;
}
