title = "Varavel Definition Language"
description = "VDL is an open-source, type-safe, multi-language, and easily extensible schema definition language and code generation toolchain."
base_url = "https://vdl.varavel.com"
minify_html = true
theme = "varapress"

[markdown.highlighting]
theme = "github-dark"
extra_grammars = ["../editors/vscode/language/vdl.tmLanguage.json"]
# extra_grammars = ["themes/varapress/grammars/vdl.json"]

[extra]
varapress_logo_light = "https://cdn.jsdelivr.net/gh/varavelio/vdl@a6a9ea/assets/svg/vdl.svg"
varapress_logo_dark = "https://cdn.jsdelivr.net/gh/varavelio/vdl@a6a9ea/assets/svg/vdl.svg"
varapress_favicon = "https://cdn.jsdelivr.net/gh/varavelio/vdl@a6a9ea/assets/svg/icon.svg"
varapress_github_repo = "varavelio/vdl"
varapress_show_title = false
varapress_llms = true
varapress_llms_full = true
varapress_llms_description_chars = 100
